### ISSUE TITLE
`augur backend start` prints incorrect address and port

### ISSUE THREAD

**Issue by zachs18** [chaoss/augur#1018]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
`augur backend start` prints the wrong address and port.

**How to reproduce:**
1. Change the backend server port in augur.config.json
2. Start the backed with `augur backend start`

**Expected behavior:**
Augur prints the address and port it is running at.

**Actual behavior:**
Line 46 of `augur/cli/backend.py` prints the string `"Augur is running at: http://0.0.0.0:5000"` no matter what port/address it is configured to use.

A temporary hack-fix is to change line 46 from
`logger.info(f"Augur is running at: http://0.0.0.0:5000")` to `logger.info(f"Augur is running at: {augur_app.gunicorn_options['bind']}")`

**Software versions:**
 - Augur: dev branch commit 77e7ea8a5ef48b71090a17e6a3f55c3f9165788c
 - OS: Ubuntu 20.04.1

**Comment by Sherlock2505** [comment]
I want to work on this issue can you please assign this to me?

**Comment by AllMight2099** [comment]
I feel that the temporary hack fix could actually be the permanent solution.  Could you elaborate on how you think it's a temporary fix considering that you just need to send in the port number as a variable in the print statement

**Comment by sgoggins** [comment]
Closing issue. its fixed in PR #1133
