### ISSUE TITLE
More Inline Comments

### ISSUE THREAD

**Issue by jackm357** [chaoss/augur#1060]
**Description of the problem:**
After working on the Augur project this semester, my team and I have noticed that there is a shortage of inline comments.  Inline comments are very helpful to newcomers and make the code much easier to read.  Given this is an open source project there are many contributors that come and go.  For this reason we believe that it would be good to have more of these inline comments.

**Potential solutions:**
As part of our project, my team and I read through a lot of the augur code and wrote inline comments to describe the processes taking place.  Our most notable contribution is in the message_sentiment.py file on the ml-sentiment-patch branch.  We feel that writing inline comments is a good practice for new contributors.  It helps both the comment writer and future comment readers understand the code better.

**Comment by Arnab11917676** [comment]
hello @jackm357 I can work on this issue and can resolve your concern about the comments

**Comment by sgoggins** [comment]
@chaoss/augurdevelopers : More inline comments in the code. 

MORE INLINE COMMENTS IN THE CODE.  Especially highly abstracted things like the worker_base.py.
