### ISSUE TITLE
Perceval Connector: Mailing Lists

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#108]
We are piloting our perceval connector using mailing lists.  

## Open Daylight Mailing Lists

1. Lists enumerated at: https://lists.opendaylight.org/mailman/listinfo
2. Using perceval, they can be gathered one at a time as so:
```bash
 perceval pipermail 'https://lists.opendaylight.org/pipermail/aaa-dev/' -o opendaylight-aaa-dev.json
 ```
3. Goals:
	- Iterate through all the mailing lists
	- Pull them down
	- Parse them into message threads stored in a database schema

## Other Mailing Lists:

1. Seems as though the parameters for --mboxes-path and -o may simultaneously execute?  
```bash
perceval pipermail 'http://lists.openstack.org/pipermail/openstack/' -o openstack.json --mboxes-path 'openstack'
perceval pipermail 'http://lists.openstack.org/pipermail/openstack/' -o openstack.json
perceval pipermail 'http://lists.digium.com/pipermail/asterisk-dev/' -o 'asterisk-dev.json' --mboxes-path 'asterisk-dev' --from-date '2004-01-01'
perceval pipermail 'http://lists.digium.com/pipermail/asterisk-users/' -o 'asterisk-users.json' --mboxes-path 'asterisk-users' --from-date '2004-01-01'
perceval pipermail 'http://lists.digium.com/pipermail/asterisk-biz/' -o 'asterisk-biz.json' --mboxes-path 'asterisk-biz' --from-date '2004-01-01'
```
2. Linux Foundation: https://lists.linuxfoundation.org/mailman/listinfo

**Comment by kmn5409** [comment]
This is where I've reached so far with the problem but I have an issue with uploading the text to the database, at the moment some of it is too large, most of the text is able to be uploaded but some of the mailing messages is really large for example one of them is I think 7598287 characters. Should I look at maybe encoding the messages so that it can fit into the mysql database?
[https://github.com/kmn5409/GSoC_CHAOSS/blob/master/Augur/Perceval/Piper_reader.py](url)

**Comment by sgoggins** [comment]
@kmn5409 : what database are you using? I think you should truncate from the top.  If they are that big they are almost surely including the very long threads preceding them.

**Comment by sgoggins** [comment]
Check one of the longer messages into your repo as a file.

**Comment by kmn5409** [comment]
@sgoggins I'm using mysql and what do you mean by truncating from the top?

**Comment by sgoggins** [comment]
@kmn5409 : In long running threads, I mean truncating the least recent messages.

**Comment by kmn5409** [comment]
@sgoggins Okay I understand and I think I have an idea of what I will need to do then, thank you.

**Comment by kmn5409** [comment]
https://github.com/kmn5409/GSoC_CHAOSS/blob/master/Augur/Perceval/Piper_reader.py
