### ISSUE TITLE
The function `init_oauths` in `worker_base.py` fails, since the query does not aling with the DB schema

### ISSUE THREAD

**Issue by maxhbr** [chaoss/augur#1086]
The sql query 
https://github.com/chaoss/augur/blob/860d72b81c0fe04dd7c67e7d1be97bc73e7c4ca4/workers/worker_base.py#L685-L687
fails on my system, since the table `access_token` does not have a column `platform`:
```
augur=# select * from augur_operations.worker_oauth;
 oauth_id | name | consumer_key | consumer_secret | access_token | access_token_secret | repo_directory
----------+------+--------------+-----------------+--------------+---------------------+----------------
(0 rows)
```

### My setup is:
- `master` at commit `860d72b81c0fe04dd7c67e7d1be97bc73e7c4ca4`
- oauth token placed in `docker_env.txt`
- started with `$ docker-compose -f docker-compose.yml -f database-compose.yml  up`
  - the pulled versions of the containers are `766668b7da48`, `8d9304199c9a`, `cee20e334823`

**Comment by maxhbr** [comment]
Maybe my pulled image of the database is old. It seems to only contain migrations until `14`:

```
[...]
database_1  | INSERT 0 1
database_1  | INSERT 0 1
database_1  | INSERT 0 1
database_1  | INSERT 0 1
database_1  | INSERT 0 1
database_1  | UPDATE 1
database_1  |
database_1  |
database_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/13-schema_update_15.sql
database_1  | INSERT 0 1
database_1  | UPDATE 1
database_1  |
database_1  |
database_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/14-schema_update_16.sql
database_1  | CREATE SEQUENCE
database_1  | CREATE TABLE
database_1  | ALTER TABLE
database_1  | COMMENT
database_1  | ALTER TABLE
database_1  |  setval
database_1  | --------
database_1  |   25150
database_1  | (1 row)
database_1  |
database_1  | ALTER SEQUENCE
database_1  | UPDATE 1
database_1  |
database_1  |
database_1  | waiting for server to shut down...2021-01-14 13:40:37.361 UTC [45] LOG:  received fast shutdown request
database_1  | .2021-01-14 13:40:37.364 UTC [45] LOG:  aborting any active transactions
database_1  | 2021-01-14 13:40:37.369 UTC [45] LOG:  worker process: logical replication launcher (PID 52) exited with exit code 1
database_1  | 2021-01-14 13:40:37.370 UTC [47] LOG:  shutting down
database_1  | 2021-01-14 13:40:37.458 UTC [45] LOG:  database system is shut down
database_1  |  done
database_1  | server stopped
database_1  |
database_1  | PostgreSQL init process complete; ready for start up.
database_1  |
database_1  | 2021-01-14 13:40:37.494 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1  | 2021-01-14 13:40:37.494 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1  | 2021-01-14 13:40:37.501 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1  | 2021-01-14 13:40:37.540 UTC [190] LOG:  database system was shut down at 2021-01-14 13:40:37 UTC
database_1  | 2021-01-14 13:40:37.547 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by maxhbr** [comment]
the database image on docker hub looks outdated (6 months old):
```
$ docker images | rg augur
augurlabs/augur                                     frontend                                   766668b7da48        2 months ago        146MB
augurlabs/augur                                     backend                                    8d9304199c9a        2 months ago        777MB
augurlabs/augur                                     database                                   cee20e334823        6 months ago        200MB
```

**Comment by ccarterlandis** [comment]
@maxhbr you're spot on in your diagnosis. I'm not sure why the database image is so old, as it is set to automatically update when we push to `master` (same with the `backend` and `frontend` images). I'll update the image and see if I can figure out why it didn't update.

**Comment by maxhbr** [comment]
I no switched to `*-dev` images and they seem to work better and resolve this issue. But I am not able to access `http://localhost:8080/augurface/`, nginx just returns 404.

**Comment by maxhbr** [comment]
The commit https://github.com/chaoss/augur/commit/de52b3258903f2ad520158583db9910a4db199ba deactivates `augurface` in the docker image. Maybe https://oss-augur.readthedocs.io/en/dev/docker/usage.html needs to be updated.

**Comment by maxhbr** [comment]
FYI: I am working on https://github.com/maxhbr/augur/tree/maxhbr/wip, there for example I have enabled augurface again and modified docker compose to build the docker images for me.

**Comment by sgoggins** [comment]
@maxhbr : Thanks!

@ccarterlandis : Can we get together and get dev merged into master. We are way too far behind right now.

**Comment by sgoggins** [comment]
@maxhbr : We are closing out threads from the machine learning workers and @gabe-heim 's bold attempt to put multi-processing into worker_base.py.  Mostly cool, but it crashes to earth on very large repositories ... We are actively working this ... 

THe Docker images are old because @ccarterlandis is our Docker expert and we need some help figuring out why the docker build tests started failing.

**Comment by sgoggins** [comment]
I believe this issue is fixed in our release last Monday, and earlier patch. @maxbalk : Can you confirm it builds for you now?
