### ISSUE TITLE
Add Center for Open Science Instance of Augur

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1148]
# Overview

[Open@RIT](https://www.rit.edu/research/open) uses perceval (along with the rest of the grimoire lab stack) to collect metrics across a variety of academic open research projects. As a center of excellence within RIT, we hope to expand our metrics collected to go beyond simply Free and open source software to other sorts of open programs such as https://osf.io which is an increasingly popular platform for hosting research materials.  This is also a space where Augur could make contributions through our existing work with open source academic and scientific software. 

## Further details

As a first step of adding this support, we want to be able to collect relevant data on users open projects on osf.io through their [API](https://developer.osf.io/#tag/Filtering).

@suhascv is interested in contributing this functionality to perceval and has already started investigating how to do so. Making this available in Augur would be similarly straightforward. 

## Open questions

This will be our first time contributing a backend, it would be great to know about any things we should take into account such as

- Specific required formats of the data we collect
- Relevant documentation or PRs that might be helpful
- Guidelines that aren't otherwise stated in CONTRIBUTING.md and perhaps most importantly...
- If CHAOSS is interested in accepting this new functionality upstream

Happy hacking!

**Comment by SravaniRaniMishra** [comment]
hey , i would like to work on this issue.
