### ISSUE TITLE
Update Visualization Captions and Titles in API : "drive-by" == "fly-by"

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1155]
"Drive-by" has an idiomatic association with urban violence in the US, so we have agreed to change the language from this unintentional association to a more general "Fly-by" language. Though the term "Drive-by" is used in open source more broadly, its replacement in Augur will be easily understood, and the change is lightweight (ish). 

This is only present in the Augur Visualization API, and associated documentation.

**Comment by rohanreddych** [comment]
Hello!! I want to contribute to this. I was trying to run on my computer but `npm run build` gave many errors. So I looked at http://zephyr.osshealth.io/insights/. I think "drive-by" is a type of contributor. But I could not see it being mentioned anywhere, except for contributor_reports.py. Can you please help me?

**Comment by sgoggins** [comment]
Fixed!
