### ISSUE TITLE
GSoC Idea: Advancing Risk Prediction With Machine Learning in Augur

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1179]
# Ideas for Google Summer of Code projects

Interested in working with CHAOSS? Below are some project ideas. We describe how to apply to work with CHAOSS and how we select students on a different page: https://github.com/chaoss/governance/blob/master/GSoC-interest.md

## Idea: Advancing Risk Prediction With Machine Learning in Augur
Currently Augur uses computational linguistics, dependency mapping, license scanning, topic modeling, social network analysis, and algorithms that target temporal changes in CHAOSS metrics. The aim of this project is to leverage and advance existing computational models and algorithms, or develop new ones, to make predictions and identify projects in large ecosystems that are at risk earlier. 

Our theory, for example, is that community decline or the increase in hostile communications is preceded by a decline in empathy, and changes in engagement level. This project will test those theories by directing Augur’s already rich set of AI tools to bear on this specific problem.  The goal of this project is to proactively identify at-risk open source communities:

One possibility would be to pool the existing, six computational models for classifying repositories in open source ecosystems to provide a rich, and complete view of project categories and clusters within a define open source software ecosystem

From the categories identified, projects most at risk will be identified using analysis of each of the six models, and trained with data from projects that are known to have contributed to projects earlier.

The aims of the project are as follows:
  - Identify projects with similar styles and characteristics automatically.
  - Recommend projects based on individual developer styles and skills.
  - Increase awareness of open source project ecosystems, and their component projects.

The aims will require working in a programming language to automate generate a list of at-risk projects, possibly dependencies for other projects, and present insights in the form of collected, persisted table data, and possibly Jupyter Notebook driven UI Design. 

* _Difficulty:_ Medium
* _Requirements:_ Python programming experience, or a strong interest.
* _Recommended:_ Experience with accessing API's, writing SQL, and a strong interest in Machine Learning.
* _Mentors:_ Sean Goggins, Andrew Brain, Vinod Ahuja

Augur is more advanced in its machine learning that basic recommender systems, using TF-IDF, Boosting, Latent Dirchelet Analysis of sequenced conversations, and clustering algorithms that look for similar topics across repositories. 

[The Github Workers that use machine learning are visible in our Workers directory here: ](https://github.com/chaoss/augur/workers). We use our advanced contributor worker to manage identities, and the existing discourse_analysis, message_insights, clustering, insight, and pull_request_worker_analysis workers. Documentation about these existing workers can be found here: https://oss-augur.readthedocs.io/en/dev/development-guide/workers/toc.html

Last year's six new machine learning workers are now an active part of Augur's growing ecosystem. 

The aims of the project are as follows:
  - Identify useful insights for project maintainers, community managers, and open source program offices. 
  - Implement new insights.
  - Integrate insights into our data persistence model. 

The aims will require generating code in **Python** for **FLASK** and the **GraphQL API**, and for the web app, which has now advanced from the  **Vue.js** and **Vuetify** ecosystems to more robust and sustained projects like Twitter/Bootstrap. 

### Microtasks

For becoming familiar with Augur, you can start by reading some documentation. You can find useful information at in the links, below.

Once you're familiar with Augur, you can have a look at the following microtasks.
-   Microtask 0:  
    Download and configure Augur, creating a dev environment using the general cautions noted here: https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html and the full documentation here: https://oss-augur.readthedocs.io/en/dev/development-guide/toc.html  
    
-  Microstask 1: 
   Work on any Augur Issue that's Open

- Microtask 2: 
   Identify new issues you encounter during installation. 

-  Microstask 3: 
   Collection data with an existing machine learning worker

- Microtask 4: 
   Anything you want to show us. Even if you find bugs in our documentation and want to issue a PR for those!

**Comment by SteveKola** [comment]
Hi,

I'm Steven Kolawole, a CS junior from FUNAAB, Nigeria. I'm quite interested in this project idea so I'll get busy with the microtasks.

Thank you for having me. 🙂

**Comment by Venkatavaradan-R** [comment]
Hello!
This project sounds very interesting! Looks like its time to get to work :)

**Comment by Riyabelle25** [comment]
Hey guys!
I have augur all set up, will start data collection soon now. Also looked at the open issues😄

**Comment by Edlison** [comment]
Hi everyone!

I'm really interested in this project and already deploy the environment locally. I will devote myself to the micro-task recently.😃

**Comment by sgoggins** [comment]
If anyone would like access to a larger scale psql backup so you have data for ML, let me know. I can make a gzipped file available, or give you read only access to a db you can selectively download from! @Venkatavaradan-R  / @Edlison  / @Riyabelle25  /  @SteveKola : I'm talking to you. 💯

**Comment by blaze-fire** [comment]
Hello everyone!
I also want to contribute to the project. I am done with the installation. Will start data collection, also looking at open issues

**Comment by sgoggins** [comment]
There have been releases of Augur each of the past two Mondays.  I expect this trend to continue. We have updates to our clustering worker that are exciting!

Collecting data can be time consuming, and I am happy to provide a prepopulated schema.

**Comment by blaze-fire** [comment]
Hello @sgoggins, 
It will be helpful to have a gzipped file available, as mentioned by you, as I am having trouble with data collection 😅.

**Comment by BoxuanZhao** [comment]
Hello everyone！
I'm Boxuan Zhao, a CS graduate student from Shanghai Jiao Tong University, China. I'm really interested in this idea and want to contribute to the project. I have already installed Augur. Now working on looking at open issues and data collection. @sgoggins Could you help me get access to the database you mentioned above?

**Comment by BoxuanZhao** [comment]
By the way, there are some typos in the content: “Augur is more advanced in its machine learning ~~that~~ **than** basic recommender systems”; the Worker directory link may be https://github.com/chaoss/augur/tree/master/workers 😀

**Comment by sgoggins** [comment]
@BoxuanZhao : Do a PR and fix them! :)

**Comment by gymgym1212** [comment]
Hi, I'm Yeming Gu, undertaking master's degree at East China Normal University . It's my first time to participate in the GSoC but not the first time to know about CHAOSS and augur. I'm busy in micro-tasks. Thanks for having me, and let's do some amazing work.

**Comment by sgoggins** [comment]
Everyone, your microtask here could simply be thinking about looking a Jupyter Notebook using https://github.com/chaoss/augur-community-reports that examines the repo_labor table, or pulls data from a package manager API to identify dependencies.  Very simple.

**Comment by gymgym1212** [comment]
@sgoggins , worker page is not found https://github.com/chaoss/augur/workers .

**Comment by BoxuanZhao** [comment]
> @sgoggins , worker page is not found https://github.com/chaoss/augur/workers .

https://github.com/chaoss/augur/tree/master/workers

**Comment by gymgym1212** [comment]
@BoxuanZhao Thank you and I thought these two pages were different before.

**Comment by sgoggins** [comment]
I am leaving this issue open for the convenience of potential GSoC Students for the time being.
