### ISSUE TITLE
GSoC Idea: Automatically identify Contributor Aliases (emails, platform user accounts) to Increase Parsimony of Statistics and Metrics With Privacy Enhancement

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1180]
# Ideas for Google Summer of Code projects

Interested in working with CHAOSS? Below are some project ideas. We describe how to apply to work with CHAOSS and how we select students on a different page: https://github.com/chaoss/governance/blob/master/GSoC-interest.md

Micro-tasks and place for questions https://github.com/chaoss/augur/issues/1180

This project will generalize, and make available through a PyPy distributable Python package the core functionality currently within the Augur contributor worker, and envisioned as the next phase of the Augur contributor worker. A worker is a data collection, machine learning, notification, or mapping daemon that can be managed by Augur for comprehensive data analysis, or installed independently.

[Augur Contributor Worker](https://github.com/chaoss/augur) is the tool that reconciles identities in Augur, using information from Git Platforms, Git Logs, and voluntary mailing lists. The contributor worker is a tool that automatically scans all repository data collected by augur to resolve distinct individuals to all of the often 10 or more aliases they can be identified across different systems.

The aims of the project are as follows:
  - Construct an API Accessible Graph Database for identifying and mapping contributors who use multiple email addresses within a platform, and identifiers across platforms.
  - Implement methods to manage this information.
  - Integrate this information into clearer, more parsimonious CHAOSS metrics.
  - Automate the management of contributor changes over time
  - Enable analysis at the project level that obscures or anonymizes individual developer identity

* _Difficulty:_ Medium
* _Requirements:_ Interest in software analytics. Python programming. JavaScript programming. SQL knowledge.
* _Recommended:_ Experience with Python
* _Mentors:_ Sean Goggins, Andrew Brain, John McGinnis

### Microtasks

Once you're familiar with Augur, you can have a look at the following microtasks.
-   Microtask 0:  
    Download and configure Augur, creating a dev environment using the general cautions noted here: https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html and the full documentation here: https://oss-augur.readthedocs.io/en/dev/development-guide/toc.html  
    
-  Microstask 1: 
   Work on any Augur Issue that's Open

- Microtask 2: 
   Identify new issues you encounter during installation. 

-  Microstask 3: 
   Using a sample set of data you can request in a comment below, evaluate the strengths and weaknesses of the current contributor worker by running it, and opening a new issue with suggestions. 

- Microtask 4: 
   Anything you want to show us. Even if you find bugs in our documentation and want to issue a PR for those!

**Comment by Venkatavaradan-R** [comment]
@sgoggins this Idea/Issue seems to have been repeated by mistake.
#1179 Has the same content!

**Comment by sgoggins** [comment]
@Venkatavaradan-R : Thanks for catching that!  I did this after a hackathon while not feeling well. Sorry about the mistake!  I fixed it!

**Comment by Dhruv-Sachdev1313** [comment]
Hello @sgoggins @ABrain7710 , If a person uses different email-ids within a platform , What key/keys should be considered to map them. For eg: Name or combination of name and something ? . (Here name is not reliable but just for example )
 If I am getting the idea wrong , please do correct me ..

**Comment by sgoggins** [comment]
@Dhruv-Sachdev1313 : The most significant part of this is how we store the data. Commits are the only information we don't get directly from a platform (we use the git log), and most of those emails resolve with the current contributor worker to the individual's github id, which we store. 

However, there are lots of imperfections in practice. For example, we do not identify the most often used email address as associated with the "canonical user ID" in Augur. Perhaps no email should be associated with that individual in the "contributor" table, and all emails should be stored in the "contributor_alias" table.  I'm happy to slack or zoom through the design on this one, and do a show and tell of what we currently have.

**Comment by Dhruv-Sachdev1313** [comment]
@sgoggins A short zoom call would be really helpful . Can we plan that

**Comment by sgoggins** [comment]
I am leaving this issue open for the convenience of potential GSoC Students for the time being.
