### ISSUE TITLE
Implement the hdpmodel module from gensim for topic modeling in the clustering_worker

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1199]
There is significant diversity in the optimal number of topics in a topic model for any given collection of repositories. The hdpmodel module from gensim accommodates this diversity by determining the optimal number of topics for a given collection. Currently, it is preset, and could easily be configurable. However, the number is going to be different for each collection of repositories we do topic modeling for; ergo, and automated way to determine that number is a better approach than what Augur currently does. 

**Potential solutions:**
The description in this post makes it clear that the hdpmodel from gensim will be a better approach, though other implementations of this optimization exist:  https://www.kaggle.com/akashram/topic-modeling-intro-implementation

@sarit-adh may be able to do this as the original author of the worker. 

The current version of the worker is in the `main` branch, though will likely be in the release on Monday, April 8th, 2022.

**Comment by sgoggins** [comment]
Here's another useful link: https://towardsdatascience.com/unsupervised-nlp-topic-models-as-a-supervised-learning-input-cf8ee9e5cf28

**Comment by sgoggins** [comment]
Another useful link: https://nlpforhackers.io/topic-modeling/

**Comment by sgoggins** [comment]
And Another: https://www.machinelearningplus.com/nlp/topic-modeling-gensim-python/#15visualizethetopicskeywords

**Comment by WhiteWolf47** [comment]
I want to work on this issue, I have never used topic modelling. Where can i find the data?

**Comment by WhiteWolf47** [comment]
@sgoggins lets discuss this issue!

**Comment by WhiteWolf47** [comment]
@sgoggins okay, so we are looking forward to replace the current worker model with a hdpmodel (task model). I dont really know how we get the data and what we do with the analyse data, I have searched about hdpmodel and tried its basic implementation , so lets discuss this in depth on saturday (during the CHAOSS Software meeting)

**Comment by sgoggins** [comment]
@WhiteWolf47 : if you are still interested I'll tag this as a first-timers-only issue which gets you direct support and access to the maintainers.

**Comment by sgoggins** [comment]
Turns out this is not the best approach we could come up with! #fixed.

**Comment by Tahamallick** [comment]
I'm interested in contributing to this issue as part of GSoC microtasks. Is anyone actively working on it?
If it's available, can I take this up?

**Comment by Godzilaa** [comment]
@sgoggins  can i contribute anything on this or is it done if theree is to contribute pplease assign me this
