### ISSUE TITLE
Add time period parameterization to merge request (PR) visualization endpionts. 

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1203]
To have the merge request (PR) endpoints include time period parameterization. 

As @ABrain7710 and I discussed, they do not currently, because @sgoggins decided at some point we did not need that for those endpoints. @sgoggins was wrong. 

average PR Duration: Not respecting the month parameter.
http://spos.osshealth.io:5099/api/unstable/pull_request_reports/Average_PR_duration/?repo_id=25531&remove_outliers=0&group_by=month
http://spos.osshealth.io:5099/api/unstable/pull_request_reports/Average_PR_duration/?repo_id=25530&remove_outliers=0&group_by=month
http://spos.osshealth.io:5099/api/unstable/pull_request_reports/Average_PR_duration/?repo_id=25158&remove_outliers=0&group_by=month

**Comment by aparnaabraham** [comment]
Hello, I would like to work on this issue.

**Comment by SravaniRaniMishra** [comment]
hey, this is my first time in the open source community and i would love to work on this issue.
could you please assign it to me
