### ISSUE TITLE
Problem deploying augur

### ISSUE THREAD

**Issue by jphillips3275** [chaoss/augur#1208]
Our group tried to deploy augur using docker on a digital ocean droplet but couldn't get docker compose working. Here is the terminal output we got:
ERROR: for augur_backend_1  Cannot start service backend: driver failed programming external connectivity on endpoint augur_backend_1 (1c0e6949bf1e41e198306064eabdd352e993427f8c9525172c8ba15af4c721ed): Error starting userland proxy:

ERROR: for backend  Cannot start service backend: driver failed programming external connectivity on endpoint augur_backend_1 (1c0e6949bf1e41e198306064eabdd352e993427f8c9525172c8ba15af4c721ed): Error starting userland proxy:
ERROR: Encountered errors while bringing up the project.

**Comment by sgoggins** [comment]
Can you provide a little more information? Is it working locally.

**Comment by jphillips3275** [comment]
It is not currently working locally

**Comment by sgoggins** [comment]
@jphillips3275 : We really need more information than "its not working". 
My suspicion is that there is an issue with digital Ocean, but I cannot know that without some logs, and description of how you deployed it.  Also, if you have a postgres server already running, the database Docker container is going to try to use the same port, and that could cause you trouble.
