### ISSUE TITLE
Problem deploying Augur

### ISSUE THREAD

**Issue by orionkepler** [chaoss/augur#1209]
Our team try to deploy augur on the server, when we run command augur backend start, we can not connect to the database, and the terminal outputs:

conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "vultr.guest" (127.0.1.1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by sgoggins** [comment]
Have you tried connecting to the database locally from the command line?  Something like `psql -U augur -p 5432 -h localhost database_name` ? Are you sure postgres is running? Try `ps -ef | grep postgres` ... if you dont see something like this: 

```
postgres    1648       1  1 Mar16 ?        03:13:05 /usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/12/main -c config_file=/etc/postgresql/12/main/postgresql.conf
postgres    1688    1648  0 Mar16 ?        00:40:42 postgres: 12/main: checkpointer   
postgres    1689    1648  0 Mar16 ?        00:04:56 postgres: 12/main: background writer   
postgres    1690    1648  0 Mar16 ?        00:07:58 postgres: 12/main: walwriter   
postgres    1691    1648  0 Mar16 ?        00:01:00 postgres: 12/main: autovacuum launcher   
postgres    1692    1648  0 Mar16 ?        00:25:49 postgres: 12/main: stats collector   
postgres    1693    1648  0 Mar16 ?        00:00:01 postgres: 12/main: logical replication launcher   
```

Chances are its not running.
