### ISSUE TITLE
Visualizing Issues and PRs

### ISSUE THREAD

**Issue by germonprez** [chaoss/augur#1216]
Hi all,

I'd like to think about a way to include this figure (refine and include?) in the work that Evolution does. It is from our friends on the Asia Pacific call as a way to visualize the Issue/PR processes. 

[Issues:PRs.pptx](https://github.com/chaoss/wg-evolution/files/4774570/Issues.PRs.pptx)

**Comment by sgoggins** [comment]
@germonprez : @ABrain7710 Has these endpoints working as API visualizations, and @Ulincsys is working on a front end for augur that puts these reports on a page. Once that is done, we can also generate a push notified link to a PDF. 
ETA: 3 weeks.

**Comment by sgoggins** [comment]
We have this working now!
