### ISSUE TITLE
Gather GERRIT Change Request Data

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1226]
Following the GitLab and GitHub examples, in the workers/directory, and using functions available in workers/worker_base.py, build a worker that will gather Change Request information from Gerrit repos. 
1. Familiarize yourself with GERRIT API
2. Pull related data
3. Develop into worker.

**Comment by sgoggins** [comment]
This issue can, effectively, copy the pattern in the pull_request_worker, and the gitlab_merge_request_worker, map the Gerrit API to the columns in the related tables, and be completed. Its a great way to learn the Augur Worker architecture.

**Comment by sgoggins** [comment]
@parthsharma2 : I think this issue would be a slam dunk for you, and it would let you see just how far Augur has come in the past two years. :)

**Comment by parthsharma2** [comment]
@sgoggins I have been away for quite some time now & this seems to be a pretty good opportunity to come back :)

Do you have any deadline in mind to get this completed? Will probably need some time to setup Augur + got some work stuff this week. Most probably will be able to begin work on this by the end of this week.

Also, do you have a GERRIT instance hosted somewhere for experimentation?
