### ISSUE TITLE
What does the output 'Housekeeper spawned .... for repo group id 0' mean?

### ISSUE THREAD

**Issue by gymgym1212** [chaoss/augur#1227]
After installation, I create a new repo group with id 50 and add a repo to this group. Continue, I run the `augur backend start`, but it is stuck without more info.
What does the **_repo group id 0_**  mean? And do I get the correct information after `augur backend start`? By the way, I can't find the repo I want in the directory right now.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/37684061/114013484-29497e80-989a-11eb-966a-8a91fb280261.png">

Augur: 0.15.2
OS: macOS 11.2.3

**Comment by gymgym1212** [comment]
Oh, maybe it's a problem with the Internet. When I got home and tried it again, it could keep going. But it stuck again as the image below and there are some errors.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/37684061/114038231-44c18300-98b4-11eb-85d4-4d75919418fa.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/37684061/114038140-31aeb300-98b4-11eb-8c48-dea0506af8ca.png">

<img width="572" alt="image" src="https://user-images.githubusercontent.com/37684061/114038043-1c398900-98b4-11eb-8692-1afb03f4ae6e.png">

In addition, I have repo folders right now but still no repo files.

**Comment by sgoggins** [comment]
`repo_group = 0` is a default for ALL repository groups.

**Comment by gymgym1212** [comment]
> `repo_group = 0` is a default for ALL repository groups.

Thanks :)
