### ISSUE TITLE
Got empty pull_request_message_ref table

### ISSUE THREAD

**Issue by gymgym1212** [chaoss/augur#1228]
**Description:**
I want to  collect data and create a PR analysis report using augur-community-repots. But I get error in `pull_request_analysis_template.ipynb` and find that there is no data in pull_request_message_ref table.

**How to reproduce:**
1. install augur
2. add repo groups and repo
3. use default config file
4. start augur backend
5. There is no data in pull_request_message_ref table

**Expected behavior:**
I want to collect the pull_request_message_ref data and create a PR analysis report as my GSoC microtask.

**Screenshots**
<img width="918" alt="image" src="https://user-images.githubusercontent.com/37684061/114302179-7c217100-9afa-11eb-8a22-187bab55f46a.png">

**Software versions:**
 - Augur: 0.15.2
 - OS: centOS 8 (also in macOS )
 - PostgreSQL: 10

**Comment by gymgym1212** [comment]
In the source code, I saw that pull_request_worker is responsible for collecting GitHub data of pull_request_message_ref table, so I turned on its switch separately and ran it, but there was still no data.

**Comment by sgoggins** [comment]
@gymgym1212 : I recognize your icon from class. I have a problem with that server right now and provided a second alternative.  I will share it with you in slack, but its also in the assignment notes.

**Comment by gymgym1212** [comment]
@sgoggins Hi, Mr. Goggins! Did you mis-recognize my GitHub icon as your student's? I am a graduate student at East China Normal University, applying for GSoC. I want to do some work about risk prediction idea and I will upload my proposal and submit a PR to the GSoC-interest page soon.

**Comment by sgoggins** [comment]
Yes. I'm sorry!  I hope you got your proposal in!

**Comment by sgoggins** [comment]
If you just installed augur, then that table is probably not populated. I'll make a point of adding a populated test data set for download and put it into the repo soon.
