### ISSUE TITLE
Repo listing not working on dev

### ISSUE THREAD

**Issue by jsaied99** [chaoss/augur#1229]
when running dev under my branch I get this error:
**Description:**
Uncaught (in promise) Error: Navigation cancelled from "/" to "/group/Default%20Repo%20Group/overview" with a new navigation.
    at He (vue-router.esm.js:2065)
    at qe (vue-router.esm.js:2047)
    at p (vue-router.esm.js:2354)
    at r (vue-router.esm.js:2004)
    at r (vue-router.esm.js:2008)
    at r (vue-router.esm.js:2008)
    at vue-router.esm.js:2005
    at vue-router.esm.js:2379
    at Augur.ts:153
    at <anonymous>

**Comment by sgoggins** [comment]
Hi @jsaied99 : We are aware of this issue. Would you be willing to build us a patch?

**Comment by Yogita98** [comment]
Hey hi @sgoggins 
If this issue is still actionable then I'd be willing to give it a shot. Maybe if you can share any pointers on how do I repro the issue then it'd be great.

**Comment by sgoggins** [comment]
fixed
