### ISSUE TITLE
APIs endpoints are not working

### ISSUE THREAD

**Issue by KShivendu** [chaoss/augur#1248]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
I am trying out the API endpoints described in https://oss-augur.readthedocs.io/en/master/rest-api/api.html#tag/utility. But for some reason, none of them are working and I'm just getting status as 500 every time. Am I doing something wrong here? Or are the APIs really that unstable as right now?

**How to reproduce:**
1. Choose any of the endpoints from https://oss-augur.readthedocs.io/en/master/rest-api/api.html#tag/utility. I'm picking the 2nd one "Repo groups"
2. Click the rectangular region above "RESPONSE SAMPLES" which will be in the format `GET <ENDPOINT>`. In my case, it's `GET /repo-groups`
3. Copy the server URL displayed to you. In my case, it's `http://augur.osshealth.io/api/unstable/repo-groups`
4. Visit the URL(Since it's a get request). 
5. You'll find the status to be 500 in all the cases and you'll be redirected to http://augur.osshealth.io/errors

**Expected behavior:**
The endpoints should have responded with 200 in the format described in the `RESPONSE SAMPLES` section 

**Software versions:**
 - OS: Ubuntu 
 - Browser: Chrome

**Comment by ABrain7710** [comment]
All the endpoints should be up and working again
