### ISSUE TITLE
Use https in the website

### ISSUE THREAD

**Issue by KShivendu** [chaoss/augur#1250]
**Description:**
Hi, I tried using `https://augur.osshealth.io/any/valid/path` but the browser says that the site can't be reached. 
Also, I discovered that the APIs are exposed at `http://augur.osshealth.io:5055/` which kind of looks odd because of the `5055` port. Maybe using `api.augur.osshealth.io` or  `augur-api.osshealth.io` will be better.

I think that the maintainers might be aware of this but I'm creating this as an issue so that it catches someone's attention and gets fixed sooner :)

**Software versions:**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by sgoggins** [comment]
I @KShivendu : If you have wrapped Flask in HTTPS before, we welcome any assistance you can provide the project. We ARE aware, and THANK you for opening this issue!!!

**Comment by KShivendu** [comment]
Hey @sgoggins, I'm sorry if you felt that my comment was rude. I had no such intentions, I like the augur project and I just wanted to help :)

**Comment by sgoggins** [comment]
@KShivendu : I agree with you that https will be better.

**Comment by Yogita98** [comment]
Can we use something like [talisman](https://github.com/GoogleCloudPlatform/flask-talisman) to wrap the flask app?

**Comment by sgoggins** [comment]
This issue is resolved in testing. New augur installations now have SSL configuration parameters generated. Documentation updates and release are forthcoming.

**Comment by harryhritik12** [comment]
hey , I would like to work on this project
