### ISSUE TITLE
worker unable to connect to broker

### ISSUE THREAD

**Issue by sta97** [chaoss/augur#1253]
I am attempting to add my own worker and I get "could not connect to broker" messages when attempting to start it.
I am not sure how to provide more information because I don't get more information from the log.
I have this issue both when starting the worker with "x_worker_start" and enabling the worker to start with augur in the config.

**Comment by sgoggins** [comment]
I think you have uncovered a gap in our documentation. There are two places you need to add sections to the `augur.config.json` file in your Augur Root directory (assuming you have completed the `make install-dev` command, which generates that file. If you used `make install`, then it will be in your $HOME/.augur/augur.config.json directory. 

In the house keeper block, you need to add something following this pattern: 
```
    "Housekeeper": {
        "update_redirects": {
            "switch": 0,
            "repo_group_id": 0
        },
        "jobs": [
            {
                "delay": 150000,
                "given": [
                    "github_url"
                ],
                "model": "contributor_breadth",
                "repo_group_id": 0
            },
            {
                "all_focused": 1,
                "delay": 150000,
                "given": [
                    "github_url"
                ],
                "model": "issues",
                "repo_group_id": 0
            },
            {
                "delay": 150000,
                "given": [
                    "<given specified in your worker>"
                ],
                "model": "<model specified in your worker>",
                "repo_group_id": 0
            },
```

In the Worker block you need to add something like this: 
```
    "Workers": {
        "contributor_breadth_worker": {
            "port": 48234,
            "switch": 0,
            "workers": 1
        },
        "facade_worker": {
            "port": 48868,
            "repo_directory": "/Volumes/repo_two/repos/augur-prwrt/",
            "switch": 1,
            "workers": 1
        },
        "facade_worker": {
            "port": <some port not otherwise in use>,
            "switch": 1,
            "workers": 1
        },
```

There should NOT be a comma after the final entry in each block. 

ALSO, if you wanted to have those blocks installed with auger itself when you do the PR, you need to add them to the `$AUGUR_ROOT/augur/config.py` file. The recommended way is to set a port range not already in use and assign a random variable range with the others, like this `your_new_worker_p = randint(56500, 56999)` ... its totally ok to compress a couple other port ranges for this process.

You can copy the housekeeper block verbatim from what you added to your own `augur.config.json`. For the worker block, in the `config.py` it would look like this: 

```
                "your_worker": {
                    "port": your_worker_p ,
                    "switch": 1,
                    "workers": 1
                },
```

The `switch` variable tells Augur to run your worker. The `worker` variable tells Augur how many to run. We recommend you begin with the number `1`.

Let us know if that works.  I will add this to the documentation.

**Comment by sgoggins** [comment]
@ABrain7710 : Can you see if you can get this worker to "run".  I have it connecting to the broker on the branch we built yesterday, but I have *no* idea why its not picking up jobs.  .... Maybe check that all the necessary operations_tables are included and spelled correctly?

**Comment by sgoggins** [comment]
I fixed this for you in the latest version of `dev` and `test`, @sta97 .. you were missing the Housekeeper block.
