### ISSUE TITLE
Analytical Notebook Creation

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1321]
Examine the Augur Schema, and request access to a populated sample. Develop Jupyter Notebooks that help to answer questions about open source health and sustainability, value, DEI, and/or risk across multiple repositories. This one is open to your imagination. You can find many examples at https://github/chaoss/augur-community-reports

**Comment by NoemiNahomy** [comment]
The link doesn't work : https://github/chaoss/augur-community-reports
