### ISSUE TITLE
Update Workers and Schema to Include issue_id/review_id/pr_id in bridge tables AND platform message ID in message table

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1324]
All of the data is presently available in base tables for issues, pull/merge requests, and pull/merge reviews. Its "relationally perfect".  HOWEVER, it does make it harder for newcomers to implement queries on messages if the issue_id, and repo_id are not included in the message table. Or, at least the bridge entities. 

This is a complex issue and we would work closely with anyone interested on it. 

![image](https://user-images.githubusercontent.com/379847/124800892-ca88b500-df1b-11eb-8c25-ddd9e5f2d4a7.png)

**Comment by Yogita98** [comment]
Hey @sgoggins 
If this issue is up for grabs, I'm interested to give it a shot

**Comment by sgoggins** [comment]
I fixed this one!
