### ISSUE TITLE
Time Series Analysis of contributor_repo table

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1326]
The contributor_repo table enumerates contributions that contributors in an Augur instance make across open source. Understanding level, diversity, and temporal cycles of contributions across open source would be helpful to many open source developers seeking new projects. Or fun.

**Comment by unnati914** [comment]
I want to work on this

**Comment by sgoggins** [comment]
@unnati914 : Go for it!

**Comment by unnati914** [comment]
thank you

**Comment by thegeekymuggle** [comment]
Hi, I would love to work on this issue. How do I get started?

**Comment by PurnaChandraMansingh** [comment]
Hi @sgoggins, could you please guide how to solve this issue
