### ISSUE TITLE
Add Vagrantfile

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#133]
This makes local development easier.

**Comment by jdbohrman** [comment]
I can help with this!

**Comment by ccarterlandis** [comment]
@howderek is there anything else we need to do for this?

**Comment by ccarterlandis** [comment]
Bump ^ @howderek

**Comment by howderek** [comment]
Hello @jdbohrman I apologize for the late reply - we have been working hard on getting things ready for a release.

I am totally open when it comes to what the Vagrantfile looks like, but ideally a user would be able to "vagrant up" and have a functional version of Augur except for the data sources that require API Keys, like GitHub. I think the hard part of this will be creating a test dataset from GHTorrent and a Facade database. Let us know if that is something you are interested in, and we can get you access to our database. I would also be happy to accept a pull request that just gives a running version of Augur without any of the data sources working.

Thanks so much for your willingness to contribute, and let us know if there is anything we can do to help!

**Comment by ccarterlandis** [comment]
Vagrant integration released in [v0.9.0](https://github.com/chaoss/augur/releases/tag/0.9.0).
