### ISSUE TITLE
UI deployment docs are unclear, please help?

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1338]
Deployment of the Augur Frontend without using a container [is undocumented](https://oss-augur.readthedocs.io/en/master/getting-started/frontend.html) (there's a big "TODO" in the docs).  Deploying it [using a container](https://oss-augur.readthedocs.io/en/master/docker/docker-compose.html) is somewhat documented, in that it tells us to use the docker-compose script.

However, in the actual [docker-compose script](https://github.com/chaoss/augur/blob/master/docker-compose.yml), the whole "frontend" section is commented out.  Why?  Does deploying it in a container not currently work?

I'm trying to engineer packaging for Augur that's deployable on Kubernetes, so I don't want to spend a lot of time trying to reverse-engineer the docker deployment if it's known-broken.

**Comment by jberkus** [comment]
Tag @cdolfi

**Comment by sgoggins** [comment]
@jberkus : You are right. The docs are unclear for the frontend Docker container. I will get those docs updated, and the container updated this week. We are in the process of altering the frontend so its less labor intensive to maintain. @Ulincsys is working on a Twitter/BootStrap version, which is noted in another open issue. 

Our docs are constantly improving, but I'm not going to point you down the rabbit hole of look here; look there! Give us 24 hours to update them for you.

**Comment by sgoggins** [comment]
You *can* run the frontend against containers, but I think updating that container is a better first attempt while we finish our longer term goal.

**Comment by unnati914** [comment]
could i work on this?

**Comment by sgoggins** [comment]
@unnati914 : I would welcome the help. I'm working on it now, but would definitely welcome the help.

**Comment by jberkus** [comment]
You can also throw notes somewhere public and I can try to follow them.  I just don't know the first thing about how the UI is suppsoed to be deployed, so I have nowhere to start.

**Comment by sgoggins** [comment]
There's a release coming this week that will make this clearer.
