### ISSUE TITLE
add_repos CLI does not populate path, name

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1348]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**

Using `augur db add-repos` provides no way to populate the "name" or "path" fields in repo records

**How to reproduce:**
1. Create a new Augur database
2. Add some repos using `augur db add-repos`
3. Repos added will appear like this in the database:

repo_id                      | 25431
repo_group_id                | 101
repo_git                     | https://github.com/konveyor/pelorus.git
repo_path                    | NULL
repo_name                    | NULL
repo_added                   | 2021-07-13 19:52:55
repo_status                  | New
repo_type                    | 

Whereas the sample repo looks like this:

repo_id                      | 1
repo_group_id                | 1
repo_git                     | https://github.com/chaoss/augur.git
repo_path                    | github.com/chaoss/
repo_name                    | augur
repo_added                   | 2019-05-31 14:28:44
repo_status                  | New

**Expected behavior:**

Either add_repos should provide columns to populate the name and path fields, OR those should get auto-populated by the workers using the GH API (which would be the better approach).

**Software versions:**
 - Augur:  0.16.2
 - OS: Built using provided Dockerfile from this repo

**Comment by sgoggins** [comment]
The sample repo should actually be changed to be NULL. The way the facade (commits) worker works is that it fills in everything based on the cloned directory, and processing of the git log. So, we should change the sample data accordingly. We want name and path to be NULL on load, and the status to be `New`. That's how facade knows to clone it, instead of doing a pull.
