### ISSUE TITLE
Adding Contributors Section & Open Source Programs in ReadMe

### ISSUE THREAD

**Issue by achalesh27022003** [chaoss/augur#1358]
I would suggest that there should be a token of appreciation for all the contributors out there to this repository. Therefore, we can add a contributor's section in the documentation i.e. readme below. We can also add tech stacks used & open source programs where this project was in participation.

If permits, I would like to take on this issue under Open Source Day'21.

**Comment by sgoggins** [comment]
ok.  Go for it @achalesh27022003

**Comment by achalesh27022003** [comment]
Thank you sir. Will do and update today itself.

**Comment by achalesh27022003** [comment]
Please review #1376  under OSD'21 sir.  Thanks.
