### ISSUE TITLE
Why does the schema use VARCHAR(255)?

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1367]
Is there any particular reason for using VARCHAR(255) and VARCHAR(4000) in the schema?  As far as Postgres is concerned, these are both just TEXT, and if we need to someday change the length limits on them it's an annoying migration.

Not really a bug, just a weird choice.

**Comment by sgoggins** [comment]
Agreed. It wasn't a choice so much as Augur starting before Postgres enabled straight up definition of a varchar without limits. I should fix this, and will.

**Comment by sgoggins** [comment]
This is the kind of thing an aging Oracle DBA turned OSS officiando might do. (hangs head in shame).

**Comment by jberkus** [comment]
Er ... Postgres has had unlimited VARCHAR since 1999.

Anyway, my suggestion would be to keep length limits on things that have actual length limits (like a repo name), and do the rest as unlimited.

**Comment by jberkus** [comment]
BTW, this isn't all tables.  Some of them use varchar-no-limit.

**Comment by sgoggins** [comment]
FIRST: Make sure that the varchar(4000) columns become varchar.

**Comment by jberkus** [comment]
Reasoning for above:

Most of the VARCHAR(255) fields are for things we expect to be much shorter than 255 chars, and never really expect to exceed it (like a login name).  But, the VARCHAR(4000) fields are largely things that are not limited in length by the repo host, and as such might be longer than 4000chars already.
