### ISSUE TITLE
Open list of tables with no unique constraint

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1369]
Following #1368, I've been checking other tables to see if they have a unique constraint that would prevent them from receiving duplicates from the workers.  Here's my tracking list of the tables in the augur_data schema that do not have one, including whether I'm seeing duplicates in my database, and what constraint I would recommend. I will keep adding to this list as I work with the database.

|        table        |  duplicates? | recommended constraints |
| --------------------- | ---------- | ----------------------------------- |
| pull_requests | no | ( pr_url ) (repo_id, pr_src_number) |
| issues | no | (issue_url) (repo_id, gh_issue_number ) |
| pull_request_reviews | yes | (pr_review_node_id) (pr_review_html_url) (pull_request_id, cntrib_id, pr_review_submitted_at) | 
| issue_events | no | (node_id) (node_url) |
| issue_message_ref | yes | (issue_id, msg_id)
| messages | yes | (cntrb_id, msg_timestamp) but see below

**Comment by jberkus** [comment]
augur_data.messages is kind of a weird case.  It currently has three unique indexes, none of which are required to be unique:

```
    "REPOGROUPLISTER" UNIQUE CONSTRAINT, btree (msg_id, rgls_id)
    "messagegrouper" UNIQUE, btree (msg_id, rgls_id)
    "platformer" UNIQUE CONSTRAINT, btree (msg_id, pltfrm_id)
```

Thing is, msg_id is already unique, to those constraints are superflouous, and they add overhead to writes.  We should probably convert them all to regular indexes without a unique constraint.

**Comment by sgoggins** [comment]
We have addressed this partially and will continue.
