### ISSUE TITLE
Clones of a repository

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/augur#1373]
**Is your feature request related to a problem? If so, please describe the problem:**
How many copies of a repository are cloned over a period of time. 

**Potential solutions:**
GitHub API
https://docs.github.com/en/rest/reference/repos#get-repository-clones

**Additional context:**
Proposed CHAOSS metric:
https://docs.google.com/document/d/19dUCadvCciouHq6XHcnzqGjuVC3hoPGf41WqlbEFJyM/edit

**Comment by sgoggins** [comment]
I think this could be a lightweight new GitHub data gathering item to test the generalized GitHub code in our next major release.

**Comment by sgoggins** [comment]
@IsaacMilarky / @ABrain7710

**Comment by meetagrawal09** [comment]
#2098 closes this issue : )

**Comment by sgoggins** [comment]
This issue is close by #2098
