### ISSUE TITLE
Augurface Production Build Doesn't Work

### ISSUE THREAD

**Issue by sbrennan98** [chaoss/augur#1374]
**Description:**
In augurface, while ```npm run serve``` builds and serves a development server perfectly fine, running ```npm run build``` and serving the production site with ```serve dist/``` results in an error as it does not load the application.

**How to reproduce:**
1. Go to ```augur/augurface```
2. run ```npm run build```
3. run ```serve dist/```

**Expected behavior:**
The frontend would compile and load properly when the user serves the production build. 

**Screenshots**
![image](https://user-images.githubusercontent.com/947042/126830497-8824061c-6870-43c5-a66c-465fcb854f53.png)

**Software versions:**
 - Augur: 0.16.2
 - OS: Ubuntu 20.04 LTE
 - Browser: Mozilla Firefox

**Comment by sgoggins** [comment]
Fixed.
