### ISSUE TITLE
Augur container does not write

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1390]
**Description:**

For undiagnosed reasons, the Augur container defined in our dockerfile does not write to its own filesystem.  This results in at least two problems.

**How to reproduce:**

1. Build a container image using the dockerfile
2. Run that container image
3. Let augur run for a while
4. exec into the container image
5. There should be logs written in /augur/logs but there are none
6. There should be repos cloned to /augur/repos but there are none

At this time, it is not possible to tell whether this is an issue with the augur code, the container definition, or the runtime.

**Software versions:**
 - Augur: 0.17.0
 - OS: Fedora 35
 - Runtime: podman 3.1.0-dev

**Comment by haukesomm** [comment]
I can confirm this behavior as well:
- Augur: 0.17.0
- OS: Ubuntu 20.04
- Runtime: docker-ce 20.10.7

Thus, I don't think this is an issue with the runtime but I'm also fairly new to Docker.

**Comment by jberkus** [comment]
No, I've been going over the podman logs and settings, and trying various configs.  This is definitely an Augur bug, and not an issue with the container runtime or setup.

**Comment by sgoggins** [comment]
Our original Docker configuration used Gluster for persistent storage. I am working on figuring out what we have setup in our test environment that is different from what is deployed. @howderek or @IsaacMilarky may have a few insights. Our core team is focused on an optimization of contributor collection, aliasing, and management right now. I am getting advice and testing fixes right now. We have a high priority on this one.
