### ISSUE TITLE
Document log_analysis installation and monitoring

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1391]
These are notes from the work of @ivanayov , who built a logstash based centralized log monitor within Augur, under the `log_analysis` directory in Augur's root: 

Right now both logstash and elasticsearch are finicky based on the configuration, release, and other factors at the operating system level. Making this stable and easy to work with is a longer term goal. 

```
export LOGSTASH_PATH=/home/ivana/logstash-6.8.10/bin/logstash (edited) 
export ELASTIC_SEARCH_PATH=/usr/share/elasticsearch/bin/elasticsearch (edited) 
https://www.elastic.co/downloads/past-releases/logstash-6-8-10
https://artifacts.elastic.co/downloads/logstash/logstash-6.8.10.tar.gz
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.0-amd64.deb (edited) 
sudo apt install ./elasticsearch-7.0.0-amd64.deb (edited) 
https://kifarunix.com/install-elasticsearch-7-x-on-ubuntu-18-04-debian-9-8/
export ROOT_AUGUR_DIRECTORY=/home/ivana/augur
cd $ROOT_AUGUR_DIRECTORY/log_analysis/http
python http_server.py

http://localhost:8003
Augur virt env once you have the http server running:
export LOGSTASH_PATH=/home/ivana/logstash-6.8.10/bin/logstash
export ELASTIC_SEARCH_PATH=/usr/share/elasticsearch/bin/elasticsearch
export ROOT_AUGUR_DIRECTORY=/home/ivana/augur
augur backend start --logstash


Regarding elasticsearch it's all about permissions issues. You can try running the binary - $ELASTIC_SEARCH_PATH , without augur and will see all the specific permissions problems for your machine. Once it's running well, there shouldn't be a problem from augur. The issue was that elasticsearch was never started and logstash relies on it.
```

**Comment by ivanayov** [comment]
The 7+ versions of Logstash are having unresolved issues that affect our specific use-case. This is why we're using 6.8 instead. Migrating to the latest versions of both Logstash and ElasticSearch would require testing the functionality with them after a period of time.


The issue about elasticsearch permissions is ubuntu-specific and related to it's installation and configuration only, not related to the Augur functionality.
The installation is less problematic on MacOS.

**Comment by Preshh0** [comment]
How can i contribute to the documentation on this? @ivanayov and @sgoggins?
