### ISSUE TITLE
Need error handling on "average commits per visualization endpoint

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1400]
I think error indicates that there is insufficient data to build a visualization. 

in red text ```SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data```

I think a little picture of @jonahz5222 's Auggie character wearing different hats, say "oops. Sorry folks. We don't have enough comments to calculate that data right now. Maybe we need to schedule some sessions to improve communication"? instead of the red text would be engaging. 

http://augur.chaoss.io/api/unstable/pull_request_reports/average_comments_per_PR?repo_id=1

**Comment by sgoggins** [comment]
Same issue with this endpoint: http://augur.chaoss.io/api/unstable/pull_request_reports/mean_response_times_for_PR?repo_id=1

**Comment by sgoggins** [comment]
Same issue with this one: augur.chaoss.io/api/unstable/pull_request_reports/PR_time_to_first_response?repo_id=1

**Comment by sgoggins** [comment]
@ABrain7710 / @Ulincsys : Same with this one.: http://augur.chaoss.io/api/unstable/pull_request_reports/average_PR_events_for_closed_PRs?repo_id=1

**Comment by sgoggins** [comment]
This is all on the `dev` branch btw.

**Comment by prathamaror** [comment]
can i work on this issue i think I have a pretty good idea how to solve this issue

**Comment by ABrain7710** [comment]
This has been fixed, and those links now return a useful error to to the user
