### ISSUE TITLE
Reliability/Uptime: Workers should automatically recover from errors and resume operation.  

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1413]
Workers should log all failures in an auditable way.

**Comment by sgoggins** [comment]
Perhaps there should be a consolidation of the logs into a single log stream. Having logs in a hierarchy of folders makes it difficult to consolidate.

**Comment by jberkus** [comment]
I'd like to separate the log stream issue from the "workers failing and not logging anything" issue, because they're two separate issues.

Right now, with the current release, the workers are not collecting any data.  And they're also not logging any errors.  This is a chronic problem.

**Comment by jberkus** [comment]
So let me spell this out as a more general issue:

There are a lot of external issues which can cause the workers to be unable to collect data as expected.  Failed auth, file permissions, database permissions, bugs in the code.  

Right now, sometimes workers will resume collecting data after the blocker is resumed.  But sometimes they won't.  #1431 is a good example of "won't".  

Workers should automatically resume collecting data ... and backfill if necessary ... whenever the blocker to that data is removed, without additional troubleshooting steps or database edits being required, except maybe in the case of bugs in Augur that we can't automate correction of.
