### ISSUE TITLE
Facade workers should restart collecting commit data after error

### ISSUE THREAD

**Issue by jberkus** [chaoss/augur#1431]
The way it is now:

If collecting commit data fails due to a git checkout error (e.g. permissions error on the repo directory, missing git executable, etc.), the Repo nevertheless gets marked as "Update" and no attempt is made to ever check out the repo again.

The way it should be:

If a worker can't check out a git repo, or can't extract data from it, it should keep retrying until the situation is corrected.  THis way, the user can just fix the permissions error (or whatever) and data will fill in.

This may require an overhaul of how data collection status codes are treated.

This is a specific fix for issue #1413

**Comment by sgoggins** [comment]
@IsaacMilarky and @ABrain7710 : This is something we need to review at our meeting this week.

**Comment by prathamaror** [comment]
can i work on this issue

**Comment by jberkus** [comment]
Feel free!  I'd check out the follow-ups on this issue as well: #1413, as well as chat with folks on Augur slack.  The "won't resume collection" problem is actually tied to some pretty significant architectural issues, so you'll want to learn a lot about Augur to help fix it.  Glad to have your help!
