### ISSUE TITLE
Extend Augur to collect Github Traffic Metrics

### ISSUE THREAD

**Issue by oindrillac** [chaoss/augur#1468]
**Is your feature request related to a problem? If so, please describe the problem:**
For project https://github.com/aicoe-aiops/ocp-ci-analysis, we wish to use Augur to collect and analyze Github traffic related information.
Does Augur currently scrape Traffic information such as Referring sites and Views per page from Git repositories? 

**Potential solutions:**
Extend Augur to collect [Github traffic information](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-traffic-to-a-repository) using Github API.

**Additional context:**
related: https://github.com/aicoe-aiops/ocp-ci-analysis/issues/382

**Comment by sgoggins** [comment]
@oindrillac : We can add this, as theirs an endpoint for it. Let me know priority

**Comment by rohanreddych** [comment]
@sgoggins Can i work on this issue?

**Comment by sgoggins** [comment]
@rohanreddych : Yes!

**Comment by ayushtamra** [comment]
Hello @sgoggins 
I am also interested to work on this issue, can you provide some brief details about what is implemented for the traffic and what needs to be implemented, that would be a great help

**Comment by rohanreddych** [comment]
@sgoggins I was familiarizing myself with the code, should we create a new worker or modify and existing worker?

**Comment by tuhinmallick** [comment]
Is this issue still available then I would like to give it a try.
