### ISSUE TITLE
Database Query / API Questions

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1478]
Put questions related to schema queries, or user of the Augur API here. 

This issue is intended to be responsive to schema questions on an ongoing basis. Its a good place to ask us how to extract information to answer specific questions using Augur. Your questions, and our answers, will then be contributed back to Augur's documentation every two weeks. 

We at Augur Global have completed a more complete fleshing out and stabilizing of the Augur Schema. The images below fall along Six Axes: 
1. The Whole Thing
2. Commits
3. Pull Requests
4. Issues
5. Dependencies
6. Contributors

Some tables, like "repo" are repeated across most of them for ease of use. 

# Overview
![20211006-augur-0 21 0-release](https://user-images.githubusercontent.com/379847/136831841-382746d1-c0ac-4bcd-b4c4-8a8b4c6cb6b8.png)

# Dependencies
![20211011-dependencies-augur-schema-v0 21 1](https://user-images.githubusercontent.com/379847/136831857-f6b33e2e-74cc-4adb-94aa-00ebedd15b0f.png)

# Issues
![issus](https://user-images.githubusercontent.com/379847/139131112-965bef92-6e80-4b22-bd4d-72f8adc067d4.png)

# Pull Requests
![20211011-pull-requests-augur-schema-v0 21 1](https://user-images.githubusercontent.com/379847/136831900-5c35303a-e469-4747-b04b-1c3a9c827eda.png)

# Commits
![20211011-commits-augur-schema-v0 21 1](https://user-images.githubusercontent.com/379847/136831925-940b1955-8eb6-45e5-81e5-13379b494101.png)

# Contributors 
![20211011-contributors-augur-schema-v0 21 1](https://user-images.githubusercontent.com/379847/136831952-4d2874ad-1280-4e61-b6cb-e4d8c135bb06.png)

**Comment by cdolfi** [comment]
@sgoggins the commits view is actually the contributor one

**Comment by cdolfi** [comment]
@sgoggins This was partially open to reference to for the schema. Is there a better place now to look?
