### ISSUE TITLE
recorded issue message time is prior to creation of issue

### ISSUE THREAD

**Issue by isabelizimm** [chaoss/augur#1510]
**Description:**
The recorded time for a messages posted on an issue is often recorded at some point in time BEFORE the issue is even created.

**How to reproduce:**
1. See https://github.com/sandiego-rh/sandiego/blob/main/notebooks/performance/issues_performance.ipynb
2. or query `               SELECT
                    r.repo_name,
                    irm.issue_id,
                    irm.issue_msg_ref_id,
                    i.created_at,
                    m.msg_timestamp msg_time,
					m.msg_text comment_text
                FROM
                	repo r,
                    issues i,
                    issue_message_ref irm, 
                    message m 
                WHERE
                	m.msg_id = irm.msg_id AND
                    irm.issue_id = i.issue_id AND
                	i.repo_id = r.repo_id AND
                    r.repo_id = \'{repo_id}\'`

**Expected behavior:**
I would expect `msg_time` to be AFTER the time the issue was created `created_at`

**Screenshots**
<img width="625" alt="Screen Shot 2021-11-01 at 11 04 27 AM" src="https://user-images.githubusercontent.com/54685329/139693429-b782352f-1279-4162-8b1b-ec0fddc09698.png">

**Software versions:**
 - Augur: using [Sandiego](https://github.com/sandiego-rh/sandiego) project

**Comment by cdolfi** [comment]
@sgoggins Any thoughts on this?

**Comment by sgoggins** [comment]
@isabelizimm : I am looking into this during this week.

**Comment by sgoggins** [comment]
@isabelizimm : I think we are getting a cartesian product. I am working on getting access to the old augur database to test your query. On another database I don't see the issue when I make this small change: 
```
SELECT
	r.repo_name,
	irm.issue_id,
	irm.issue_msg_ref_id,
	i.created_at,
	M.msg_timestamp msg_time,
	M.msg_text comment_text 
FROM
	repo r,
	issues i,
	issue_message_ref irm,
	message M 
WHERE
	M.msg_id = irm.msg_id 
	AND irm.issue_id = i.issue_id 
	AND i.repo_id = r.repo_id 
	and i.repo_id = m.repo_id
	AND r.repo_id = 36113
```

its the `and i.repo_id = m.repo_id` line that I added to what you had... and I'm not sure that exists in the schema of the augur database, but I can't access it right now.  There is a database on that server called sandiego that I can access.
