### ISSUE TITLE
Issues matching commit authors with their entries in the contributors table due to missing data

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/augur#1525]
**Is your feature request related to a problem? If so, please describe the problem:**
The authors of commits from GitHub can't currently be matched with their entries in the contributors table because the data required to match it is missing.
* The commits table does not include GitHub login (should populated in cmt_author_platform_username?), so these can't be matched to people in the contributors table by login, and for people in contributors with missing email addresses, they can't be mapped by email address either.
* In the contributors table, email addresses for some commit authors are missing, so these can't be matched to the email address in the commits table.

**Potential solutions:**
The GH API commit data does have the GH login details (see link below), so it should be possible to get the GH login details to populate cmt_author_platform_username in the commits table to allow for matching:
https://api.github.com/repos/goharbor/harbor/commits/ff50e2363dc7cbbe1d137bb3fb5a344f8c327680

It should also be possible to populate missing information (email, name, etc.) from the GitHub commit data by adding email addresses and other details from authors of commits to the contributors table.

**Caveat:**
We are just rebuilding my database with a new version of Augur, and it's possible that this issue is specific to my environment. There may be a worker to populate this info that just hasn't been run on my db yet.

**Additional context:**
@sgoggins can get additional information from the "Investigation" section of my dawn_contrib_risk Jupyter Notebook (which is private and not available publicly, but Sean has access). 

Sean - this is why my query that uses "cntrb_canonical" to match contributor info with commits is failing to get this data more than 50% of the time.

I know it's the Thanksgiving weekend, so please ignore this until Monday :)

**Comment by geekygirldawn** [comment]
I wanted to let you know that I've written my own workaround for this that allows me to get my contributor metrics. It's a hack and not a permanent solution, but it lets me run my monthly metrics, so this isn't particularly urgent. 

Have a great Thanksgiving!

**Comment by claracscl** [comment]
@geekygirldawn : Right now this is a function of a large collection of repositories run for the first time, and possibly a byproduct of my decision to seed contributors in your new augur instance from the old one. The big hang up right now is how long affiliation updates are taking. This is one thing I am working on optimizing for large datasets.

**Comment by sgoggins** [comment]
@geekygirldawn : That was me under a different account ^

**Comment by sgoggins** [comment]
The technical piece of what's happening is: 
1. Platform API's generally do not return the email
2. Commits include an email
3. We resolve the email to the platform user at the end of the commit process, which is, as I mentioned above, taking a really long time on a large collection right now. I am working with @IsaacMilarky on this issue.

**Comment by sgoggins** [comment]
I am now confident this is completely rectified.

**Comment by geekygirldawn** [comment]
I'm not so sure it's actually fixed (or possibly just not fixed on my instance)?

Here's an example:

Query for someone who is in the contributors table, but their email address was never populated.
`person_query = f"""
SELECT
   *
FROM
   contributors
WHERE
   cntrb_login = 'danfengliu';
    """`

`person_info = pd.read_sql_query(person_query, con=engine)
print(person_info)`

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1304299/155683305-8e189f6b-e750-46dc-9b19-3f9cc5803583.png">

Query showing that we have this person's details within the commits table, but they are never being added to the contributor's table:

`commit_query = f"""
SELECT
   *
FROM
   commits
WHERE
   cmt_commit_hash = 'ff50e2363dc7cbbe1d137bb3fb5a344f8c327680';
    """`

`commit_info = pd.read_sql_query(commit_query, con=engine)
print(commit_info)`

<img width="735" alt="image" src="https://user-images.githubusercontent.com/1304299/155683146-052bd507-0435-4917-b47b-8b0b0bf93f15.png">

**Comment by sgoggins** [comment]
@geekygirldawn  : I think this may be a documentation problem, where we do not explain clearly enough that duplicate contributors are mapped to contributor_aliases in the `contributors_aliases` table. In this case: 

```
select * from contributors_aliases where alias_email like '%dan%vmware.com%';
```

```
15252	401146	danfengl@vmware.com	danfengl@vmware.com	1	2022-02-14 02:33:35	'Facade Worker'	'1.0.1'	'Git Log'	2022-02-14 02:33:35
```

**Comment by sgoggins** [comment]
@geekygirldawn : How do you think we stand on this issue with the new version of Augur?

**Comment by geekygirldawn** [comment]
This is so old that I'm not sure, but I think so. :)
