### ISSUE TITLE
Move markdown docs to .rst

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#159]
This will help us produce more complete and descriptive apI documentation locally when Augur is deployed and built.

**Comment by sgoggins** [comment]
@howderek and @ccarterlandis : Status?

**Comment by ccarterlandis** [comment]
Completed in `dev` [this](https://github.com/chaoss/augur/commit/3aa72adeed85d5a8c3e172349a577257e64f0c51) commit.
