### ISSUE TITLE
Missing link 

### ISSUE THREAD

**Issue by kaxada** [chaoss/augur#1612]
**Description:**
Expected a link but there is none 

**How to reproduce:**
1. Go to  [this link](https://oss-augur.readthedocs.io/en/main/#:~:text=There%20are%20many%20more%20useful%20metrics%2C%20and%20you%20can%20find%20a%20full%20list%20of%20them%20here.)

**Expected behavior:**
There should be a link to the metrics

**Screenshots**
![image](https://user-images.githubusercontent.com/54111299/152760444-c46a52cf-0062-4c2e-9f18-71f9c1585051.png)

**Comment by kaxada** [comment]
If sure there should be a link here, I'd be glad to be assigned this issue as my first contribution to Augur!

**Comment by Preshh0** [comment]
@kaxada, did you find a list? @ElizabethN and @sgoggins these metrics for augur, is it the same as the ones listed [here?](https://chaoss.community/metrics/)

**Comment by ElizabethN** [comment]
This is the right link to use, thanks @Preshh0 ! If you see any other terms you can link to feel free to do so 😍

**Comment by Preshh0** [comment]
![chaoss](https://user-images.githubusercontent.com/42142405/174485299-9ee7c9b2-120c-44c1-8a9b-5e86ea63f5b5.PNG)
Hi, @ElizabethN where exactly is the augur instance for CHAOSS referenced? That one might need a link too. I can't seem to find it on the website.

**Comment by ElizabethN** [comment]
> Hi, @ElizabethN where exactly is the augur instance for CHAOSS referenced? That one might need a link too. I can't seem to find it on the website.

Hmm, great question @Preshh0! I don't think it's active for some reason. Let's link to the list of other live examples instead: https://www.augurlabs.io/live-examples/. 

Hope that helps!
