### ISSUE TITLE
Missing command

### ISSUE THREAD

**Issue by kaxada** [chaoss/augur#1613]
**Description:**
The installation guide to run augur locally is missing a particular word. expected `sudo apt **install** make` but there is `sudo apt make`

**How to reproduce:**
1. Go to [this link](https://oss-augur.readthedocs.io/en/main/quick-start.html#:~:text=git%0Acd%20augur/-,sudo%20apt%20make,-sudo%20add%2Dapt) 

**Screenshots**
![image](https://user-images.githubusercontent.com/54111299/152767551-900ceb30-a637-4b3b-a5b9-b98fff42dff3.png)

**Comment by kaxada** [comment]
Would also be happy to be assigned and fix this error 😇

**Comment by sgoggins** [comment]
@kaxada : It would be great if you could fork Augur and PR that fix in.

**Comment by kaxada** [comment]
Sure. Let me fix this
