### ISSUE TITLE
Support for python 3.9 in the project

### ISSUE THREAD

**Issue by kaxada** [chaoss/augur#1619]
Recently I  [having an error](https://gist.github.com/kaxada/5c264be3fcd48924e0dabdb4a1734adb)  with installing augur locally which I thought were attributed to me using python 3.9 but later confirmed it was my internet issue and got resolved. 

I later found out that the installation docs caution against not supporting python 3.9 because it is not supported by tensorflow as per now but the last time [I checked via their system requirements as of end of last year ](https://www.tensorflow.org/install/pip#:~:text=System%20requirements,-Python%203.7%E2%80%933.9&text=Python%203.9%20support%20requires%20TensorFlow,requires%20TensorFlow%202.2%20or%20later.)I saw like it is now supported. Is there anyupgrade that could be made so that we can have the project support python

@sgoggins I can't tell whether I have explained this the best way possible

**Comment by sgoggins** [comment]
@kaxada : Augur does now work with Python 3.9.

**Comment by kaxada** [comment]
> @kaxada : Augur does now work with Python 3.9.

And that is why I was of a suggestion we make the necessary upgrades since TensorFlow is supported.
