### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by davidak** [chaoss/augur#1625]
**Description:**
I want to _see_ what this project is.

I was searching for examples and there are some, but they are all broken.

https://www.augurlabs.io/live-examples/

In fact the whole domain is abandoned: http://osshealth.io/

Can you add a screenshot to the first section "What is Augur?" so people can find an answer to the question without reading.

**How to reproduce:**
1. Go to project
2. Click on links
3. Scroll down to examples
4. Find no working examples

**Expected behavior:**
Have working examples or at least a screenshot to have something to look at.

A picture says more than a thousand words.

**Comment by purna135** [comment]
I would like to work on this.
