### ISSUE TITLE
"augur command not found" and "brunch command not found"

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#165]
after a fresh install on an Amazon AMI instance (Linux), neither the augur command or the brunch commands work on 
``` 
make dev
```
or 
``` 
make dev-start
```

**Comment by ccarterlandis** [comment]
Does running `sudo make install-dev` allow `make dev` and/or `make dev-start` to work?

**Comment by sgoggins** [comment]
There does seem to be some glitchyness with a fresh install on Ubuntu.

**Comment by Nebrethar** [comment]
Normally I have to run two commands:

`make dev-install-admin`
This is to install files.

`sudo make install-dev`
It seems like all the second does is install augur 0.7.x itself.

The command "make dev" starts augur when called after these two commands
Changing all Makefile "pip" commands to "pip3" does not fix, but it is required for installation on Ubuntu 16.04 and 18.04
