### ISSUE TITLE
Populate "Repo_Type" in Repo Table with "organization" or "person"

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#1650]
**Is your feature request related to a problem? If so, please describe the problem:**
If a repository is under an organization, make the "repo_type" "organization".  If a "person", make the "repo_type" a person". 

**Potential solutions:**
In short, if this API call returns nothing, then its a person: 

https://docs.github.com/en/rest/reference/orgs#get-an-organization

**Comment by ritikBhandari** [comment]
Hi @sgoggins!
I would love to work on this or have further discussions if needed. Let me know if the issue is still relevant.
