### ISSUE TITLE
Documentation Inclusivity: clarify MacOS setup 

### ISSUE THREAD

**Issue by diananova** [chaoss/augur#1665]
In the [installation page](https://oss-augur.readthedocs.io/en/main/getting-started/installation.html), it says: 
> If you’re running Augur on macOS, we strongly suggest adding the following line to your shell’s initialization script:
> `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`

As someone who only recently started developing on Mac, I was confused by what this meant and had to google it. I would clarify what the exact commands should be on the terminal. 

> If you’re running Augur on macOS, we strongly suggest updating your shell’s initialization script as follows.
>
> In a terminal, open the script:
> `nano .bash_profile`
> Add the following line to the end of the file:
> `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`
> Save the file and exit. 
> Run this command to reload bash_profile:
> `source .bash_profile`
> Check if it was updated:
> `env`
> env should contain OBJC_DISABLE_INITIALIZE_FORK_SAFETY

**Comment by Quickbeasts51429** [comment]
Hello, I am Soumya Jha. Can I take up this issue and work upon?
