### ISSUE TITLE
Getting Started List Numbering starts with 0 instead of 1

### ISSUE THREAD

**Issue by Florence-Njeri** [chaoss/augur#1667]
**Description:**
The [Getting Started](https://oss-augur.readthedocs.io/en/main/getting-started/toc.html) section has an ordered list that starts with the number 0 instead of 1 and I'd like to correct that as well as make the last paragraph more clear on what the reader will learn in the database section which is quite vague.

**How to reproduce:**
1. Navigate to [Getting Started](https://oss-augur.readthedocs.io/en/main/getting-started/toc.html) 
2. Look at the numbering on the ordered list.

**Expected behavior:**
An ordered list starts with 1 not 0.

**Screenshots**
<img width="1433" alt="Screenshot 2022-03-26 at 13 37 12" src="https://user-images.githubusercontent.com/40742916/160235830-3c269a57-0454-489a-80b0-6b36ec188283.png">

**Comment by Florence-Njeri** [comment]
@sgoggins I'd like to get started on this task

**Comment by manishsaini6421** [comment]
@sgoggins I am working on it.

**Comment by manishsaini6421** [comment]
@Florence-Njeri i have started working on this.

**Comment by Florence-Njeri** [comment]
@manishsaini6421 I'm currently waiting for approval to work on it as my Outreachy task.

**Comment by manishsaini6421** [comment]
@Florence-Njeri Ma'am i am an outreachy applicant and i have fixed this issue .can you review it please.

**Comment by manishsaini6421** [comment]
@Florence-Njeri I am also an outreachy applicant and i have fixed this issue, but me also waiting for approval.
