### ISSUE TITLE
Doc Inclusivity: confusing installation guide

### ISSUE THREAD

**Issue by diananova** [chaoss/augur#1688]
The installation guide for augur is a little confusing. I'll write these issues in first person from the point of view of a first time user.

> The index is confusing. When opening the documentation, I don't know where to start. 

We have 3 sections that sound similar: Quickstart, Getting Started, and Development Guide. And they all contain different information. It would be nice to have everything consolidated into one page, and then have references for additional setup. But the minimum steps required to get augur running should be found in one place. 
> I walked through all the steps and ran `augur backend start` and I don't know if it's working or not. What's the expected result?

We should clarify what a user should expect in case of a successful installation. The result should be that the database is populated with data collected by the workers, correct? 

> Ok, I populated the database. Now what?

As I understand, there are different ways to visualize this data. One of them is running the frontend, another way is through jupyter notebooks and by installing augur-community-reports. Maybe a screenshot of what the frontend looks like would be helpful, so users can decide if they need to set up the frontend part as well.

> I ran into an error. How do I fix it?

I think it would be beneficial to have a separate page for common issues and how to solve them. I already have some that are related to MacOS and I think would be useful for newcomers.  

I would love to start working on this, but I just wanted to first check if these issues make sense to you and if you think they are worth changing.

**Comment by Preshh0** [comment]
Hi @diananova, commenting on your suggestion on Quickstart, Getting Started and Development Guide; I think they can still be separate, they all serve different purposes, but they could be more detailed. For instance: The Quickstart is supposed to be that section that gets you up and running quickly, merging it with either of those other two sections might not be so beneficial. If you want, we could brainstorm/work together on making the documentation better.

**Comment by ayush-8** [comment]
@diananova You are right, The documentation takes into consideration that the user knows a bit before writing the commands. Also, it doesn't have valid outputs and the possible errors. I myself encountered many errors during the installation of augur. The conflict of python libraries such as tensorflow, and psql schemas not created automatically during the execution of Makefile were the prominent ones. The Solution is that we can together Modify the documentation, since I have installed it successfully.

**Comment by Preshh0** [comment]
Yes, we can do that. Do we ask that this issue be assigned to us? Also, should we move this conversation to slack? Or it's fine having it here?

**Comment by ayush-8** [comment]
We need to ask to assign us. It's fine to converse here than slack.

**Comment by Preshh0** [comment]
Okay, cool. We can't ask to be assigned the whole documentation, so I think we could start from the Quickstart. Is that fine?

**Comment by sgoggins** [comment]
Yes, this is a good idea!
