### ISSUE TITLE
Fix a typo on the Getting Started - Command Line Interface (database instruction)

### ISSUE THREAD

**Issue by Preshh0** [chaoss/augur#1689]
It's a typo.

Fix the typo on the Getting Started - Command Line Interface (database instruction)

![chaoss 3- augur db](https://user-images.githubusercontent.com/42142405/161342454-2c2932f2-8b04-41c4-a16b-e59d642b05c1.PNG)

Hi @sgoggins can I work on this?

**Comment by Redeem-Grimm-Satoshi** [comment]
Hi @Preshh0 can i work on this?

**Comment by Preshh0** [comment]
Oh, no. I posted it so I could ask permission to work on it. Let me edit it accordingly.

**Comment by Redeem-Grimm-Satoshi** [comment]
alright

**Comment by Redeem-Grimm-Satoshi** [comment]
alright

**Comment by diananova** [comment]
I think you can start working on it without asking permission, since it's a very small change.

**Comment by Preshh0** [comment]
Okay, cool.
