### ISSUE TITLE
Contribution to Documentation : Easy Navigation as a Newbie in the Community (Navigation/Community Guide)

### ISSUE THREAD

**Issue by Preshh0** [chaoss/augur#1696]
As a new member of this community, I have found navigating and figuring my way around the community hard.  For instance in the areas of knowing what issues to tackle, where to start from etcetera. 
In the documentation, I'd like to include a detailed navigation and/or a community guide page so people coming after would find it easy to navigate and contribute faster to the project. 

@sgoggins, i'd like to be assigned this issue.

**Comment by Preshh0** [comment]
HI @howderek, I'm about to make a pr for this issue but I am unsure which directory to place it in. I did see a community repo two days ago that sort of references this issue, but could still be better. Do I solve this issue in that repo, or just go ahead and place it in the "getting started" doc that i initially wanted it to be in?

**Comment by sgoggins** [comment]
Merged PR #1797
