### ISSUE TITLE
Separate installation guide for each OS

### ISSUE THREAD

**Issue by diananova** [chaoss/augur#1709]
The current documentation is mostly focused on Ubuntu. I think for beginners it would be useful to have separate installation guides for Ubuntu, Windows or MacOS. Thoughts?

**Comment by Deepthi562** [comment]
@diananova, that's a great idea. Can we work on this?

**Comment by Preshh0** [comment]
Hi @sgoggins, I think this should be taken into serious consideration. Especially on the quickstart guide. It'd be much better if users can know which direction to follow specific to OS and it'd also make the documentation more structured.  @diananova are you already working on it? I can take care of the Ubuntu guide.
