### ISSUE TITLE
Automatic Issue Creation API for GitHub

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#171]
This could serve us for getting feedback off of our test sites, but i would also like it implemented to support the "Global Consent Manager" project. https://www.npmjs.com/package/github-create-issue

Lets discuss.

**Comment by Sai-Adarsh** [comment]
@sgoggins I'm interested in contributing.

**Comment by ccarterlandis** [comment]
Hi @Sai-Adarsh! Please review our guidelines on [contributing](https://github.com/chaoss/augur/blob/master/CONTRIBUTING.md) and [installation](http://twitter.augurlabs.io/static/docs/dev-guide-toc.html) to get started, and please let us know if you have any questions!

**Comment by sgoggins** [comment]
I think this issue should be closed now. I don't think its an "augur thing".
