### ISSUE TITLE
Augur Component Software Docs 

### ISSUE THREAD

**Issue by Anubhavdevv** [chaoss/augur#1736]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
In the Chaoss Website under the section of software there is Augur documentation is provided in which under Augur Component section start here part when I click on the python library and the rest server documentation the link is redirecting to new page but there is no content it show that "This page Does not exist and 404 not found"

**How to reproduce:**
1. Go to [Chaoss Software](https://chaoss.community/software/)
2. Click on [Augur Dropdown](https://chaoss.community/software/#user-content-augur)
3. Scroll down to Augur Components and click on [Python Library](https://oss-augur.readthedocs.io/en/dev/library-documentation/python.html) and [rest server](http://augur.osshealth.io/static/api_docs/)

**Expected behavior:**
It should be redirect to the website docs but it is showing the error 404 it should open the docs link

**Screenshots**
![image](https://user-images.githubusercontent.com/72249059/163099945-c7923fce-0f11-435e-8c35-b4cc7df145a4.png)

![image](https://user-images.githubusercontent.com/72249059/163099968-d98a828a-e36a-42da-a67e-5b9a46363c4e.png)

**Comment by Anubhavdevv** [comment]
I would like to work on this if you could assign this issue to me 
Thank You !

**Comment by howderek** [comment]
Hello @Anubhavdevv, I assigned you the issue.

**Comment by Anubhavdevv** [comment]
Thank you @howderek for assigning this issue to me but as the chaoss community website is build on wordpress so how can I change the link of the website which will redirect to the correct one ?

**Comment by germonprez** [comment]
@sgoggins could you help out here?

**Comment by apriltotheg** [comment]
@Anubhavdevv : That is a website that needs to be updated.

**Comment by Anubhavdevv** [comment]
> @Anubhavdevv : That is a website that needs to be updated. 
Yup I know that need to be updated so if I want to contribute to that how can I do that?

**Comment by klumb** [comment]
CHAOSS website pages are populated by GitHub markdown pages. The page that needs to be updated is here: https://github.com/chaoss/website/blob/main/Software/augur.md

**Comment by Anubhavdevv** [comment]
ohk thank you
