### ISSUE TITLE
Create a more detailed installation guide in the Quickstart Section 

### ISSUE THREAD

**Issue by Preshh0** [chaoss/augur#1742]
**Is your feature request related to a problem? If so, please describe the problem:**

The current installation guide on the Quickstart part of the documentation is really complex to follow. Even as a ubuntu user.

**Potential solutions:**

I'd like to make it more detailed, include alternate methods of installation in case the current one there doesn't work and maybe also include pictures for better understanding too. 

**Additional context:**

For instance: 
The installation guide for PostgreSQL doesn't tell you you need to make sure your server is running before typing "psql", for people who are new to Postgres, finding solutions might be tricky as they don't exactly know how to apply the answer being seen on the internet.

The picture below buttresses my point:
![repo](https://user-images.githubusercontent.com/42142405/163332010-b8585b65-41d1-4f85-8284-a6f6c85b3cb3.PNG)

 @sgoggins, I'm working on this.

**Comment by howderek** [comment]
Hello @Preshh0 - I assigned you the issue. Thanks!

**Comment by Preshh0** [comment]
Thank you!
