### ISSUE TITLE
Confusing setup after install

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#176]
**Is your feature request related to a problem? Please describe.**

I just finished the docker install. It may have something to do with my experience, but I cannot figure out where to put information for the GHTorrent database that I have.

Here are a few things I've noticed:

- There is no README or instructions for use. The link "tutorial" for the README file is dead.
- Exploring files, I see an "augur.config.json" file but it is empty.
- I found another file, "_config.yml" under /docs, but it only has one line for "theme" and no explanation.
- The link for documentation on the main banner, "https://osshealth.github.io/augur/" is dead. I was able to replace "osshealth" with "chaoss" and it works.

**Describe the solution you'd like**

I would like to see some more explicit documentation on how to use augur.

edit: Front and and Back end development guides are fixed.

**Comment by howderek** [comment]
Hi @Nebrethar,

Thanks for letting us know about these issues! I apologize for the delay in our reply - we will make sure to improve our documentation soon. 

In the meantime, please note that `augur.config.json` is dynamically generated as Augur requests configuration. We will make sure that file has default contents in the future to make this less confusing. When you run augur, that file will be populated with the default values for all of the configurable data sources, including GHTorrent.

**Comment by ccarterlandis** [comment]
These specific issues have been resolved, but the overall experience could still be better. I'm going to close this issue and open another one where we can continue this discussion.
