### ISSUE TITLE
configparser not found

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#177]
**Describe the bug**
I've had an error while installing augur for development that may come in handy.
I have been getting the error "configparser not found". Augur was having trouble importing it.
I found in "application.py"

```
import configparser as configparser
```

Replacing it with this makes it work for me.
```
try:
    import configparser as configparser
except:
    from six.moves import configparser as configparser
```
https://pypi.org/project/six/

I'm not sure if the statement is needed or six can just be used in general.
I didnt want to open a PR because it might cause problems without six.

**To Reproduce**

Install on Ubuntu 18.04
Run `make install-dev-admin` (issue is after this point in the installation)
Run `augur`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop x64
 - Version 18.04

**Additional context**
![image](https://user-images.githubusercontent.com/34951354/45773856-1524cf80-bc11-11e8-9e2f-2fd9cb43d639.png)

**Comment by howderek** [comment]
Hello @Nebrethar,

Thank you for your bug report!

This issue is caused by attempting to run Augur with Python 2.x. Augur does not support Python 2.x. We will ensure that make install-dev-admin will only use Python 3 in the future, and also make sure that our docs make that more clear.
