### ISSUE TITLE
Adding duplicate compared repo on refresh

### ISSUE THREAD

**Issue by gabe-heim** [chaoss/augur#179]
If you have a compared repo and you hit refresh on a page, each compared repo duplicates itself in the compared repo array and  an extra "&comparedTo[]=owner+repo" will be added to the query string with the same repo.

**Comment by ccarterlandis** [comment]
Duplicate of [this](https://github.com/chaoss/augur/issues/186) issue. Closing this one, as the other one is in the proper format. Please use the other one linked above.
