### ISSUE TITLE
Augur Makefile commands should always use Python 3

### ISSUE THREAD

**Issue by howderek** [chaoss/augur#180]
Augur does not support Python 2. Commands in the Makefile still use Python 2 when Anaconda is not available and Python 2 is the default Python version on the users system. Makefile commands should fail when Python 3 is not available. 

Examples:
#174 
#177
#163

**Comment by sgoggins** [comment]
@ccarterlandis and @howderek : how are we doing on this one? I think its super important for newcomers.

**Comment by Nebrethar** [comment]
https://github.com/chaoss/augur/pull/196 fixes this issue on Ubuntu with a fresh install.

I'm not sure what pip3 would look like in other distros/os

**Comment by sgoggins** [comment]
The environment has evolved enough that I am going to close this issue now. For the most part we now know its a Python 3.x application and 2.7 does not work.
