### ISSUE TITLE
letting people know when to exit 

### ISSUE THREAD

**Issue by namgyalangmo** [chaoss/augur#1801]
after we complete the last step of PostgreSQL Installation[](https://oss-augur.readthedocs.io/en/main/quick-start.html#postgresql-installation) i.e "postgres=# GRANT ALL PRIVILEGES ON DATABASE augur TO augur;" 
we should let people who are new to the environment know that they should first exit the postgres by hitting ctrl+D  before moving to git configuration section.
![issue1](https://user-images.githubusercontent.com/75657887/164553646-8e4709e4-d030-40f7-845a-d8e0a6492404.jpeg)

**Comment by ayushtamra** [comment]
Yeah I totally agree with that, we should have an expansion of explanations in some documentation sections so as to make it clear for the newcomers, or we can just provide some references where these installations are clearly explained.
