### ISSUE TITLE
Specify Content Language

### ISSUE THREAD

**Issue by jonahz5222** [chaoss/augur#185]
**Is your feature request related to a problem? Please describe.**
To conform to web accessibility standards, we need to declare the content language of our page to allow screen readers to more easily access our page.

The problem is described more formally as such:  

>Developers should define the natural language of a document to ensure that screen readers and other user agents understand the language the document is to be interpreted in.  Specifically, when a document contains multiple inline language choices, screen readers and other assistive technology types must know what the default language type is to ensure they can appropriately switch between languages. 
Per the HTML 4.01 recommendation, language declarations should be made in accordance with IETF RFC 1766.

>Always declare the default language for text in the page using attributes on the html tag. 
><ul>
><li>Do NOT use the meta element with the content attribute set to Content-Language.</li> 
><li>Use language attributes rather than HTTP to declare the default language for 'text processing' (ie. >when language needs to be known for things such as font choice, styling, spell-checking, hyphentation, quote mark styling, etc.). </li>
><li>Do not declare the default language of a document in the body element, use the html element. 
><li>Where a document contains content aimed at speakers of more than one language, decide whether you want to declare one language in the html tag, or leave the languages undefined until later. ></li>
><li>Where a document contains content aimed at speakers of more than one language, try to divide the document linguistically at the highest possible level, and declare the appropriate language for each of those divisions. </li>
><li>For HTML use the lang attribute only, for XHTML 1.0 served as text/html use the lang and xml:lang attributes, and for XHTML served as XML use the xml:lang attribute only. </li>
></ul>

**Describe the solution you'd like**
Adding a lang tag to the <html> header i.e. `<html lang="en">`

**Additional context**
Source: https://webaccessibility.com/results using twitter.augurlabs.io

**Comment by sgoggins** [comment]
@jonahz5222 : What's the remaining "to do" here?

**Comment by sgoggins** [comment]
Closed per discussion with Jonah!
