### ISSUE TITLE
Make use of more inclusive text in the Augur documentation. 

### ISSUE THREAD

**Issue by Preshh0** [chaoss/augur#1857]
This feature deals with making the texts on the different pages of Augur more inclusive. 

I'm using [this tool ](https://www.witty.works/)

It works like Grammarly, but instead of correcting typos and/or sentence structure, it adjusts your text to involve more inclusive words.

**Comment by sgoggins** [comment]
@Preshh0 : Do we keep this open for reference as you do all the work, or close it?

**Comment by Preshh0** [comment]
I'm unsure. I've used the tool to go through Augur and have exhausted whatever corrections it had to make. But I'm thinking, what if I personally get more knowledge regarding the subject and decide to edit? What do you think? Close it for now, and maybe reopen if the topic ever comes up?

**Comment by sgoggins** [comment]
@Preshh0 : Lets bring this up at the next CHAOSS Community call.

**Comment by Preshh0** [comment]
Okay. The general one, or the DEI workgroup?
