### ISSUE TITLE
Duplicate Compared Repos are possible

### ISSUE THREAD

**Issue by jonahz5222** [chaoss/augur#186]
**Describe the bug**
When comparing repositories, it's possible to have two comparisons to the same repository, this seems like it is unintended behavior.

**To Reproduce**

1. Go to /?repo=rails+rails
2. Compare to another repo, i.e. `/?repo=rails+rails&comparedTo[]=jquery+jquery`
3. Compare to another repo, i.e. `/?repo=rails+rails&comparedTo[]=jquery+jquery&comparedTo[]=twitter+twemoji`
4. Compare again to the same repo, i.e. `/?repo=rails+rails&comparedTo[]=jquery+jquery&comparedTo[]=twitter+twemoji&comparedTo[]=jquery+jquery`
  
**Expected behavior**
Before adding a new comparison repo to the url, it should check to see if it's already being compared, and if so, not add it.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari

**Comment by sgoggins** [comment]
Status report?
