### ISSUE TITLE
Add the GSOC 2021+ contributors.

### ISSUE THREAD

**Issue by Preshh0** [chaoss/augur#1876]
GSOC contributors for 2021 and more recently aren't on the documentation. 

I'd like to get a list of them and add them up. 

For context: 
![augurIssue](https://user-images.githubusercontent.com/42142405/174460019-fe02da7d-13a4-4821-9a5f-183030e8aa10.PNG)

**Comment by sgoggins** [comment]
@skdbsp123 : can you address this issue? I can get you the names.

**Comment by skdbsp123** [comment]
@sgoggins sure!

**Comment by ajeurkar** [comment]
@sgoggins Can I address the issue?

**Comment by AdityaRaimec22** [comment]
Hi @sgoggins  can you assign me this issue. I will definitely get your work done
