### ISSUE TITLE
The image for issues schema is incorrect.

### ISSUE THREAD

**Issue by justinabrahms** [chaoss/augur#1885]
In these docs: https://oss-augur.readthedocs.io/en/main/schema/issues.html

You have an image of the pull request schema, not the issues schema. In the full graphic, the issues are present in their own bubbles.

**Comment by Preshh0** [comment]
@sgoggins, how would I do this? If I were to take it up.

**Comment by skdbsp123** [comment]
@sgoggins I can try. I need to know the tool used to create this image.

**Comment by sgoggins** [comment]
resolved by pull request #1910 

@skdbsp123 : SOrry. I assumed I just had the markup link wrong, but I actually did not have that image in the repository, so I had to fix it myself .. since my database design tool is kind of expensive. :)
