### ISSUE TITLE
Project Drop Downs not showing selected items

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#189]
**Describe the bug**
 - Its not clear that the drop downs contain information, though they do include a full list of the repositories in a project. 
 - when I select something it does not show up in the box.  ... I think it needs to display some kind of state

*Tertiary Design questions*
 - the selection behavior is also not entirely clear. Perhaps this confounds the confusion? 
 - only a question, but are drop downs the right design for a selection list that could include from 1 to 110 (or more) projects? 

**To Reproduce**
1. Go to an augur page on the dev branch and 
2. search for a respository
3. Select a second repository to compare it to. 

**Expected behavior**
I expect maybe it'll be a tad bit more intuitive. 

**Screenshots**
![issueaugur-dropdown](https://user-images.githubusercontent.com/379847/47746892-1a842980-dc55-11e8-850f-27aabbe61512.jpg)

**Desktop (please complete the following information):**
 - Mac OSX
 - Chrome
 - Running in Trump's America

**Smartphone (please complete the following information):**
 - nope.

**Additional context**
The Red Sox won the world series a couple nights ago.

**Comment by ccarterlandis** [comment]
I believe @tretrue has been working on a fix for this, although it's not public yet.

**Comment by sgoggins** [comment]
There is progress here ... now the version in dev doesn't respond to day changes ... or Z-Score changes .. the lists are working better, though a little "dodgy" ... ALso, if there's anything we can do to make the list of repos being compared a little easier to follow at the top ... maybe even a simple numbering scheme ... 1. .. 2... etc. 
![augur](https://user-images.githubusercontent.com/379847/48315883-7b8af600-e5a1-11e8-8fa4-de0828eebf44.jpg)

**Comment by sgoggins** [comment]
> I believe @tretrue has been working on a fix for this, although it's not public yet.

There is some progress.  My comment above is simply the state of what is checked in.

**Comment by sgoggins** [comment]
Hey @gabe-heim : My sense is we are solving this with the work stream you are on?

**Comment by gabe-heim** [comment]
Yes, I will make sure all is working flawlessly before we do a release.

**Comment by sgoggins** [comment]
Its not entirely on you .. :) 

…. 


Sean P. Goggins
Associate Professor, Computer Science
University of Missouri
http://www.seangoggins.net <http://www.seangoggins.net/>

visit: http://www.augurlabs.io <http://www.augurlabs.io/> (Research Lab) [Sloan Foundation, National Science Foundation]
visit:  <http://mhs.missouri.edu/>http://mhs.missouri.edu <http://mhs.missouri.edu/> (for mission hydro sci!) [i3 & IES]
visit: http://ocdx.io <http://ocdx.io/> (for the open collaboration data exchange!)   [National Science Foundation]
visit: http://www.sociotech.net <http://www.sociotech.net/>
visit: <http://chaoss.community/>  <http://chaoss.community/>http://c <http://c/>haoss.community (for open source health metrics) [Sloan Foundation]
visit: http://sociallycompute.io <http://sociallycompute.io/> (for code like things and Group Informatics) [National Science Foundation]
 
“Start with what is right rather than what is acceptable.”
—Franz Kafka
