### ISSUE TITLE
Display how users can extract data from Augur

### ISSUE THREAD

**Issue by Preshh0** [chaoss/augur#1900]
Users need to be able to extract data and understand what the data extracted is.

This issue is to work on displaying this information to the users.

This can be done by updating and properly explaining the functions and features of the items in the schema.

**Comment by sgoggins** [comment]
A lot of this will be documenting some of the queries we are working on!

**Comment by Preshh0** [comment]
Can i get access to the info on these queries? How do I get access to them?
