### ISSUE TITLE
Visualization of Top n Developers

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#191]
**Is your feature request related to a problem? Please describe.**
There is a use case where community managers want to see the top n coders.  The folks who contribute "most" of the code. So, instead of showing the top 10 developers, it would be useful to see "developers responsible for 50% of all code" or "developers responsible for 80% of all code" ... we could do this by commits and LOC seperately ... starting with commits. 

**Describe the solution you'd like**
I love this visualization.  If we had that visualization for the top n% of developers that is one possibility. 
![augur2](https://user-images.githubusercontent.com/379847/48316135-22bd5c80-e5a5-11e8-82c9-89934e7104d2.jpg)

I would like to get your thoughts on this, y'all. 

**Describe alternatives you've considered**
A simple pie chart or other visualization of how many developers are responsible for n% of the code in a period of time, and how many other developers there are.  *This could be an even better solution*, actually. 

**Additional context**

**Comment by gabe-heim** [comment]
I think the new viz's on the Git tab ("Lines of code added by the top 10 authors as Percentages - By Time Period", "Commits by the top 10 Authors as Percentages - All Time", and "Lines of Code Added by the top 10 Authors as Percentages - All Time") solve this use case.
