### ISSUE TITLE
Installation Minor issues

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#197]
**Describe the bug**
A few errors that don't seem to stop us, but I think we should update the install docs and continue doing what we can to streamline. I think @howderek 's plan to take "make" out of the mix will eliminate some of the minor, non-blocking issues I noted. 

**To Reproduce**
1. Follow installation instructions in dev branch. 

**Expected behavior**
Make it easier for developers that are new to the project. 

**Screenshots**
see attachment 

**Desktop (please complete the following information):**
 - n/a

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
n/a

[AugurInstallLog-December-5-2018.pdf](https://github.com/chaoss/augur/files/2647437/AugurInstallLog-December-5-2018.pdf)

**Comment by sgoggins** [comment]
Another issue with "make dev start"

make dev start

Server     Description       Log                   Monitoring                   PID                        
------------------------------------------------------------------------------------------                 
Frontend   Brunch            logs/frontend.log     make monitor-backend         13143 
Backend    Augur/Gunicorn    logs/backend.log      make monitor-frontend        13114 

Monitor both:  make monitor  
Restart and monitor: make dev
Restart servers:  make dev-start 
Stop servers:  make dev-stop 

**==> logs/frontend.log <==
bash: brunch: command not found**

==> logs/backend.log <==
[2018-12-05 15:29:21 +0900] [13131] [INFO] Booting worker with pid: 13131
[2018-12-05 15:29:21 +0900] [13132] [INFO] Booting worker with pid: 13132
[2018-12-05 15:29:21 +0900] [13133] [INFO] Booting worker with pid: 13133
[2018-12-05 15:29:21 +0900] [13134] [INFO] Booting worker with pid: 13134
[2018-12-05 15:29:21 +0900] [13135] [INFO] Booting worker with pid: 13135
[2018-12-05 15:29:21 +0900] [13136] [INFO] Booting worker with pid: 13136
[2018-12-05 15:29:22 +0900] [13137] [INFO] Booting worker with pid: 13137
[2018-12-05 15:29:22 +0900] [13138] [INFO] Booting worker with pid: 13138
[2018-12-05 15:29:22 +0900] [13139] [INFO] Booting worker with pid: 13139
[2018-12-05 15:29:22 +0900] [13141] [INFO] Booting worker with pid: 13141

**Comment by sgoggins** [comment]
I do get the front end installed after I use 
``` 
make install-dev-admin
```
I had thought we eliminated the need for that, but it seems we need brunch installed as admin. 

Before we get rid of the make architecture, I wonder if we should separate the brunch install since it *seems* like it might be the only thing requiring root access to install?

**Comment by ccarterlandis** [comment]
(@howderek, correct me if I'm wrong) IIRC, we will keep the frontend npm stuff in the `Makefile` for that reason @sgoggins. The main things we want to move out of the Makefile are the Python install scripts; if we want to package Augur, we should have all the installation stuff for it live inside of the `augur/` directory in the project's root folder. That way, the backend and frontend will be more clearly separated (again, that might be totally incorrect. Just my recollection).

**Comment by ccarterlandis** [comment]
After doing a clean install of Augur, I was unable to reproduce this issue. I used `make install-dev-admin`, and not `make install-dev`: @sgoggins, the first time around, did you use `install-dev` as well? It seems to me that `install-dev` is just a weaker version of `install-dev-admin` that doesn't seem to work very well, so I propose we nix `install-dev` and just transparently replace the contents of `make install-dev` with the admin version.

**Comment by sgoggins** [comment]
The installation has evolved. We are ready to close this issue.
