### ISSUE TITLE
Reset button should clear applied compared repos

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#199]
**Is your feature request related to a problem? Please describe.**
When selecting compared repos, the "Reset" button does not reset the applied compared repos, just the ones that have been selected (but not applied) for comparison.

**Describe the solution you'd like**
Clicking the "Reset" button should clear all compared repos from the list, allowing the user to start comparing with an entirely new list of repos.

**Describe alternatives you've considered**
Have two buttons: A "Clear Selection" button and a "Reset Results" button. We would prefer to have just one.

**Comment by gabe-heim** [comment]
Hitting this button now clears selected entries in the drop down AND clears all compared repos
