### ISSUE TITLE
docker hub page is out of date?

### ISSUE THREAD

**Issue by justinabrahms** [chaoss/augur#2004]
Hello.

I went looking for the container image for augur backend. The [docker compose](https://github.com/chaoss/augur/blob/main/docker-compose.yml#L5) file pointed me towards augurlabs/augur on dockerhub. 

This is that url: https://hub.docker.com/r/augurlabs/augur

The build badges on that page are broken and it hasn't been update in 7 months.

I see in [a recent build](https://github.com/chaoss/augur/actions/runs/3108982122/jobs/5038759631) that things are pushing to ghcr.io/chaoss/augur_frontend:latest for the frontend.

It appears that the correct place to find the packages is here: https://github.com/chaoss/augur/pkgs/container/augur_backend

Which means that:
- [ ] The docker hub page should be marked as deprecated
- [ ] The docker compose file should probably reference ghcr.io instead of docker hub

**Comment by sgoggins** [comment]
Thanks, @justinabrahms : Yes, these need to be marked obsolete or removed. Are you getting these links from our docs? 

@IsaacMilarky is our Docker go-to person. Do the containers we build on GitHub work for you? We are using them in our work.

**Comment by justinabrahms** [comment]
I got the location from the docker scripts checked into the repo. I haven't checked the GitHub ones yet. Hoping to test this week or next.

**Comment by sgoggins** [comment]
@justinabrahms : Check out the docker for [release 0.42.6](https://github.com/chaoss/augur/releases/tag/v0.42.6) 

Working on the docs, but the commands are
```
sudo docker-compose AUGUR_GITHUB_API_KEY=1 AUGUR_GITLAB_API_KEY=1 AUGUR_GITHUB_USERNAME=<your GH username, like sgoggins> AUGUR_GITLAB_USERNAME=<your GL username, like superdave> up
```

**Comment by sgoggins** [comment]
@justinabrahms : I believe this is rectified in the Augur 0.43.x and 0.44.x releases. 

If you have a moment to chat on Zoom or check it out yourself I would like to make sure we have addressed this issue.
