### ISSUE TITLE
Text color and spacing

### ISSUE THREAD

**Issue by ccrawford23** [chaoss/augur#2005]
The contrast of the color of text against the background and the spacing of the information on the page was straining and difficult to read.
A solution might be to change text color and make the information more compact instead of scattered across the page.
![s1](https://user-images.githubusercontent.com/115101797/195392116-46f6695c-38c0-4aad-8305-faf6b840e2ac.png)

**Comment by sgoggins** [comment]
Thanks, @ccrawford23 !  We use an API documentation tool to generate this from our code and documentation string. We will look into ways of improving the formatting. If you have an example of API docs you love, it would be great to see them!

**Comment by sgoggins** [comment]
@ccrawford23 : Just checking again to see if you have an API documentation template you think would look better.

**Comment by tarannum-2002** [comment]
can i work on this issue? if yes, can i get more details on which text colour to change an details on spacing?

**Comment by AdityaRaimec22** [comment]
I am really to eager to work on this issue but as I am a newcomer I don't know how to find the code of this issue please help me out

**Comment by AdityaRaimec22** [comment]
@sgoggins I want work on this issue can tell me which documentation tool is used here and how to change this text color and spacing

**Comment by AdityaRaimec22** [comment]
@sgoggins I want work on this issue can you please tell me which documentation tool is used here and how to change this text color and spacing

**Comment by Ulincsys** [comment]
@tarannum-2002 Yes! Please definitely feel free to work on this issue.

@AdityaRaimec22 We use [Read The Docs](https://readthedocs.org/) for our documentation. You can find information about getting started with the software in their [documentation](https://docs.readthedocs.io/en/stable/tutorial/index.html). The source code for our documentation is located in the [docs/](https://github.com/chaoss/augur/tree/main/docs) directory of the project.

We use the default theme for our documentation, and we have no style guidelines at current. You can style it as you see fit.
