### ISSUE TITLE
Text and structure change for better visibility

### ISSUE THREAD

**Issue by witchtrish** [chaoss/augur#2006]
Reading through the schema tables was a bit hard with the way the titles were displayed. A change to title headings would make reading through the [list of data tables](https://oss-augur.readthedocs.io/en/main/schema/regularly_used_data.html) much easier to see.

The typeface of some commands do not match the rest. This is a minor change in the [Make Commands](https://oss-augur.readthedocs.io/en/main/development-guide/make/development.html) page.

Warning and note signs could be different symbols. Both have an exclamation mark and the title after, but at first glance, they seem the same. Maybe have an asterisk for a note and keep the exclamation for warnings.
![image](https://user-images.githubusercontent.com/56330133/195392078-3eabac4f-e46f-41a2-8d1f-48d8a0921104.png)

For context:
![unnamed](https://user-images.githubusercontent.com/56330133/195391415-ae800a74-8f20-40c1-b284-f280608f90aa.png)

![unnamed (2)](https://user-images.githubusercontent.com/56330133/195391413-d2608ce2-a82f-4712-ab22-824267c24ec4.png)

**Comment by sgoggins** [comment]
Thanks, @witchtrish ! This is extremely helpful feedback!

**Comment by glowreeya-01** [comment]
Hello,
Has this issue been assigned already?
I would love to work on it

**Comment by sgoggins** [comment]
We welcome your contributions. Thank you!
