### ISSUE TITLE
Main UI 

### ISSUE THREAD

**Issue by behall3** [chaoss/augur#2007]
The main GUI is very limited, there is a lot of font with small icons. The icons do not get bigger as the page gets bigger. The page does not expand to the whole screen.
![auger2](https://user-images.githubusercontent.com/56844439/195395302-ddb014ff-3741-4e01-9aee-cd8d61659bdd.PNG)

The images so show how to install Ubuntu are not readable for everyone, especially with eye sight issues.
![ubuntu](https://user-images.githubusercontent.com/56844439/195394146-d289afcc-e35a-4211-ba80-63204806a049.PNG)

I would suggest screen shots instead of pictures of the screen. The UI would need to be changed by allowing the website to expand to the full size and the GUI being changed for a more enjoyable read, maybe some images of the software being downloaded. People recognize icons before they recognize a word. New people may not know where to start or what the site is offering

**Comment by sgoggins** [comment]
Thanks @behall3 ! This is an excellent point!

**Comment by meetagrawal09** [comment]
Hey @sgoggins, I would like to update those unclear images in the documentation to clearer screenshots which seem more readable. Can I work on this issue ?
