### ISSUE TITLE
Make compared repo selection dropdown opaque

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#201]
**Describe the bug**
When selecting repos to compare, if the configuration options are expanded, both dropdowns will "lay over" the configuration options and cannot be interacted with.

**To Reproduce**
1. Go to augur and select a repo to examine (i.e. rails/rails
2. Click on "More configuration options"
3. Click on the project or repo dropdown (you need to have at least 42 projects to see the effect)

**Expected behavior**
The dropdowns should be opaque so as to hide what's underneath them.

**Screenshots**
![screen shot 2018-12-13 at 9 16 03 am](https://user-images.githubusercontent.com/31522931/49948273-bf329180-feb8-11e8-8918-1cc34a3d8cf9.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Browser: Safari 12.0.1

**Comment by gabe-heim** [comment]
Now overlays everything else.
