### ISSUE TITLE
Drop-down menus should disappear appropriately

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#202]
**Describe the bug**
This is more of a usability bug. When selecting a drop-down menu, after I click outside of its bounds, nothing happens. The only way to get it to disappear is to click "Apply" or "Reset"

**To Reproduce**
1. Go to Augur and select a repo to examine (i.e. rails/rails
2. Click on the project dropdown
3. Click outside of the bounds of the box

**Expected behavior**
The drop-down menu should disappear.

**Screenshots**
![screen shot 2018-12-13 at 9 17 25 am](https://user-images.githubusercontent.com/31522931/49948656-7d561b00-feb9-11e8-92cb-e3e4e1c38ac7.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Browser: Safari 12.01.1

**Comment by tretrue** [comment]
dropdown now disappears appropriately. Drop down does not disappear when you click anywhere besides the "maincontrols" card.

**Comment by ccarterlandis** [comment]
I can only get this to work by clicking on a single section of the screen, just below the words "Compare from your repos". The drop-down should disappear when the user clicks **anywhere** that isn't inside the drop-down menu. I've attached a screen recording showing this incorrect behavior in action.


[Screen Recording 2018-12-21 at 12.40.20 PM.zip](https://github.com/chaoss/augur/files/2703872/Screen.Recording.2018-12-21.at.12.40.20.PM.zip)

**Comment by gabe-heim** [comment]
They now disappear appropriately by using a vue directive.
