### ISSUE TITLE
Repo search should fail gracefully

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#203]
**Describe the bug**
When searching for repo on Augur's main page, using an invalid repo string (e.g. `asdfghjkl`) then the whole screen goes blank.

**To Reproduce**
1. Go to Augur
2. In the repo search box, type `asdfghjkl`
3. Click search

**Expected behavior**
It should fail gracefully and just display a message saying something to the effect of "The repo `<bad string goes here>` could not be found. Please try again."

**Screenshots**
Before searching for `asdfghjkl`: 
![screen shot 2018-12-13 at 9 52 12 am](https://user-images.githubusercontent.com/31522931/49950126-d3788d80-febc-11e8-998c-aa72b42d2a05.png)

After searching for `asdfghjkl`:
![screen shot 2018-12-13 at 9 52 18 am](https://user-images.githubusercontent.com/31522931/49950138-da9f9b80-febc-11e8-99e5-f3189098115b.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1
 - Browser Safari 12.0.1

**Comment by gabe-heim** [comment]
Now has an alert with something to the effect of what is suggested above.
