### ISSUE TITLE
Augur db add-repos changed format in 0.42.4

### ISSUE THREAD

**Issue by ignacioherdez** [chaoss/augur#2036]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
On current documentation in order to add a repo to the database for previous versions the .csv format was the following:

`group_id,repo_url`

This format does not work as it was changed in newer version and takes the **group_id** behind the **repo_url**, like this:

 `repo_url,group_id`

 **How to reproduce:**
1. Try adding a repo with previous csv format as it is specified in the [readthedocs](https://oss-augur.readthedocs.io/en/main/getting-started/command-line-interface/db.html).

**Expected behavior:**
You will receive an error while adding the repo:

`Invalid repo group_id: https://github.com/chaoss/augur.git for Git url: `10``

**How to Fix:**
Documentation should be reviewed for newer versions and also the --help command for add-repos should show a sample csv format to prevent errors while adding repos.

**Software versions:**
 - Augur: 0.42.4
 - OS: Ubuntu 20.04.5 LTS

**Comment by sgoggins** [comment]
Thanks, @ignacioherdez . @ABrain7710 : I think we should update the docs on this one. I will push a change.

**Comment by sgoggins** [comment]
Issue resolved with documentation update in PR #2029

**Comment by sgoggins** [comment]
New release #0.42.5 https://github.com/chaoss/augur/releases/tag/v0.42.5
