### ISSUE TITLE
Back button doesn't work correctly between the metrics status page and the API docs page

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#205]
**Describe the bug**
When having navigated to API docs page from the metrics status page, if you click the back button, it returns a 404 despite having just come from the metrics status page. 

**To Reproduce**
1. Go to augur.augurlabs.io
2. Click on "Metrics Status" in the header
3. Click on "API Docs" in the header
4. Click the back button

**Expected behavior**
It should return to the metrics status page.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.1
 - Browser: Safari 12.0.1

**Additional context**

**Comment by gabe-heim** [comment]
This works as expected now.
