### ISSUE TITLE
Z-Score Zero Value Error in Visual Option Panel 

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#206]
**Describe the bug**
Sometimes when we do comparisons there are "no data available" pages for some of the graphs by default. However, if we change the visual option panel to change from "Z-Score" to "Baseline is Compared" then the data missing becomes apparent. This is most common with Issues on the GMD panel ... If a project doesn't use issues, it's going to be "all zeros" .. or "no values" ... in these cases then the graph should default to zero values for the repos with no data. See the image below: 

<img width="1222" alt="screenshot 2018-12-21 11 59 39" src="https://user-images.githubusercontent.com/379847/50356714-a9584880-0518-11e9-84ec-388750f8b91d.png">

**To Reproduce**
1. Go to the main augur page
2. Click on 'compare repos' and compare three repos. 
3. Scroll down to select repos until you have one that doesn't have data for issues and you get a "data missing" error.  
4. Then select "more configuration options" and change from Z-Score to "All Data" ... 
5. You will now see all the repos in an issues graph, but with no data for the one that has no issue data. 

**Expected behavior**
Abssence of data should behave the same under Z-Score as it does under "all data".  There should be a line graph comparing the repos with data, and showing the symbol/legend for all the repos .. but no data lines where there is no data. 

**Screenshots**
See above. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome, safari
 - Version : Dev branch as of 12/20/2018. 

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by sgoggins** [comment]
We should get the screen pasted for the Z-Score version as well ... obviously with Z-Scores graphed, but nothing grphaed where there is not any data ...

**Comment by gabe-heim** [comment]
This originated from the z-score function, where the case of the standard deviation being 0 was not handled, since the formula for z-score divides by zero and would cause a divide by 0 error not allowing the chart to show up. This case is handled now.
