### ISSUE TITLE
Discourse Analysis worker facing error!! + Message Insights worker not able to configure. 

### ISSUE THREAD

**Issue by sreekar-G** [chaoss/augur#2072]
**Description:**
I have started the augur with a repo group with 4 repos with default configuration and got Data Collection done for issues and messages. 

Now I need some workers which gives me analysis of messages like Message_Insights_worker and Discourse_Analysis. 

**How to reproduce:**
1. I have got data of issues and messages in database.
2. Now I need to get some analysis in my local machine so I switch off all workers but Message_Insights, github_worker (as message_insights, repo_info, discourse uses the github_url for their models ), repo_info_worker and Discourse_analysis worker.
3. When I check with the data I am not getting any data for quite days in message_analysis / message_analysis_summary. Even I am not getting logs for Message Insights worker. 
4. In Discourse Worker I have got some issues in logs generated. 

**Expected behavior:**
Needed to get analyzed data from the databases messages to discourse and message_analysis

**Screenshots**

I got this in my augur_main.log file.
![Message_insights](https://user-images.githubusercontent.com/99112257/207259836-10afc284-2a34-484f-b841-862dce63c374.png)
 I have manually debugged the code on multiple changes. I am able to bootup the workers in message_insights but In housekeeper.py in updater_process there is no broker keys like message_insights / message_analysis which assigns to workers! and never getting *Housekeeper recognized that the broker has a worker that for message_analysis. not able to debug more!*

This is my broker._getvalue().keys() on switching the workers for message_insights, github, repo_info to 1.
![Discourse Analysis worker](https://user-images.githubusercontent.com/99112257/207260587-a08082e0-0612-4ecc-ae1e-e3eb4250a0e4.png)

**Log files**
This is my Discourse Analysis worker logs which is getting error in tokenizing [discourse_analysis_worker_9310_collection.log](https://github.com/chaoss/augur/files/10215821/discourse_analysis_worker_9310_collection.log) not able to take further step from this!

Please let me know if I miss something and do needful!. 

And I am curious to know for hear the answers for these of questions 
1. how housekeeper and workers (servers which takes request and respond to run) get communicates? I am digging to deep on how they are getting scheduled so that we can schedule them at best?
2. I have turned off all workers and only repo_info is turned on then it ends up saying *end of github block.* and doesn't print anything after that until I turned on github_worker. so As it is using github_url I need to turn on github_worker to process?
3. Need to know what are all workers dependency one each other if exists else how to know if data collection is done in data collection workers completely so that I can turn on ml and analysis workers?
4. Need to know how we add worker_oauths so that we can pull more data from github & gitlab platform? I have searched in documentation I didn't find anything over documenation.
5. How do we compare between two branches of same repo ( so will prefer which is stable on insights / metrics)

**Software versions:**
 - Augur: (currently I am using the old workers setup!!  instead of the new tasks setup of 0.43.3!)
 - OS: (Ubuntu 20.04.5 LTS on Linux)
 - Browser: (if applicable)

**Comment by sgoggins** [comment]
@sreekar-G : Is there a particular reason you are using the older version of code? Do you already have a lot of data collected? I recommend using the latest version of Augur.

**Comment by sreekar-G** [comment]
I want to get the analysis driven from ml workers, I have lots of data collected from github so I am not moving to new setup

**Comment by sgoggins** [comment]
@sreekar-G OK. I know we accounted for empty messages in the new version. I will backport them to the previous version of Augur for you.

**Comment by sreekar-G** [comment]
Hi @sgoggins , 

Just I want to know the results of Message Insights. Currently I have pulled the latest version and ran with default config but still I am not getting data. I just want to know how we can make the message Insights (ML workers) to produce results. I have ~7000 augur_data.messages.

**Comment by sgoggins** [comment]
This issue is resolved in Augur release 0.44.2
