### ISSUE TITLE
Name of Chart Not Displayed if No Data

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#209]
**Describe the bug**
If the chart keeps spinning (visualization) we should at least see the name of the vue card/chart.  Which we don't right now. 

**To Reproduce**
1. Go to 'main augur page'
2. Click on 'any of hte listed git repos'
3. Scroll down to 'growth maturity and decline tab
4. See error:

<img width="1189" alt="screenshot 2018-12-29 13 22 21" src="https://user-images.githubusercontent.com/379847/50541680-30886a80-0b70-11e9-920f-7108afc245ff.png">

**Expected behavior**
I should see the name of the metric Vue card that is spinning

**Screenshots**
above. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
n/a

**Additional context**

n/a

**Comment by gabe-heim** [comment]
Now fixed to look like this.
<img width="1280" alt="screen shot 2018-12-29 at 3 52 51 pm" src="https://user-images.githubusercontent.com/20764846/50550527-da7efa00-0c37-11e9-95a4-44c2f6219fe4.png">
