### ISSUE TITLE
Minor Styling Issues (Browser Specific Issues)

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#210]
These are small improvements, but they'll help everything look nicer.

This styling under the lines of code by top authors by percentage chart should be properly spaced:
<img width="665" alt="screen shot 2018-12-29 at 1 44 11 pm" src="https://user-images.githubusercontent.com/31522931/50541667-03d45300-0b70-11e9-907b-074b2451dfcb.png">

The "Repo not found" text should be centered both horizontally and vertically: 
<img width="795" alt="screen shot 2018-12-28 at 5 30 56 pm" src="https://user-images.githubusercontent.com/31522931/50541673-1a7aaa00-0b70-11e9-9609-d99d71b29c5a.png">

Each chart and the links/info displayed underneath them should be aligned:
<img width="687" alt="screen shot 2019-01-03 at 6 32 46 pm" src="https://user-images.githubusercontent.com/31522931/50668737-a46aae80-0f86-11e9-9735-e09b4140ef9e.png">

**Comment by tretrue** [comment]
![image](https://user-images.githubusercontent.com/31676518/50659079-0d3f3000-0f61-11e9-9917-aae57d94fdd4.png)

**Comment by ccarterlandis** [comment]
Looks good @tretrue! 👍

**Comment by tretrue** [comment]
weird question carter, but what is your screen zoom at? because im at 100% on chrome and the charts look just fine. or are you wanting to have it stay framed in no matter the zoom??

**Comment by tretrue** [comment]
@ccarterlandis ^^

**Comment by ccarterlandis** [comment]
@tretrue: this is on Safari, full screen, default zoom (100%).

**Comment by tretrue** [comment]
![image](https://user-images.githubusercontent.com/31676518/50792822-e1d38280-128b-11e9-8b55-609d6b44ed2e.png)

**Comment by ccarterlandis** [comment]
Is that pushed? @tretrue

**Comment by tretrue** [comment]
Yes
