### ISSUE TITLE
Add a "Frequently encountered erros" sections in the Augur docs

### ISSUE THREAD

**Issue by WhiteWolf47** [chaoss/augur#2116]
There can be some errors that one may face while setting up augur on one's local machine. A very good solution for this can be creating a separate section in the docs where people who have encountered such errors previously and resolved them can add the problem description and its solutions

**Comment by sgoggins** [comment]
@WhiteWolf47 : Are you thinking like an FAQ?

**Comment by WhiteWolf47** [comment]
Yes, maybe we can even add something which is more interactive like where in under a particular FAQ ,peeps can ask ques regarding this. Or even a normal FAQ like section in the docs would do the work.

**Comment by sgoggins** [comment]
@WhiteWolf47 : We are exploring documentation systems that also provide wiki like functionality to enable fast additions of FAQ's. Issue #2183 has a number of suggestions. This one, in particular has these types of features (though I'm sure others do as well). https://www.notion.so/ 

I'm curious if you have an example or two of projects that do this well. We don't have a strong need to reinvent the wheel. :)
