### ISSUE TITLE
Make contribution platform rules visible in analysis

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#2117]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

Augur does an excellent job taking all contribution types into account. There are platform-specific rules for which contributions are counted in GitHub statistics. Augur differences are based on value judgements and the culture of Augur using companies, groups, OSPO's, etc. 

**Potential solutions:**
Make these differences visible and explain them in context.

**Comment by MauryaRitesh** [comment]
Hi, can I work on this issue?

**Comment by shubham21155102** [comment]
@sgoggins  sir i will very grateful if you assign me work on this

**Comment by BhaswatiRoy** [comment]
Hello @sgoggins 
Are you suggesting displaying the platform rules on https://www.augurlabs.io/ website?
