### ISSUE TITLE
Terminal obtained link is not working

### ISSUE THREAD

**Issue by shubham21155102** [chaoss/augur#2129]
The link that we are getting in terminal after setting up the database is not working
[https://github.com/shubham21155102/STL-formation-/blob/main/Screenshot%20from%202023-01-18%2014-16-54.png](url)
[https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html#backend](url)
[https://github.com/shubham21155102/STL-formation-/blob/main/Screenshot%20from%202023-01-18%2014-17-14.png](url)
<img src="https://raw.githubusercontent.com/shubham21155102/STL-formation-/main/Screenshot%20from%202023-01-18%2014-17-14.png">
<img src="https://raw.githubusercontent.com/shubham21155102/STL-formation-/main/Screenshot%20from%202023-01-18%2014-16-54.png">

**Comment by sgoggins** [comment]
@shubham21155102 : Thank you for pointing this out. Our `dev` docs appear to have been removed from our readthedocs.io publishing process. Quoting the 1980's English band "The Police", I will write this off to a "Ghost in the Machine" and apologize to you. 

The `dev` branch documentation should be compiled and available within a few minutes. Meanwhile, the `main` branch is up to date with our most significant new release (See our README.md file for details). That link is here. Again, sincere apologies for creating this confusion for you.
