### ISSUE TITLE
Comparison URL Sharing Not working

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#214]
**Describe the bug**
When you share a regular, single repo URL, it works!!!  When you share a link to comparisons, the link does not work.  

**To Reproduce**
1. Go to 'compare'
2. Click on 'choose a repo to compare'
3. Copy and past the URL into another browser (chrome --> firefox etc)

This works: http://localhost:3333/singlegit/git/github.com%2Ftwitter%2Felephant-bird.git#
This does not work: http://localhost:3333/compare/gmd/github.com%2Ftwitter%2Felephant-bird.git/comparedto/pulp/pulp_rpm

**Expected behavior**
Both links should work

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by gabe-heim** [comment]
Both of these types of links should work when clicked on now. Please reopen if you still have any problems.
