### ISSUE TITLE
Issue when running augur backend --help and running augur --help

### ISSUE THREAD

**Issue by salleejackson2020** [chaoss/augur#2150]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
ValueError thrown when running augur backend --help and running augur --help commands

**How to reproduce:**
Run the commands

**Expected behavior:**
Help description from augur

**Screenshots**
Error log when running augur backend --help
![image](https://user-images.githubusercontent.com/25645829/214657838-ba27181a-979a-40ab-8e59-c952f9ffc18a.png)
![image](https://user-images.githubusercontent.com/25645829/214657978-306f4d80-2de8-44ad-86d4-bc987b43e280.png)
![image](https://user-images.githubusercontent.com/25645829/214658199-f814f815-c239-4943-bfb6-f3a54e4a8cb1.png)
Error log when running augur --help
![image](https://user-images.githubusercontent.com/25645829/214658609-fbe2ec35-4345-4644-8c40-4ebdee3af30f.png)
![image](https://user-images.githubusercontent.com/25645829/214658712-4a32207c-bab3-402c-961e-d7b75d78f7f0.png)
![image](https://user-images.githubusercontent.com/25645829/214658793-a41a3b26-b605-4bfb-8ece-38dfef1fdcf8.png)
![image](https://user-images.githubusercontent.com/25645829/214658947-d0a41807-ac35-45bb-9719-ca185bb33bd5.png)

**Log files**
Attach the relevant log files here. Server and installation logs can be found in the `logs/` directory in the root `augur/` directory, and the logs for each worker are stored in their respective directories. If the logs are pretty long (> 50ish lines or just use your best judgement) please use a Gist or a [pastebin](https://pastebin.com/). **These logs file are required if you would like help solving your issue.**

**Software versions:**
 - Augur: 0.43.10
 - OS: Ubuntu 22.04.1 LTS

**Comment by sgoggins** [comment]
@salleejackson2020 : What version of Ubuntu are you using? There's an issue with 22.x that arises from our machine learning tasks. tl;dr : Ubuntu 22.x defaults to Python3.10 and a number of ML libraries are not yet ported to that major release. This happens with EVERY major python release because a significant proportion of ML libraries in python are written in Fortran, and the ports take time. We are actively working on making this a non-issue for Augur.

**Comment by salleejackson2020** [comment]
Looks like its Ubuntu 22.04.1 LTS

**Comment by sgoggins** [comment]
@salleejackson2020 : OK, I think there's another PR that just got opened that will make the necessary changes for Python 3.10 work; which would then get us up to 22.04.1 LTS. Give us a week or two. We are getting some key software supply chain security updates (for analysis of repos) done in front of this fix. THANK YOU!  @IsaacMilarky / @ABrain7710  .... note.

**Comment by sgoggins** [comment]
This issue is resolved in the latest release.
