### ISSUE TITLE
Missing/inconsistent documentation on VirtualBox under Quickstart 

### ISSUE THREAD

**Issue by logandeal** [chaoss/augur#2157]
**Is your feature request related to a problem? If so, please describe the problem:**
Yes, the problem is that there are pieces of missing/inconsistent documentation in the VirtualBox installation process under the Quickstart section.

The issues are as follows:

1. There is no VirtualBox documentation guide for users with operating systems other than Windows.
2. There are no ISO-related documentation instructions even though it is specified when creating a virtual machine (in the Oracle VirtualBox prompt). 

(MacOS specific)
3. There are no hard disk file type or physical hard disk options to select when creating a virtual machine (in the Oracle VirtualBox prompt). 

**Potential solutions:**
N/A

**Additional context:**
N/A

**Comment by sgoggins** [comment]
@logandeal : I recommend the new installation instructions under Augur version 0.44.2: https://github.com/chaoss/augur/blob/main/docs/new-install.md 

If you want to use OSX native, Augur works quite well. We just need to provide the equivalents for `sudo apt ..` ... which is largely `brew install`

**Comment by sgoggins** [comment]
@logandeal : My native OS is OSX most of the time. Do you want to try the translation yourself and maybe issue a PR, or would you prefer if I put together the OSX docs? I'm happy with either path.  THANK YOU!

**Comment by logandeal** [comment]
Thank you for the info. I think you would be more well-versed in putting together the OSX docs.
