### ISSUE TITLE
Installation issues in Quickstart (VirtualBox and Python Virtual Environment Config.)

### ISSUE THREAD

**Issue by bondecai** [chaoss/augur#2158]
**Description:**
Incorrect installation package for python virtual environment configuration and missing root access when creating VM

**Issue 1**
Installing VirtualBox 7 and checking unattended installation, the created user will not have root access to use sudo and continue the rest of the Quickstart.

**Fixes**
During installation of VirtualBox, do not do an unattended installation.
Alternatively, 
1. Boot into Rescue Mode
2. Select Advanced options for Ubuntu
3. Then select a recovery mode (second option from top)
4. Select root and use the command `adduser yourUsername sudo`

**Issue 2**
In the Python Virtual Environment Configuration, installing package python-pip-whl has no installation candidate.
I installed python3-pip-whl instead.

**Expected behavior:**
Users creating in VirtualBox should have root access to run sudo. Installing python-pip-whl should not have a no installation candidate error.

**Software versions:**
 - Augur: 0.43.10
 - OS: Windows 10

**Comment by sgoggins** [comment]
Try Augur: 0.44.2 

Also, I have to warn folks that our documentation is pretty clear that Windows installations are deeply flawed. This is a problem with Windows, not Augur. Even the Ubuntu subsystem on Windows does not comply with the way Ubuntu native works. 

Right now, I recommend a virtual machine with Ubuntu 20.0x
