### ISSUE TITLE
Installation Extremely Difficult for Mac Users

### ISSUE THREAD

**Issue by NerdyBaseballDude** [chaoss/augur#2160]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
Hello, I am working on installing and building augur from my mac and am running into numerous issues. I have been trying to follow the documentation as closely as possible, but haven't been able to install correctly. 

At first I tried installing using virtual box, which I downloaded and set up exactly how the documentation described. However, I could not get the machine to boot up. I got the error that: "The virtual machine failed to boot"... (screenshot below). I am confident that I followed the documentation to a tee and have retried installing 3 different times with the same result

![image](https://user-images.githubusercontent.com/87952981/215365074-370467f5-f1be-408f-97fd-85ce9edcb97c.png)

After that failed, I just tried to clone and install from the command line. I was able to install the repo successfully and create a virtual environment. However, when I ran `make install` I got the error that `Failed to build pandas psutil h5py greenlet` I do not understand why this is the case, no error message was ever printed during installation and I have downloaded the packages just fine outside of the virtual environment. Everything looks like it was running fine until I get the error message at the end. Any ideas on how to debug either one of these 2 issues?

**Software versions:**
 - Augur: v0.43.10
 - OS: macOS (M1 chip)

**Comment by sgoggins** [comment]
@NerdyBaseballDude : Are you using a VM or OSX Native?
