### ISSUE TITLE
Mac installation issues

### ISSUE THREAD

**Issue by J-robinson11** [chaoss/augur#2161]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**

**How to reproduce:**

**Expected behavior:**

**Screenshots**
If applicable, add screenshots to help explain your problem. If your bug is related to the UI, you **must** include screenshots.

**Log files**
Attach the relevant log files here. Server and installation logs can be found in the `logs/` directory in the root `augur/` directory, and the logs for each worker are stored in their respective directories. If the logs are pretty long (> 50ish lines or just use your best judgement) please use a Gist or a [pastebin](https://pastebin.com/). **These logs file are required if you would like help solving your issue.**

**Software versions:**
 - Augur: (you can use `pip show augur` to find your version)
 - OS: (`sw_vers` for macOS, `lsb_release -a` on Linux)
 - Browser: (if applicable)

**Comment by Preshh0** [comment]
Hi @J-robinson11 what issues exactly did you face?  Could you attach screenshots and error messages?

**Comment by sgoggins** [comment]
@J-robinson11 : The latest release provides much better installation instructions. Please give that a try!

**Comment by Preshh0** [comment]
Hi @sgoggins I tried using the recent installation instructions so I could update the docs and still faced a few blockers. The weekly session didn't hold, as I wanted to ask for help there. Can one be scheduled within the week so I can edit the installation instructions in the [Quickstart guide](https://oss-augur.readthedocs.io/en/main/quick-start.html).
