### ISSUE TITLE
No detailed documentation on installation process.

### ISSUE THREAD

**Issue by MANISHSRIDHAR** [chaoss/augur#2163]
The problem is that the documentation is not complete and well explained in the VirtualBox installation process in the Quickstart section.

The issues are as follows:

There is no documentation guide for VirtualBox for users with operating systems other than Windows.

MacOS - There are no hard disk file type or physical hard disk options to select when creating a virtual machine.

**Comment by Preshh0** [comment]
Hi @MANISHSRIDHAR, could you take screenshots to show exactly what part was confusing for you? I could update the doc. Or, if you've found a solution and fixed it, you could work on it and create a PR.

**Comment by sgoggins** [comment]
https://github.com/chaoss/augur/blob/main/docs/new-install.md Is robustly tested on Ubuntu 20.x now.

**Comment by sgoggins** [comment]
I'm going to combine this with issue #2183
