### ISSUE TITLE
Docs incorrectly rerouted on dev.augurlabs.io

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#220]
**Describe the bug**
When trying to access the docs on [dev.augurlabs.io](dev.augurlabs.io), the docs incorrectly reroute to `localhost`.

**To Reproduce**
1. Go to [dev.augurlabs.io](dev.augurlabs.io)
2. Click on "API Docs"
3. See error

**Expected behavior**
The docs should show up when I click on the links

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Browser: Safari 12.0.2

**Comment by sgoggins** [comment]
@ccarterlandis : you and @howderek have this?

**Comment by ccarterlandis** [comment]
I will work on it. We've seen this before, so hopefully, it won't be too hard of a fix. @sgoggins

**Comment by ccarterlandis** [comment]
Fix in `dev` as of [this](https://github.com/chaoss/augur/commit/6e35480d75db0765aa1210154febc26ed3734ef4) commit.
