### ISSUE TITLE
Conda Environment Setup and Maintenence

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#225]
**Describe the bug:**
I've never used the conda environment for augur, primarily because it will not work as expected for me. I've tried tweaking it around a few times, using strategies like adding conda to the environment, but it will produce different errors.

**To Reproduce:**
Here is a basic "what happens when" scenario:
1. Call `make install-dev` or any variation that uses conda
2a. If I don't add conda to the environment, this happens:
![image](https://user-images.githubusercontent.com/34951354/51727048-087d1180-201f-11e9-9338-41271fdf6be7.png)
2b. If conda has been added to the working path, the conda environment will not instantiate or resolve

**Expected behavior:**
I'm not entirely sure what purpose the conda enviroment serves, as everything works if it fails.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.5
 - Browser: Terminal

**Comment by ccarterlandis** [comment]
@Nebrethar have you by any chance looked at [this](https://github.com/chaoss/augur/pull/222) PR? @parthsharma2 mentioned that he had been able to get Augur working without Anaconda as well. I'd love to chat with the two of you sometime and discuss your experiences with Anaconda and if it's worth the continued support (spoiler: I don't think it is).

**Comment by Nebrethar** [comment]
Thanks for referring to the PR, also +1 for ditching anaconda, though I don't know much about its use otherwise.

The conda environment fails every time I use `make dev` or `augur` and I've run I to no related hiccups with functionality. That's what I do know.

**Comment by ccarterlandis** [comment]
We've decided to use Anaconda only to manage the version of Python installed, and not to manage the packages. Augur will still work perfectly fine without it; it's just to make our lives easier.
