### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by germonprez** [chaoss/augur#2269]
Hi, 

Could you please update your code of conduct to use the CHAOSS Code of Conduct and not the Contributor Covenant? 

You can simply 

1) Point to: https://github.com/chaoss/.github/blob/main/CODE_OF_CONDUCT.md
2) Remove your existing Code of Conduct in your repository

The intention here is to have all CHAOSS repositories use and point to the same Code of Conduct.

**Comment by sgoggins** [comment]
Done!
