### ISSUE TITLE
Risk CII Badge Behavior and Contextualization

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#228]
BRANCH: dev

**Is your feature request related to a problem? If so, please describe the problem:**
I see the badging info for CII when I go to repositories that have the same name as the GitHub organization. For example, 
 - ceph/ceph and 
 - pulp/pulp

I don't see anything when I look at pulp/pulp_rpm though. Similar with others that don't follow the pattern above. 

**Describe the solution you'd like:**
I would like to know if this is a defect in our implementation or an anomaly that is beyond our control. That's first. I think the solution need to be 1 of 2 things conceptually: 
1. Provide some short, narrative contextualization for what you are looking at on the risk page if, in fact, the badging would be at the "collection of repositories" level instead of the individual, discrete repository level or
2. Make it work for all the repos. 

**Describe alternatives you've considered:**
listed above. 

**Additional context:**
I'm using firefox.

**Comment by Nebrethar** [comment]
It looks like pulp is the only repo with a CII badge that has the name pulp in it. I cna also confirm that this is what the page looks like when it fails to pull data. I will merge that fix when we arrive or possible sooner. 

Thanks for looking out for that.

**Comment by ccarterlandis** [comment]
Looks like this has been implemented in `dev`. Closing for now, but if I'm wrong please re-open.
