### ISSUE TITLE
add multiple repos and groups in a return separated list

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#2282]
Instead of just one repo or group at a time, allow the pasting of many ... AND both repo URLs and github orgs at the same time.... because people are just going to do that. 

![Image](https://user-images.githubusercontent.com/379847/229673518-9f814232-6e69-4f24-b6fa-b80991848453.png)

**Comment by ABrain7710** [comment]
This issue is complete with pull request #2300
