### ISSUE TITLE
augur.config.json deleted when augur is installed or reinstalled

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#233]
**Is your feature request related to a problem? If so, please describe the problem:**
On reinstall or reconfiguration of dependencies, augur will get rid of the augur.config.json file and my configuration will be lost. I am using Ubuntu 16.04.

I set up a fresh install to test installation and created an augur.config.json. I had to update augur's requirement version of "requests" to match runtime requirements; a typical bug. After updating this dependency, I ran the installer again and my augur.config.json file was gone.

**Describe the solution you'd like:**
I've got an idea, but I don't know how to execute it. I was thinking a default augur.config.json file could be generated on install, but only if there is none present.

**Describe alternatives you've considered:**
I normally just create a new one when it is gone, but for some users that may not be as easy.

**Additional context:**
Related issues [#176](https://github.com/chaoss/augur/issues/176) and [#227](https://github.com/chaoss/augur/issues/227)

**Comment by Nebrethar** [comment]
#229 Relating to the augur.config.json remark in OP

**Comment by ccarterlandis** [comment]
If there is no `augur.config.json` file present, running the command `augur` will create a default one that looks as follows: 
```{
    "Cache": {
        "config": {
            "cache.data_dir": "$(AUGUR)/runtime/cache",
            "cache.lock_dir": "$(AUGUR)/runtime/cache",
            "cache.type": "file"
        }
    },
    "Plugins": []
}
```

While this default config should be changed to reflect what plugins are installed, for the purposes of closing this issue this current default is fine. I propose opening another issue that details a need to create a default config based on the installed plugins.
