### ISSUE TITLE
Repo set to initializing forever

### ISSUE THREAD

**Issue by ABrain7710** [chaoss/augur#2401]
**Description:**
The bug happens when an unexpected error occurs in the `clone_repos` task. Then the task auto retries in 5 minutes, but the repo that errored never gets it's `facade_status` updated, so it is left at `Initializing` forever.

**Expected behavior:**
Where an unexpected error occurs in clone_repos the repo should be set to `Pending` or `Error`

**Comment by IsaacMilarky** [comment]
I think we should set the repository to Error when we run into an issue like this otherwise it will just cycle through the failed repositories over and over when it has no other repos left to clone.
