### ISSUE TITLE
Augur View Registration Form Behavior

### ISSUE THREAD

**Issue by ABrain7710** [chaoss/augur#2403]
**Description:**
If user enters a user name and password before pressing the register button, it jumps the user to the email field rather than jumping them to the next field in the list (confirm password). 

Note: It works properly if the user doesn't enter a user name or password and presses register, and also if the user only enters a username then presses register

**How to reproduce:**
1. Enter user name
2. Enter password
3. Press register
4. See that the cursor jumped to the email field

**Comment by sgoggins** [comment]
@Ulincsys

**Comment by sgoggins** [comment]
@Ulincsys : Is this fixed?

**Comment by kaxada** [comment]
@sgoggins assign me this issue. I was in contact with @Ulincsys and he proposed I fix

**Comment by Ulincsys** [comment]
Closed by #2564
