### ISSUE TITLE
Update section titles of chart configuration options

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#243]
**Is your feature request related to a problem? If so, please describe the problem:**
On the leftmost section of the chart configuration options (the section related to line chart options), there's no title to indicate which section the options are related to. Additionally, the title for the section for changing date ranges is "Configuration", which is generic and does not uniquely identify that section's purpose.

**Describe the solution you'd like:**
Each logical section of the configuration should have a short, descriptive title to enable users to have a better understanding of where to quickly find which options.

**Describe alternatives you've considered:**
I don't see any reasonable alternatives to titling these sections.

**Additional context:**
<img width="720" alt="screen shot 2019-03-04 at 18 10 52" src="https://user-images.githubusercontent.com/31522931/53771603-e477e000-3ea8-11e9-808c-7176aa714a11.png">
This is the section that has no title.

<img width="720" alt="screen shot 2019-03-04 at 18 10 58" src="https://user-images.githubusercontent.com/31522931/53771614-ee014800-3ea8-11e9-9c0d-56c112348c37.png">
This is the section with a confusing title.

**Comment by tretrue** [comment]
![image](https://user-images.githubusercontent.com/31676518/53903516-89113380-4009-11e9-8edb-f8bdb37b5b26.png)

**Comment by ccarterlandis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Config section titles](https://trello.com/c/HbmPWQls/10-config-section-titles)
