### ISSUE TITLE
Data Source Information in API Docs

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#244]
*For API Docs I would like to see the data source that we have in metrics status also implemented in the API docs so I know the data source when I am looking at the api docs.

**Comment by ccarterlandis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show data source for metrics in API docs](https://trello.com/c/apJTJqhg/5-show-data-source-for-metrics-in-api-docs)

**Comment by ccarterlandis** [comment]
Added to `hotfix` as of [this](https://github.com/chaoss/augur/pull/248/commits/642934f5a5c81bb7591bc72544e7ff01520232fa) commit.
