### ISSUE TITLE
Installing on EC2 22.04.1-Ubuntu instance: make install fails while trying to connect to rabbitmq

### ISSUE THREAD

**Issue by jansche** [chaoss/augur#2445]
**Description:**
Following the [install guide for Ubuntu](https://oss-augur.readthedocs.io/en/main/quick-start.html#ubuntu-22-x) with only one deviation at the installation of firefox (used: `sudo apt install firefox=115.0~b5+build1-0ubuntu0.22.04.1` instead of: `sudo apt install firefox=111.0~b8+build1-0ubuntu0.22.04.1`) and otherwise all according to the documentation, the make install script always terminates due to not being able to connect to the rabbitmq db broker:
`ERROR: Could not connect to database. Please check database configuration`

Digging into /var/log/rabbitmq/rabbit@[hostname].log brings up this error:
```
2023-06-15 11:32:27.424400+00:00 [info] <0.3278.0> accepting AMQP connection <0.3278.0> (127.0.0.1:34034 -> 127.0.0.1:5672)
2023-06-15 11:32:27.424933+00:00 [error] <0.3278.0> closing AMQP connection <0.3278.0> (127.0.0.1:34034 -> 127.0.0.1:5672):
2023-06-15 11:32:27.424933+00:00 [error] <0.3278.0> {bad_header,<<0,0,0,8,4,210,22,47>>}
```

Followed through with @sgoggins [in this thread](https://chaoss-workspace.slack.com/archives/C0226ELG6R4/p1685009287443189) at the CHAOSS Slack, but we couldn't fix it.

**How to reproduce:**
1. Provision AWS EC2 22.04.1-Ubuntu instance with 24GB storage and a t2.small AMI
2. Follow installation guide for Ubuntu
3. Run `make install`

**Expected behavior:**
Clean finish of make install.

**Screenshots**
no screenshots

**Log files**
https://pastebin.com/LX6P2QtC
https://pastebin.com/BRnTZ5h9

**Software versions:**
 - Augur: v0.50.3
 - OS: 
ubuntu@[hostname]:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by Seltyk** [comment]
There were some recent-ish changes to Augur's install process that may have outdated that guide. Try [this one](https://github.com/chaoss/augur/blob/main/docs/new-install.md) and see if the results are any better.

**Comment by jansche** [comment]
Thanks, @Seltyk. I could install Augur thanks to your hint. I was mixing up the database and broker configuration, I think. 
I tried to enter rabbitmq user, password and db (augur_vhost), when I should have entered postgresql details.

 I'm running into new errors while trying to start Augur, but this issue was solved. Closing.
