### ISSUE TITLE
Add Commits Summary Page for git Repo

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#245]
Implement the same visualization style for commit statistics as we have for lines of code against git respositories. 

![augur](https://user-images.githubusercontent.com/379847/53877668-68c48300-3fcf-11e9-8f3f-f7d3087878c9.png)

**Comment by sgoggins** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Commit Graphs](https://trello.com/c/6UzisS6p/1-commit-graphs)

**Comment by gabe-heim** [comment]
Keep in mind that every tick or circle on the top chart IS a commit, so a different viz showing commits statistics over time would look about the same, this one is a bit hard to read when going in with the desire to look at commits. I'll brainstorm potential options

**Comment by tretrue** [comment]
What browser and zoom are you using? On Chrome 100 zoom, the whitespace between "...-By Time Period" and "... Authors Visualized" is about half that: 
![image](https://user-images.githubusercontent.com/31676518/53915415-7e649780-4025-11e9-80b4-987f0f3a94de.png)

**Comment by sgoggins** [comment]
@tretrue : Here's some additional thoughts from our stakeholder. What they want is the ability to get a list of whose commits are in a time period. Perhaps selected. Perhaps click a spot and pick a date *my question*
Seeing commits question regarding the graph I sent earlier: Would you prefer a table layout or a more finely resolved graph, do you think? 

*quote key*: 
**Table layout of the commits associated with a blob,  ie.  click on blob,  get list of commits (and size associated),  with hotlink to actual commit?   Possible?**

**My Thought** 
Depending on the number of commits involved in a period, the graph version may or may not give you a readable set of details. I’m thinking a list. ?

Let me know. We will build that. 

**Sorted list. Ding ding!**
Agree sorted list would be more natural to interact with.   Thanks!

**Comment by ccarterlandis** [comment]
@tretrue: I don't think it's fair to expect users to use any one specific browser, so we should implement things in a way that they still look good on any browser. At a minimum, I think we should focus on Firefox and Google Chrome, since Chrome is quite widespread and I'd wager that many people in the open source community use Firefox.

**Comment by tretrue** [comment]
@ccarterlandis i completely agree with you. Dynamically setting the whitespace should not be that big of a deal, I was curious as to which browser/zoom being used that way i can see it from his angle too just to be safe. I'll play around with both firefox and chrome. Thanks!

**Comment by sgoggins** [comment]
Done!
