### ISSUE TITLE
Slow GET requests for repos and groups

### ISSUE THREAD

**Issue by Seltyk** [chaoss/augur#2452]
**Description:**
As Augur builds a larger and larger library of repos and repo groups, GET requests to the API get slower, to the point where a request for repos in the "apache" group takes a whopping 44 seconds. Requesting *all* repos takes 24 seconds. Timed using `time curl`. Curiously, the group request idles for almost that entire time before any JSON is printed to the terminal, whereas the all-repos request starts printing after merely one second.

**How to reproduce:**
1. `time curl -H 'Accept: application/json' 'https://foo.bar.baz/api/unstable/repo-groups/[some ID]/repos'`
2. Wait hours or days for Augur's database to grow
3. Run that command again, and see that it takes an eternity.

You can also try `https://foo.bar.baz/api/unstable/repos` to compare the idling time.

**Expected behavior:**
I know there's a ***lot*** of data here, but it really shouldn't take THAT long to load it all. Besides, the request for one repo group's data should take significantly less time than the request for every repo in the database.

**Log files**
I have no idea which log files would be most relevant, so just have [all of them tar-gz'd](https://github.com/chaoss/augur/files/11884725/laugur.tar.gz).

**Software versions:**
 - Augur: 0.50.3
 - OS: Ubuntu 23.04
 - Browser: Firefox 113.0.1-1 (via snap (I hate Ubuntu))

**Comment by sgoggins** [comment]
@Seltyk : Thanks for catching that. I see the performance issue in the API code and am testing a patch.

**Comment by sgoggins** [comment]
@Seltyk : The performance issue is specific to the repo_groups endpoints, FYI. Testing the fix.

**Comment by sgoggins** [comment]
@Seltyk : This issue is fixed in the `dev` branch, and will be released in the next day or so.

**Comment by sgoggins** [comment]
Fixed by PR #2451
