### ISSUE TITLE
Frontend 'Repos' list not filterable

### ISSUE THREAD

**Issue by JamesKunstle** [chaoss/augur#2457]
**Description:**
'Filter Repos' input isn't working in augur frontend.

**How to reproduce:**
1. Go to 'https://eightknot.chaoss.tv/repos/views/table'
2. Filter repos by some obviously present string, e.g. 'anaconda-project'
3. See that page returns "Your search did not match any repositories"

**Expected behavior:**
For the table to show rows of repos available in the DB that match the filter.

**Screenshots**
<img width="1709" alt="Screenshot 2023-06-30 at 10 11 08 AM" src="https://github.com/chaoss/augur/assets/52969093/4b28232c-60c5-451b-9e67-ddce70ee195e">

After inputting reasonable filter to get project that I see in table, page reports that no repos match.

<img width="1728" alt="Screenshot 2023-06-30 at 10 16 30 AM" src="https://github.com/chaoss/augur/assets/52969093/acf79585-9c36-4ffe-95de-23e1c08d83a4">

**Comment by sgoggins** [comment]
Got it, @JamesKunstle !

**Comment by sgoggins** [comment]
Fixed by PR #2577
