### ISSUE TITLE
Vagrant: Bad augur.config.json generated

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#247]
**Describe the bug:**
The augur.config.json file generated by the vagrant install is not "right". 
```json

{
    "Cache": {
        "config": {
            "cache.data_dir": "$(AUGUR)/runtime/cache",
            "cache.lock_dir": "$(AUGUR)/runtime/cache",
            "cache.type": "file"
        }
    },
    "Plugins": []
}
```

**To Reproduce:**
1. Follow vagrant install
2. get through workaround for upgrade of request
3. Run augur

**Expected behavior:**
Augur.config.json that will include all necessary configs. 

**Screenshots**
n/a

**Desktop (please complete the following information):**
- vagrant
 
**Additional context**
n/a/

**Comment by ccarterlandis** [comment]
Fixed in `hotfix` as of [this](https://github.com/chaoss/augur/pull/248/commits/d89eea95173fa134b4ee8f88e429ee0c8ba9b58c) commit.
