### ISSUE TITLE
Getting a UnicodeEncodeError and not sure how to fix it

### ISSUE THREAD

**Issue by tibitoy** [chaoss/augur#2475]
Tried download augur, a bioinformatic tool. It seems to download perfectly but when I try to run "augur --help" I get the following error: File "/home4/tibitoy/miniconda3/bin/augur", line 8, in sys.exit(main()) File "/home4/tibitoy/miniconda3/lib/python3.9/site-packages/augur/main.py", line 10, in main return augur.run( argv[1:] ) File "/home4/tibitoy/miniconda3/lib/python3.9/site-packages/augur/init.py", line 64, in run args = make_parser().parse_args(argv) File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 1824, in parse_args args, argv = self.parse_known_args(args, namespace) File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 1857, in parse_known_args namespace, args = self._parse_known_args(args, namespace) File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 2066, in _parse_known_args start_index = consume_optional(start_index) File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 2006, in consume_optional take_action(action, args, option_string) File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 1934, in take_action action(self, namespace, argument_values, option_string) File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 1098, in call parser.print_help() File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 2554, in print_help self._print_message(self.format_help(), file) File "/home4/tibitoy/miniconda3/lib/python3.9/argparse.py", line 2560, in _print_message file.write(message) **UnicodeEncodeError: 'latin-1' codec can't encode character '\u2192' in position 3174: ordinal not in range(256)**

Any possible solutions? For reference, I'm using linux.

**Comment by corneliusroemer** [comment]
I think this is the wrong repo for the tool you installed, the issue here is the right place: https://github.com/nextstrain/augur/issues/1272

**Comment by Ulincsys** [comment]
Glad to see you got the issue resolved!

I'll close this since it's unrelated here.
