### ISSUE TITLE
Missing/Incorrect Info Installation Instructions MacOSX

### ISSUE THREAD

**Issue by jkgrmc** [chaoss/augur#2511]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
There are some issues in the installation instructions for Mac OS X. On several occasions there are commands that the user is shown, but not always directly asked to run. Also, it is not clear where to run these commands. Following the instructions linearly will produce some errors because the PATH variable updates are necessary to run rabbitmq-plugins and other rabbitmq commands, so those sections should be switched in order. Finally, during the 'make install' command, an intel Mac and an Apple Silicon Mac both encountered an error with version 1.7.3 of a package not being found.

**How to reproduce:**
1. Follow instructions at https://github.com/chaoss/augur/blob/dev/docs/dev-osx-install.md
2. Will occur at 'make install' command

**Expected behavior:**
I expect some minor improvements to the instructions to make them more clear about commands. Also, I expect the 'make install' command to execute without an error.

**Screenshots**
<img width="1792" alt="augur_install_evidence" src="https://github.com/chaoss/augur/assets/142946475/38df6a3d-21e9-4856-b001-ba0d8f159ef3">

**Log files**
[backend-install.log](https://github.com/chaoss/augur/files/12508876/backend-install.log)

**Software versions:**
 - Augur: 0.52.0
 - OS: macOS 13.5.1

**Comment by sgoggins** [comment]
@jkgrmc : 
1. What version of Python are  you running? I'm assuming python3@3.11 on OSX. Checking.
2. Are you running inside a python3 virtual environment created using `python3 -m venv <path to venv>` and then activated with `source <path to venv>/bin/activate`? 

These two facets will help us narrow down the issue.

Thanks!

**Comment by sgoggins** [comment]
@jkgrmc : I did replicate this on OSX after doing a `brew update` and `brew upgrade` ... working on a patch.

**Comment by sgoggins** [comment]
@jkgrmc : For now, it seems that different libraries have introduced some new dependencies that do not currently work with `python@3.11` ... This sometimes happens with the most recent publication of python3.x ... The workaround for now is `python@3.10` and then `python3.10 -m venv ... ` to create your virtualenv. This will be a problem, for now, on any platform running python3.11 ... for now that's just OSX that has 3.11 as the default.

**Comment by sgoggins** [comment]
This is fixed via PR #2517
