### ISSUE TITLE
Augur front end not filling screen/folds up 

### ISSUE THREAD

**Issue by cdolfi** [chaoss/augur#2525]
![Screenshot 2023-09-11 at 12 48 58 PM](https://github.com/chaoss/augur/assets/47504866/ec625431-5ceb-4038-80ec-a5c651c18d11)
![Screenshot 2023-09-11 at 12 49 43 PM](https://github.com/chaoss/augur/assets/47504866/a82df49f-f63d-4a47-b299-ba82801a175a)

**Comment by sgoggins** [comment]
@cdolfi : Are the two screens above both in "100%" mode? Or is one higher than that? Or one lower than that? Trying to reproduce this.

**Comment by cdolfi** [comment]
@cdolfi What do you mean by "100%" mode?

**Comment by Ulincsys** [comment]
I believe @sgoggins was referring to your browser's scale factor for this domain.

I will look into this. In the meantime, can you reply with your screen resolution and display scale factor?

**Comment by cdolfi** [comment]
I think I am following. I tried this out on 3 different screens, all on the default full screen view with "100%" on zoom. On my 13in mac it looks normal when at full screen, any smaller and all of the attributes start colliding. On my 16in and my personal monitor on (basically) full screen it looks like the first image above

**Comment by sgoggins** [comment]
I think its important from talking to Cali that the top nav be the same as every other page, or similar.

**Comment by Ulincsys** [comment]
Fixed by #2689
