### ISSUE TITLE
ssl certificate is out of date for https

### ISSUE THREAD

**Issue by JamesKunstle** [chaoss/augur#2527]
![Screenshot 2023-09-19 at 10 02 48 AM](https://github.com/chaoss/augur/assets/52969093/46396724-bb96-4382-b7f5-f6f4fd940a56)

![image](https://github.com/chaoss/augur/assets/52969093/9c001036-70f2-4212-a34f-a1e813788617)

**Comment by sgoggins** [comment]
This is resolved.
