### ISSUE TITLE
BUG: pull_request_reviews incorrect pull_request_id

### ISSUE THREAD

**Issue by cdolfi** [chaoss/augur#2532]
In a case example looking at the augur repo, pull request reviews has pull_request_id all being for the same id except one. 

The results show currently that there are 1322 pull_request_reviews on https://github.com/chaoss/augur/pull/2506 (which does not have a review itself)

**Comment by sgoggins** [comment]
@cdolfi : We did repair a bug associated with this issue last month. I will check to see if the data on your instance is repaired.

**Comment by sgoggins** [comment]
This is fixed in the current code base, and the fix will address any previously mismapped data.
