### ISSUE TITLE
Broken API Endpoint to get REPO_ID given repo name and organization

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#2556]
Endpoint exists in documentation, however its not working. So, make it work.

**Comment by IsaacMilarky** [comment]
https://oss-augur.readthedocs.io/en/dev/rest-api/api.html#operation/Get%20Repo%20by%20Owner%20and%20Repo%20Name

**Comment by IsaacMilarky** [comment]
Here is the result when hitting ai.chaoss.io: https://ai.chaoss.io/api/unstable/owner/chaoss/repo/augur

**Comment by IsaacMilarky** [comment]
Fixed in #2572
