### ISSUE TITLE
Fix endpoint to get repos in a repo group

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#2557]
The repo group for these purposes is defined as the platform organization. 

Right now, this repo group API exists, but does not work.

**Comment by IsaacMilarky** [comment]
https://oss-augur.readthedocs.io/en/dev/rest-api/api.html#operation/Get%20Repos%20in%20Repo%20Group

**Comment by IsaacMilarky** [comment]
Here is the result when hitting ai.chaoss.io: https://ai.chaoss.io/api/unstable/repo-groups/1/repos

**Comment by IsaacMilarky** [comment]
Fixed in https://github.com/chaoss/augur/pull/2572
