### ISSUE TITLE
Require DCO sign-off for new commits

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/augur#258]
This issue is to activate [protobot/dco](https://github.com/apps/dco) (or similar bot) to check that all commits have a sign-off in this repository. 

The [CHAOSS Project Charter section 8.2.1](https://chaoss.community/about/charter/#user-content-8-intellectual-property-policy) requires that all contributions are signed-off. The CHAOSS project has been piloting the use of DCO sign-offs. Once contributors know how to do it, sign-offs are easy to do with little overhead. 

> For users of the git command line interface, a sign-off is accomplished with the `-s` as part of the commit command: `git commit -s -m 'This is a commit message'`
>
> For users of the GitHub interface, a sign-off is accomplished by writing `Signed-off-by: Your Name <YourName@example.org>` into the commit comment field. This can be automated by using a browser plugin like [scottrigby/dco-gh-ui](https://github.com/)

**To-Do for repo maintainers:** Please inform your contributors about DCO sign-offs and comment on this issue when your are ready for the DCO bot to be activated on this repository.

**Comment by sgoggins** [comment]
We have a pull request approved and ready to merge, but a few merge conflicts to resolve over the next couple days.

**Comment by sgoggins** [comment]
Fixed in pull request #270
