### ISSUE TITLE
Code Changes Lines metric API

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#2624]
The canonical definition is here: https://chaoss.community/?p=3591

**Comment by IsaacMilarky** [comment]
This metric is something that Remy and I want to use for gov metrics. It seems that it's not working and doesn't have a way to pass in a parameter.

Let me know if I can help with this issue and getting the endpoint to work.

Thanks!

**Comment by IsaacMilarky** [comment]
Total lines, blank lines, and comment lines are the specific desired metric endpoints.
