### ISSUE TITLE
Search bar in the header is not refreshing the charts

### ISSUE THREAD

**Issue by gabe-heim** [chaoss/augur#263]
**Describe the bug:**
If you already have a repo loaded and are looking at one of the tab's charts (GMD for example), and then you try to change the repo you have selected by typing in a new url in the search box in the header, the name shown at the top of the card will change, but the charts do not get updated unless you refresh the page.

**To Reproduce:**
1. Type in a repo url on the home page, "rails/rails" for example
2. Navigate to the GMD tab
3. Try to change the repo by typing a different url, "akka/akka" for example, in the search box in the header and hit enter

**Expected behavior:**
The charts will get updated when you change to a different repo url immediately, without having to refresh

**Desktop (please complete the following information):**
 - OS: macOS v10.13.6
 - Browser: Chrome v73.0.3683.103 (Official Build) (64-bit)

**Comment by tretrue** [comment]
@gabe-heim what branch is this? I'm currently in `tre` branch and the charts are updating just fine... I did notice that when I quickly changed from `rails/rails` to `akka/akka`, the charts didn't begin to request the `akka/akka` charts until after the `rails/rails` were fully loaded in, but as soon as it finished the request for pulling the `rails/rails` chart in, it quickly grabbed the `akka/akka` charts, without needing a page refresh or anything
