### ISSUE TITLE
404 localhost error on a fork from master

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#269]
**Describe the bug:**
I am receiving a 404 error on the first run of Augur, after a development installation. I am working off of the master branch of my own fork, [which is identical to chaoss/augur/master](https://github.com/chaoss/augur/compare/master...Nebrethar:master). I have changed nothing, but I did run into some weird NPM errors.

Side Note: I had some NPM failures. Brunch tries and fails to reinstall the NPM packages which might mean the frontend is just having trouble.

**To Reproduce:**
1. Install Augur at master, verbatim to the dev installation instructions.
2. run any version of `make install-dev` (with or without `sudo`, root user, etc)
3. See error

**Expected behavior:**
Augur homepage

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/56473145-8be6ad00-642c-11e9-8790-6e793dac3d95.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu subsystem on windows
 - Browser: Chrome 6x

**Additional context**
This exact build seems to have been working just days ago. I didn't change anything by my knowledge, but every time I reverted the app, vendor, etc they updated immediately, though there were no real updates to make.

**Comment by ccarterlandis** [comment]
`5555` is not a port Augur uses. What do `localhost:5000/api/unstable/` and `localhost:3333` display when running the `make dev` command? @Nebrethar

**Comment by Nebrethar** [comment]
None of those work either; I had `5555` in my config up to now because that's the only port I could get brunch to work on previously. I also tried changing to these ports in the config and no luck. Pictures of these are at the bottom.

This is a fresh install from master. 
I've also run into issues with the brunch build in the past... and they seem to trail back to NPM install

`localhost:5000`
![image](https://user-images.githubusercontent.com/34951354/56475499-afbaea80-644e-11e9-857d-dc261fd5aa31.png)


`localhost:5000/api/unstable/`
![image](https://user-images.githubusercontent.com/34951354/56475505-bb0e1600-644e-11e9-9b23-320f7832ae6d.png)

`localhost:3333`
![image](https://user-images.githubusercontent.com/34951354/56475523-f7417680-644e-11e9-87be-80290ecd5501.png)

**Comment by Nebrethar** [comment]
Semi-related, I have had an issue where the frontend only displays as a blank page and it seemed to fix itself after a few hours of messing with it. Not sure what I did for that one though.

**Comment by Nebrethar** [comment]
I figured out after letting the command `sudo make-dev` run for about four hours that it eventually compiled. Brunch had a note about installing missing NPM packages that I only saw after it was finished. 

My guess of the issue here is that brunch needed to get NPM packages that `sudo make install-dev` did not cover (a lot of them, apparently). That's my only idea on why it took 4 hours to compile. The dependency tree was massive, too.

**Comment by ccarterlandis** [comment]
I have not been able to replicate this error. Brunch does have to install a good amount of packages, but usually not enough that it should take 4 hours. Can you post the `frontend.log` file from the `logs/` directory after running `make dev`? Additionally, is it possible that something else on your system is using port `3333`? The backend is working just fine, it seems to be a frontend error of some sort which leads me to believe that @gabe-heim might be able to provide more direction on this than I can.

**Comment by Nebrethar** [comment]
I figured this out with @gabe-heim just recently. No matter what my server was set to, I've been running into a lot of problems using the port in augur.config.json.

For example, if I have port 5555 or 5000 in my augur.config.json and go to that port on localhost, it will work sometimes on that port but otherwise provide weird bugs and errors.

Gave helped me figure out that I need to set the port to 5555 and navigate to localhost:3333 and it worked. I haven't gotten nearly as many errors.
