### ISSUE TITLE
Apple Silicon Weirdness when launching through `docker compose`

### ISSUE THREAD

**Issue by GaryPWhite** [chaoss/augur#2724]
**Description:**
When using `docker compose --env-file ./environment.txt up` on an Apple Silicon chip (tested M1/M2) we notice output:
```
command not found: backend
```
Through my investigation, I've found that this likely refers to the last line of [init.sh](https://github.com/chaoss/augur/blob/main/docker/backend/init.sh#L22). changing "backend" to anything else confirms this.

I suspect this has something to do with [shell and exec form](https://docs.docker.com/reference/dockerfile/#shell-and-exec-form) but haven't found anything concrete -- so that could be a red herring.

**How to reproduce:**
1. Go to the base of this repository, on apple silicon chips
2. populate your `environment.txt` with some values (they don't need to be real, the app doesn't get far enough)
3. run `docker compose --env-file environment.txt up`
4. wait for failure

**Expected behavior:**
`docker compose ... up` should allow us to run the augur application.

**Screenshots**
N/A

**Log files**
Attach the relevant log files here. Server and installation logs can be found in the `logs/` directory in the root `augur/` directory, and the logs for each worker are stored in their respective directories. If the logs are pretty long (> 50ish lines or just use your best judgement) please use a Gist or a [pastebin](https://pastebin.com/). **These logs file are required if you would like help solving your issue.**

**Software versions:**
 - Augur: main branch
 - OS: `sw_vers`
 - Browser: N/A

**Comment by JamesKunstle** [comment]
Starting to look at this tm morning

**Comment by sgoggins** [comment]
@GaryPWhite : We are working on this still. :)

**Comment by JamesKunstle** [comment]
@GaryPWhite I can build and run Augur on M2 Pro without hitting that error
