### ISSUE TITLE
`augur.config.json` is not created by  `make install` or `augur config init`

### ISSUE THREAD

**Issue by Shotaro-Yoshinaga-sti** [chaoss/augur#2750]
**Description:**
`augur.config.json` is not created.

**How to reproduce:**
- Follow the [instructions](https://oss-augur.readthedocs.io/en/main/getting-started/installation.html) to `make install`
- Run `augur config init` with reference to [this](https://oss-augur.readthedocs.io/en/main/getting-started/command-line-interface/configure.html)

**Expected behavior:**
`augur.config.json` is created.

**Software versions:**
OS, Tools| Version
-- | --
Ubuntu | 22.04
PostgreSQL | 14.11
Python | 3.9
GO | 1.21.4
Radis | 7.2.4
RabbitMQ | 3.13.0
Augur | 0.63.0

**Comment by sgoggins** [comment]
The config currently is stored in the database and a db.config.json is created instead.  It sounds like we have some documentation that needs updating. Can you link to the docs you are looking at?

**Comment by ShotaroYoshinaga** [comment]
Updated docs and add links.

**Comment by ShotaroYoshinaga** [comment]
@sgoggins 
I was thinking of using [this](https://github.com/chaoss/augur-license).
If the config is stored in the database and db.config.json is created instead, does that mean it cannot be used?
