### ISSUE TITLE
Augur front end "Repo Tracker" tab name 

### ISSUE THREAD

**Issue by cdolfi** [chaoss/augur#2754]
Curious to open a discussion around naming of this tab. I feel like "Repo Tracker" is a pretty loaded term so curious if there is a specific reason to hold onto that vs changing it to something specifically descriptive to the tab contents

**Comment by Ulincsys** [comment]
The name for each of the tabs in the profile page was chosen ad hoc during development of the new layout. We weren't entirely sure what the content of each section would be, so I just chose generic titles to loosely group the functionality I expected to put there.
If you have particular feedback as to what you think would be a better name for this section given its current functionality, we welcome any input on the topic.

**Comment by cdolfi** [comment]
Maybe "Repo Groups" ?

**Comment by Ulincsys** [comment]
The name of the tab was changed to "My Repos" in #2783. Please let us know your feedback, and we can work more on this if need be. The changes are currently slated for the next release.
