### ISSUE TITLE
Clean up "Empty Noise" in default User Interface

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#276]
**Description**
Our initial design focused on a tab per CHAOSS working group. At this juncture, I think directly referencing defined metrics has greater utility than deriving the full user interface from the CHAOSS working group structure. Specifically: 

1) Empty tabs
2) Empty metrics 
3) Tabs that seem to be the same thing (GMD, Activity, and Git)

Its my view that design work presently underway will address these issues, but we should consider placing a higher priority on their implementation. Accordingly, I added a "critical" tag.

**Comment by sgoggins** [comment]
I think eliminating the GHTorrent Schema driven data from the evolution, activity and experimental tabs, combined with only showing graphs with data behind them in a "GHTorrent" part of the new UI will take care of this issue.

**Comment by gabe-heim** [comment]
The new front end addresses and solves this issue IMO
