### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by mhauru** [chaoss/augur#2764]
I just found Augur and have been trying it out. Much of the docs at https://oss-augur.readthedocs.io/en/main/ seem to be out of date. Given that the project seems to currently be in the middle of a new major release, does it make sense to send a PR fixing all sorts of small things in the docs, or is it all about to go through a rewrite anyway?

**Comment by sgoggins** [comment]
Any specifics you can share regarding what is out of date will be helpful.
