### ISSUE TITLE
augurlabs.io is dead/down

### ISSUE THREAD

**Issue by mhauru** [chaoss/augur#2765]
There's a link to https://augurlabs.io/ in the repo description text, but the link is dead. Not sure if the issue is that the site is temporarily down or that it's no longer active, but especially if the latter, the description should probably be updated.

**Comment by sgoggins** [comment]
Please join our slack org for notifications regarding CHAOSS SaaS software.

https://join.slack.com/t/chaoss-workspace/shared_invite/zt-289zxh6tu-3oQaFlutPFY039MjKpnWcA 

The #wg-augur-8knot channel is a good place to post.
