### ISSUE TITLE
machine_learning_phase undefined in start_tasks.py

### ISSUE THREAD

**Issue by mhauru** [chaoss/augur#2767]
The `machine_learning_phase` variable is referenced a few times in start_tasks.py, but it's undefined:
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/tasks/start_tasks.py#L144
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/tasks/start_tasks.py#L223
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/tasks/start_tasks.py#L260

Probably just missing an import.

**Comment by sgoggins** [comment]
@ABrain7710 : This goes to one of my questions. I found the same thing. Let's fix this when we can. @IsaacMilarky : If you have time to address that would also be great!
