### ISSUE TITLE
Hard-coded default repos

### ISSUE THREAD

**Issue by mhauru** [chaoss/augur#2771]
Several source files have hard-coded in them the default repos to get data for, that I assume are used for testing purposes. This makes it hard to start my own instance of Augur that would not download data for these repos immediately as it starts, but rather wait for me to tell it which repos I'm interested in.

I'm not sure I found all instances of this, but here are a few places where the example repos are hard-coded:

https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/application/schema/augur_full.sql#L4689
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/application/schema/alembic/versions/legacy/80.3-sample-data.sql#L1075
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/docker/database/augur-new-schema.sql#L5814
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/application/schema/repo_load_sample.csv

There may also be other hard-coded test/example cases, that aren't repos, that would probably be better kept in configuration files or as a part of the test suite. I spotted this one about contributors, but there may be others I missed.
https://github.com/chaoss/augur/blob/a786ac5a506ffac31931f40c2a58056b7c1f073c/augur/application/schema/augur_full.sql#L4360

**Comment by sgoggins** [comment]
@mhauru : This is certainly a test dataset included with Augur. We could possibly remove them, however my concern is that people starting up augur for the first time may not then know how to begin.

**Comment by mhauru** [comment]
Maybe they could be moved to configuration files outside of the main source code? Then by default a new instance of Augur would be configured with some repos, but severing that link and starting a "bare" instance would be as simple as changing the configuration files.

**Comment by sgoggins** [comment]
@mhauru ; This came up again in Slack. I'm reopening it ...
