### ISSUE TITLE
Installation script assumes egress port 53 is allowed.

### ISSUE THREAD

**Issue by ggolin** [chaoss/augur#2781]
Observed in v0.63.3 on a clean install with docker-compose.

[This check](https://github.com/chaoss/augur/blob/331b8e2b332117428deb3aa591d925bb6a58b239/augur/application/cli/__init__.py#L21C1-L21C53) attempts to connect to Google's DNS server. In a corporate setting accessing an external DNS server is not always allowed. This check fails in my case and the configuration never completes:
```bash
root@ba7968d86e9e:/augur# nc 8.8.8.8 53
Ncat: TIMEOUT.
```

**Comment by GaryPWhite** [comment]
may be resolved by #2782 -- using httpx to check if the outside internet (namely, chaoss.community) is available -- configurable with standard `_PROXY` variables.

**Comment by ggolin** [comment]
Thanks for taking a look at this. The linked PR will solve this problem. Locally I modified the code to try and resolve a hostname rather than attempting to connect to an external DNS server.
