### ISSUE TITLE
Trouble using public instances

### ISSUE THREAD

**Issue by alexey-milovidov** [chaoss/augur#2785]
**Description:**

I tried https://metrix.chaoss.io/ and https://ai.chaoss.io/

I cannot find my repository (https://github.com/ClickHouse/ClickHouse) in the suggest.
However, I found some other repositories with clickhouse strings, seemingly random.

When I select one of them, a very beautiful cube animation starts to show. It showed for multiple minutes, making the impression that the website did not work. Then it stops and the small phrase "Data Ready" appears.

Anyway, it is unclear how to use it after "Data Ready". When I switch to another tab, e.g., "repo overview", it shows the data for another repo, probably, "chaoss".

Also, the suggest looks rusty...
<img width="1146" alt="Screenshot_20240509_173751" src="https://github.com/chaoss/augur/assets/18581488/00633911-b0e6-4819-b828-6d4275e51d9f">
My browser is Chromium on Linux.

By the way, it is not possible to close suggest from this state.

**How to reproduce:**
1. Go to the public service by a link.
2. Click on suggest.

PS. This is unsolicited, unfiltered usability feedback. Sorry if it was not appropriate. Feel free to close if the report does not fit here.

**Comment by sgoggins** [comment]
@alexey-milovidov : Did you add clickhouse/clickhouse to collection at https://ai.chaoss.io? The site is not for all repos. We need somebody to tell us which ones are of interest. :)
