### ISSUE TITLE
Public augur database- rust pull request messsages not populating 

### ISSUE THREAD

**Issue by cdolfi** [chaoss/augur#2786]
there is only 30,000 messages with the last one being almost 10 years ago - https://github.com/rust-lang/rust

**Comment by sgoggins** [comment]
@cdolfi : We resolved this issue in an upcoming release. There are anomalous repositories (i.e. 0.1% or less of all repos we are tracking in any instance of Augur) with so many messages that we don't catch them on the message API. The workaround is in place and tested. I expect a release soon!

**Comment by cdolfi** [comment]
Just checked out the impacted graphs, they look great!
