### ISSUE TITLE
What should be possible after docker compose up

### ISSUE THREAD

**Issue by JustinGOSSES** [chaoss/augur#2822]
I've been able to get the augur docker containers up and running using the Docker quick start instructions on windows as described on this page https://oss-augur.readthedocs.io/en/main/docker/quick-start.html. However, it isn't clear what to do after running `docker compose up`. 

I had to use the `docker-compose-externalDB.yml` file instead of the default `docker-compose.yml` file, because I already have postgresql running locally for another project and didn't want to disable it. Docker apparently won't let me start Postgresql in Docker if there's another one running as the port is reserved. 

I've gotten to a point where Docker desktop shows that rabbitmq-1, redis-1, and augur-1 containers are all up and running without error after running the command ` docker compose -f docker-compose-externalDB.yml up`. What's next? The docs don't clarify what do next in the docker quick start scenario. I assumed either augur CLI would be installed in that augur-1 container, it wasn't, or I could access a front-end at http://localhost:5002/ or http://localhost:8080 but that isn't the case either. 

If someone could point me in the direction of what next steps should be possible after `docker compose up`, that would help me debug as I'm not getting any errors. Thank you.

**Comment by sgoggins** [comment]
@JustinGOSSES : OK. These are fair concerns or ambiguities. @Ulincsys is working on an installation wizard that may be an alternative to Docker. We will make updates in the next 2 weeks to resolve this issue.

**Comment by JustinGOSSES** [comment]
Thanks for the response. Will check out the changes
