### ISSUE TITLE
Request Access to Public Instance of GHTorrent

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#302]
If you would like to request access to the public instance of GHTorrent that we use, please post a **COMMENT** here, stating: 
1. The reason
2. Your institutional affiliation
3. Whether or not you will be using the instance for anything other than Augur (we are not categorically opposed to this, but we may give you an account that works better for those purposes)
4. Tag @sgoggins  or @gabe-heim  or @ccarterlandis or @parthsharma2 or @bing0n3

**Comment by Nebrethar** [comment]
@sgoggins 
This option needs more visibility; it is not included in the dev install doc. The master install doc does not provide enough exposure to this option either.

**Comment by Prajwal7842** [comment]
Hi, I am new to this project and would like to contribute to it. I am trying to set up this project "Augur" on my local machine. So I followed the instructions and am posting this comment.
I am currently a student.
I won't be using it anywhere else other than Augur.
@sgoggins

**Comment by sgoggins** [comment]
@Prajwal7842 : Try installing from the dev branch. `make install`. Its MUCH better than it was.
