### ISSUE TITLE
Worker Update to Capture Additional Issue Metadata

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#321]
To speed up our integrity checking via the Housekeeper process, the following pieces of data are requested from the GitHub Issue Worker. These are fields already added to the test schema, and we would like them populated by the next version of the worker. 

# Columns Added to Issue Related Schema to Incorporate into GitHub Worker

## issue_msg_ref:
	- COMMENT ON COLUMN "augur_data"."issue_msg_ref"."issue_msg_ref_src_comment_id" IS 'This ID comes from the source. In the case of GitHub, it is the id that is the first field returned from the issue comments API';
	- COMMENT ON COLUMN "augur_data"."issue_msg_ref"."issue_msg_ref_src_node_id" IS 'This character based identifier comes from the source. In the case of GitHub, it is the id that is the first field returned from the issue comments API';

## issue_events : 
	- COMMENT ON COLUMN "augur_data"."issue_events"."issue_event_id" IS 'This ID comes from the source. In the case of GitHub, it is the id that is the first field returned from the issue events API';
   
## issue_labels: 
    - COMMENT ON COLUMN "public"."issue_labels"."label_src_id" IS 'This ID comes from the source. In the case of GitHub, it is the id that is the first field returned from the issue events API JSON subsection for issues.';
    - COMMENT ON COLUMN "public"."issue_labels"."label_src_id" IS 'This character based identifier (node) comes from the source. In the case of GitHub, it is the id that is the second field returned from the issue events API JSON subsection for issues. ';

## issue_assignees: 
    - COMMENT ON COLUMN "augur_data"."issue_assignees"."issue_assignee_src_id" IS 'This ID comes from the source. In the case of GitHub, it is the id that is the first field returned from the issue events API in the issue_assignees embedded JSON object. We may discover it is an ID for the person themselves; but my hypothesis is that its not.';
    - COMMENT ON COLUMN "augur_data"."issue_assignees"."issue_assignee_src_node" IS 'This character based identifier comes from the source. In the case of GitHub, it is the id that is the second field returned from the issue events API in the issue_assignees embedded JSON object. We may discover it is an ID for the person themselves; but my hypothesis is that its not.';

## commit_comment_ref (Currently not Populated)
    - COMMENT ON COLUMN "commit_comment_ref"."cmt_comment_src_id" IS 'For data provenance, we store the source ID if it exists. ';
    - COMMENT ON COLUMN "commit_comment_ref"."commit_comment_src_node_id" IS 'For data provenance, we store the source node ID if it exists. ';

**Comment by sgoggins** [comment]
Maybe this is something @ortonpaul could jump back in with? Just a thought. Never interpret anything I say as an order. We'd all be subjects of the crown if people started doing that. 😂

**Comment by gabe-heim** [comment]
@sgoggins there is a small inconsistency in the naming, specifically that all the node_id columns end in `node_id` while the one for `issue_assignees` only ends in `node`. Small detail that doesn't matter too much but thought I'd mention. Updates to include the new columns with their current names is added in e32e97e, while the columns for `issue_msg_ref` were added in a previous commit. We do not have any worker able to populate the `commit_comment_ref` table so I could not add this but I will close the issue since we will add these columns when this model is able to be filled.
