### ISSUE TITLE
Organization History

### ISSUE THREAD

**Issue by abuhman** [chaoss/augur#34]
organizationHistory folder is now added under dev branch.  It contains the pythonBlameHistoryTree.py file, which gets the percentage of a repo written by different organizations at the time of each commit.  If no organizations are output for a certain commit, or the percentage adds up to less than 100%, this is expected because not all users are a member of an organization.

However, currently the way users are matched to organizations, it is possible to have a user be a member of multiple organizations (leading to a potential sum of more than 100% of the repo, and/or other misleading statistics).

Data for the percentage of the file comes from Git.  The Git Blame command allows the user to view which user most recently changed each line of code in a file.  By looping through every commit and every file in the repo, we can get a percentage of the repo written by each user over the history of the repo.

The user's organization is obtained through querying the ghTorrent database using the user's email address (in my local case, MSR14).

**Comment by sgoggins** [comment]
i think the next step is to make this available for visualization on the front end, right?
