### ISSUE TITLE
Simplified Installation for Tech Scenario 1: Local

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#361]
**Is your feature request related to a problem? If so, please describe the problem:**
Augur has two main parts, and two main technical use scenarios:
Part 1: Back End
Part 2: Front End
Tech Scenario 1: New user wanting to try Augur locally
Tech Scenario 2: Organization wanting to deploy Augur on a server. 

**Describe the solution you'd like:**
A simple script for local installation. Components include: 
1. Python 3.7
2. Pip3
3. Virtualenv
4. Create VirtualENV
5. Path execution depending on user answers to questions. 

**Describe alternatives you've considered:**
Path Execution A: (Database)
1. Do you have access to a Postgres 10 or 11 installation, with administrative privileges where you want to install the Augur database? 
2. If "no", Do you have access to a Postgres 10 or 11 database where you have administrative privileges where you want to install the Augur database? 
3. If "no", Do you want to install a Postgres database locally? (Answer is "yes", or we say, "You will need a postgres database to install Augur, are you sure you do not have access to one or wish to install one?" 
4. Either stop, or offer user each of the 3 choices again

Path Execution B: (Repository Implementation): 
1. How would you like to configure your .git Repositories: 
(a) Would you like to install a sample of fully populated Augur analysis of 25 repositories so you can explore augur? 
(b) Attach Augur to an existing database you or somebody else populated? 
(c) Would you like to load repositories from a `.csv` file with `repo_group` (a number), and `repo_git` (a full path to where we clone the repository from) headers? 
(c) Would you like to list repositories and groups from a web page we launch for you? (Or, this could be, "Would you like to create your repository list later?)

Path Execution C: (Augur Configuration): 
1. Automatically run `util/make-config.py`

Path Execution D: (Starting Augur)
1. Would you like to start Augur's back end and make our API available on the port you specified (don't worry, we will print your configuration choices for you at the end if you forgot the port)? 
2. These are the Augur data collection workers you can start: 
(a) Git Repository Analysis
(b) Issue Tracker collection
(c) Pull Request collection
(d) Repository metadata, time series collection (forks, stars, watchers, etc.)
(e) Pull request Collection
(f) Top insight artificial intelligence generation
(g) Slack, email or other instant message notification for insights

Path Execution E: 
1. Would you like to configure Augur's front end? 
2. Would you like to serve Augur's front end using 
(a) A development server 
(b) nginx 

... then proceed to separate script for front end installation, or add here. This issue can be closed with back end installation complete. 

**Additional context:**
 - Ubuntu
 - Fedora
 - Mac OSX

**Comment by sgoggins** [comment]
A first draft is in `augurinstall.sh` in the root directory. 
@parthsharma2 's  program to generate an `augur.config.json` needs to have the worker ports added as defaults. For the new user running locally, we do not need to prompt for these. `augur_localstart.sh` and `augurkill.sh` in the root directory are also in progress.  Getting the database configured and started with repositories is the biggest "next thing" ... this is kind of started in a very "hacky" way in `docs/setup/augur-get-data.py`, which will iteratively gather repos from a github organization. Refactoring this will provide a nice feature .. @ccarterlandis has worked on this before.

**Comment by ccarterlandis** [comment]
@sgoggins I'm slightly confused about the wording of this section:

> 1. Do you have access to a Postgres 10 or 11 installation, with administrative privileges where you want to install the Augur database?
> 2. If "no", Do you have access to a Postgres 10 or 11 database where you have administrative privileges where you want to install the Augur database?

I'm confused about the difference between an 'installation' and 'database' in this context, can you clarify?

**Comment by ccarterlandis** [comment]
Additionally, I feel like this section from Path B
>  (b) Attach Augur to an existing database you or somebody else populated?

more aptly belongs under the Path A with the configuration of the database. If they have a database already populated, we can skip Path B entirely. Thoughts? @sgoggins
