### ISSUE TITLE
Sample data link on dev install is broken

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#363]
**Describe the bug:**
I noticed that the sample data link is a 404, under the heading "create the database schema". 

**To Reproduce:**
1. Go to https://github.com/chaoss/augur/blob/dev/docs/setup/installing-augur.md
2. Click on nekocase.augurlabs.io/augur.psql.bak.gz
(real link https://github.com/chaoss/augur/blob/dev/docs/setup/nekocase.augurlabs.io/augur.psql.bak.gz)

**Expected behavior:**
Navigate to startup copy of data

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 76

**Comment by Nebrethar** [comment]
Note: Using the link verbatim (nekocase.augurlabs.io/augur.psql.bak.gz) also ends in a 404

**Comment by sgoggins** [comment]
The sample data is now part of the installation script!  Thanks, @ccarterlandis !!!
