### ISSUE TITLE
Git Repo_Group Page Operational

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#367]
**Is your feature request related to a problem? If so, please describe the problem:**
The repo groups page I would like to see some basic info on, even if its just a list of repo groups that takes me to a list of repos in that group.

**Comment by gabe-heim** [comment]
@ElitaNelson @ortonpaul Hey guys this may be a good thing for one or both of you to work on that helps give you a sense of how the endpoints and data handling works on the frontend. Looking at `Repos.vue` would be a great reference for how to do this, as that component essentially does the same thing but for repos, I'm always available on slack if you have questions
