### ISSUE TITLE
No first-page metrics visualizations on dev branch

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#370]
**Describe the bug:**
I've noticed using the latest version of `dev` that the main metrics page is not loading completely . I've only noticed it on zephyr repositories but it happens every time there.

**To Reproduce:**
1. Go to Repos page
2. Click on any repo prefixed with `zephyrproject-rtos`

**Expected behavior:**
I expected the metrics page to load like normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/64084144-e3a3f780-cced-11e9-9548-9f2972425523.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 76

**Additional context**
**Here is the log on error.**
![image](https://user-images.githubusercontent.com/34951354/64084203-7775c380-ccee-11e9-97ca-a068b2be1f63.png)

**Comment by Nebrethar** [comment]
It is happening to my dashboard for more than just zephyr. Confirmed on a clean pull of dev.
**Dashboard:**
https://imgur.com/a/hm2YHB2

**Terminals (No signs of issues):**
https://imgur.com/a/W8E1Gls

**Comment by Nebrethar** [comment]
I can't find any changes related to the issue itself, but it seems to be that some vue files (such as tickchart and horizontalbarchart) can't find window.vegaEmbed

@gabe-heim inviting you to this one because it seems that you've worked the most on these files.

@sgoggins I can't move forward until we get **this** and **pr #365** taken care of.

**Comment by gabe-heim** [comment]
This should be fixed in 1719c45, let me know if you are still having issues @Nebrethar

**Comment by Nebrethar** [comment]
The metrics page still looks like this:
https://i.imgur.com/CGdTMcN.png

Text for "lines of code" is very small and the visualization for it does not load.

Here is a copy of my console from the page. It looks like it is rejecting something in "lines of code" with the yellow text.
```
![image](https://user-images.githubusercontent.com/34951354/64212300-88e5d980-ce6e-11e9-99ec-86f39212cebb.png)
```

**Comment by sgoggins** [comment]
I am checking with @gabe-heim about where we have the fix deployed. Primarily to make sure I do useful things. :)

**Comment by Nebrethar** [comment]
Second discussion moved to #376
