### ISSUE TITLE
Can these project work on privatization gitlab?

### ISSUE THREAD

**Issue by ericshanda** [chaoss/augur#371]
We use privatization gitlab inside my company. Can augur work on the gitlab?

**Comment by sgoggins** [comment]
I think you would need to define "privatization" a little more, but if you have credentials to clone a .git repository from .gitlab, which you can configure within the shell that you run our commit collection 'facade_worker' on, then you can get commits. Do you also have issues and the GitLab equivalent of Pull Requests that you want to track?
