### ISSUE TITLE
Metrics page Loading Issues

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#376]
Migrated from #370 

The metrics page looks like this:
https://i.imgur.com/CGdTMcN.png

Text for "lines of code" is very small and the visualization for it does not load.

Here is a copy of my console from the page. It looks like it is rejecting something in "lines of code".
![image](https://user-images.githubusercontent.com/34951354/64212366-bc286880-ce6e-11e9-9ea7-089648714e9a.png)

**Comment by sgoggins** [comment]
I think @gabe-heim fixed this.  Can you confirm @Nebrethar ?

**Comment by Nebrethar** [comment]
It is not fixed on my computer with a clean install, but It seems to be fixed elsewhere. I will close this now.
