### ISSUE TITLE
Augur Single-Platform Target for Developers?

### ISSUE THREAD

**Issue by andyl** [chaoss/augur#379]
This is more of a discussion than a bug...

# Developer Platform

While going thru the Augur installation docco, I see references to installing on Mac, on Ubuntu, on Fedora, on Windows...  

IMHO supporting multiple platforms leads to extra documentation complexity, extra testing, more opportunities for failure. It would simplify things greatly if there were just a single developer installation target.  In this way, the limited developer resources could be spent building features, rather than on platform support.

My proposal is to let Ubuntu 18.04 be the target platform for developers, because it has IMO the greatest  market share, and is simplest to set up a VirtualBox devsystem on Windows and Mac.

If this proposal is acceptable,  the only item that is impacted would be documentation.  We would simply streamline the documentation to only describe installation on Ubuntu.  If people want to install on other platforms, they would be on their own.

# Production Platform

In my view, Production instances would be deployed as Docker containers, and any platform that supports Docker would be supported.

# Decision and Possible Follow-on Action

If you all are in support of this proposal, then I will submit documentation PR's to streamline the installation docs to refer only to Ubuntu 18.04.

Thanks for your consideration and let me know your views...

**Comment by sgoggins** [comment]
Hi @andyl : We are really focused on making the new developer experience accessible to everyone. Virtualbox has proven kind of unstable with Augur. I think the Docker container could possibly work for some, but we are not sure about abandoning instructions for Fedora and Mac.  Windows is super hard. It is so completely different in every way. Even their Ubuntu distro/VM/Shell systems do things differently and do not support ordinary commands we rely on ... If you have ideas for windows that would help. They are the one community that has proven too expensive in terms of time to actively support.

**Comment by andyl** [comment]
@sgoggins: fair enough and thanks for the clarification.  That being the case: would you be open to segregating the install instructions into separate platform-specific sections?  In this way a potential author (like me) could focus on a specific platform.  In this case, I'm thinking that a 'platform' is a combination of hostOS plus a virtualization layer.  It's an interesting organization challenge because there are many possible combinations of host OS and virtualization.

There could be a high-level README showing which platforms are supported:

| Platform Name | Target Use | HostOS | Virtualization Platform | Lead |
| --- | --- | --- | --- | --- |
| UbuntuCore | Development | Ubuntu18.04 | NA | andyl |
| UbuntuDocker | Production | Ubuntu18.04 | Docker | sgoggins |
| UbuntuVbox | Production |  Ubuntu18.04 | VirtualBox | ccarterlandis |
| MacDev | Development | MacOS 10 | NA | gabe-heim |

And the docco with support files could be organized under separate directories:

```
install-docs\
|- README.md
|- MacDev\
    |- Install_Mac_Dev.md
    |- mac_sample_config_file.ini
|- UbuntuCore\
    |- Install_Ubuntu_Core.md
    |- bin\
        |- install_database.sh
        |- setup_python.sh
```

Let me know if you find this appealing or not.
