### ISSUE TITLE
Separate Identity Resolution Into its own worker

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#386]
**Is your feature request related to a problem? If so, please describe the problem:**
We resolve identity in the Facade_Worker and the Git_Hub worker, trying to ensure the same people are included in only one row, and identifying aliases. 

Under initial data load conditions, it becomes a kind of tie breaking order of execution contest that works, but results in extra API calls. 

It is more optimal to have the identity resolution be its own worker, that is run only after the other workers that gather identity information have completed their initial runs. This way, redundancy is avoided.

**Comment by ccarterlandis** [comment]
Closing since this is an old issue, and also because @gabe-heim built a `contributor_worker` to do this very task!
