### ISSUE TITLE
On the fly aggregation of "metric sets" by a user selected set of repositories

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#387]
**Is your feature request related to a problem? If so, please describe the problem:**
Using CHAOSS as an example, the working group repositories function one way, while Augur and Grimoirelab function in different ways. In discussion with scientific software communities we learned that this kind of "filtering within a set" for "aggregation by type" is a desired endpoint and possibly front end. 

**Describe the solution you'd like:**
1. Dynamic summarization of a set of metric endpoints for a user defined set of repositories.
2. Ability to dump a .csv or JSON file with that data. 

**Describe alternatives you've considered:**
Ad hoc DB Queries. 

**Additional context:**

**Comment by Nebrethar** [comment]
@sgoggins  Any updates on this enhancement?

**Comment by ccarterlandis** [comment]
I'm not really sure what this issue is outlining here. Is this essentially being able to get the results of a large set of metrics for a given group of repos with a single API endpoint? Additionally, is this still relevant/something we want?

**Comment by sgoggins** [comment]
We have solved this with the new chaoss/augur-community-reports project.
