### ISSUE TITLE
[dev] Empty "Default", "Seniate" repo groups

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#396]
**Describe the bug:**
If i click on the repo group `default`, i get an empty data set.

**To Reproduce:**
1. Go to `http://augur.osshealth.io/`
2. Click on `Default` repo group
4. See empty box

**Expected behavior:**
I expected some data to be present.

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/65979446-e9027800-e43a-11e9-80df-4d35d074921e.png)

**Desktop (please complete the following information):**
 - Browser: chrome 76

**Additional context**
I am using `http://augur.osshealth.io/`

**Comment by Nebrethar** [comment]
It looks like the repo group [Seniate](http://augur.osshealth.io/group/Senaite/overview) is empty too.

**Comment by ccarterlandis** [comment]
We are okay with this for now, as these are supposed to be empty. We know it's not ideal but we have a long term solution in place to target this.
