### ISSUE TITLE
[dev] Can compare repo-group to single repo (broken)

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#400]
**Describe the bug:**
I am able to compare a repo to a repo group. To reproduce this, you must come from the augur repo-groups page and click on a repo group. The next page will have single-repo comparison available.

**To Reproduce:**
1. Go to http://augur.osshealth.io/
2. Click on a repo-group
3. Select a comparison
4. See broken page

**Expected behavior:**
I didn't expect the comparison box to be present there in the first place

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/66071662-29d0be80-e519-11e9-8b23-9839d7e2c29c.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 76

**Additional context**
This process works as expected when I reload a repo-group page, and try the same thing (instead of clicking to navigate to it). At this point I am able to compare repo-groups.

**Comment by ccarterlandis** [comment]
There's no expectation that we should be able to compare repo groups, as at that point the information would be so diffused that it would be meaningless. @gabe-heim @michaelwoodruffdev can you take a look into what's causing this?

**Comment by sgoggins** [comment]
This is in progress and will be released soon.

**Comment by sgoggins** [comment]
I think we just need to disable the "apply" button if there is not a repository selected. Don't let people choose "apply" for a group only. @michaelwoodruffdev  / @gabe-heim : What do you think?

**Comment by ccarterlandis** [comment]
I can't recreate as of Augur v0.12.0. Closing
