### ISSUE TITLE
Axis of chart cut off at top

### ISSUE THREAD

**Issue by ElitaNelson** [chaoss/augur#401]
On the Insights page, the axis of the charts is cut off at the top, when it reaches the edge of the container, see screenshot below:
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/43044423/66140574-f8fb9280-e5c7-11e9-8ec4-8b8a6523d308.png">

**Comment by Nebrethar** [comment]
I see that this is fixed, but I found a related problem. I will refer to it in another issue.

@ElitaNelson Can we close?
