### ISSUE TITLE
Getting ready to run augur on a windows 10 PC (Part 1: The install)

### ISSUE THREAD

**Issue by yDraigRP** [chaoss/augur#403]
Hopefully this will follow the instructions at
https://oss-augur.readthedocs.io/en/osd-2019/installation.html

**Prerequisites:**

1) Install python 3.6+
2) Install PyCharm
3) Install GnuMake (or use Visual Studio if you have it)
4) Make sure your path has the Python and Python scripts directory
5) Add an environment variable for HOME = %USERPROFILE%
6) Install node/npm
7) Install @vue\cli
8) Enable bash (https://stackoverflow.com/questions/36352627/how-to-enable-bash-in-windows-10-developer-preview)
	

The Python installation instructions can be found here:
https://timmyreilly.azurewebsites.net/python-pip-virtualenv-installation-on-windows/

Instructions on how to use mkvirtualenv can be found here:
https://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html

Back to the instructions
0: Clone the repository using the Git GUI and check out the correct branch/version

For Visual Studio
=================
0: Start up a developer command prompt

1: Create a virtual environment: mkvirtualenv Augur_env
	(This creates it at C:\Users\<username>\.virtualenvs\augur_env
	Create a directory where you want to link the virtual directory to and cd into it e.g.
	C:\Users\<username>\Augur_env
	Activate the virtual environment:
	setprojectdir .
	
Note: if you already have the environment then the creation won't work and you need to type workon Augur_env
	
2: Start the installation process
	a) cd into the GIT directory (e.g. C:\GIT\CHAOSS)
	b) type nmake install
	c) go grab a coffee whilst the installation happens
	d) don't choose the webpage option for installing the credentials

3: Run Augur_env => to be continued

**Comment by yDraigRP** [comment]
I forgot that I also had to edit the Makefile slightly.  

[Makefile ,txt](https://github.com/chaoss/augur/files/3687748/Makefile.txt)

**Comment by ccarterlandis** [comment]
#480 has a more up to date version of these instructions. Closing
