### ISSUE TITLE
Frontend does not compile on dev branch

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#406]
**Describe the bug:**
 ERROR  Failed to compile with 17 errors                                                                                                                                              10:13:20 PM

 ERROR  Failed to compile with 17 errors                                                                                                                                              10:13:20 PM

 error  in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/axis.d.ts

ERROR in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/axis.d.ts
5:47 Type 'BaseAxis' is not generic.
    3 | import { Guide, GuideEncodingEntry, VlOnlyGuideConfig } from './guide';
    4 | import { LayoutAlign } from './vega.schema';
  > 5 | declare type BaseAxisNoSignals = AxisMixins & BaseAxis<number, number, boolean, number | boolean, string, Color, FontWeight, FontStyle, Align, TextBaseline, LayoutAlign, LabelOverlap, number[], TitleAnchor>;
      |                                               ^
    6 | declare type VgAxisConfigNoSignals = BaseAxisNoSignals;
    7 | interface AxisMixins {
    8 |     /**

 error  in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/axis.d.ts

ERROR in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/axis.d.ts
119:63 A type predicate's type must be assignable to its parameter's type.
  Type 'string | number' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
    117 |     title?: GuideEncodingEntry;
    118 | }
  > 119 | export declare function isAxisProperty(prop: string): prop is keyof Axis;
        |                                                               ^
    120 | export declare const VG_AXIS_PROPERTIES: ("values" | "orient" | "titleAngle" | "titleAnchor" | "titleAlign" | "titleBaseline" | "titleColor" | "titleFont" | "titleFontSize" | "titleFontStyle" | "titleFontWeight" | "titleLimit" | "titlePadding" | "labels" | "labelAlign" | "labelAngle" | "labelColor" | "labelFont" | "labelFontSize" | "labelFontStyle" | "labelLimit" | "labelPadding" | "format" | "formatType" | "offset" | "zindex" | "encode" | "domain" | "title" | "scale" | "labelOverlap" | "titleOpacity" | "labelBaseline" | "labelFontWeight" | "labelOpacity" | "labelSeparation" | "ticks" | "grid" | "labelFlush" | "minExtent" | "maxExtent" | "bandPosition" | "titleX" | "titleY" | "domainDash" | "domainDashOffset" | "domainColor" | "domainOpacity" | "domainWidth" | "tickColor" | "tickDash" | "tickDashOffset" | "tickExtra" | "tickOffset" | "tickOpacity" | "tickRound" | "tickSize" | "tickWidth" | "gridColor" | "gridDash" | "gridDashOffset" | "gridOpacity" | "gridWidth" | "labelBound" | "labelFlushOffset" | "gridScale" | "position" | "tickCount" | "tickMinStep")[];
    121 | export declare const AXIS_PROPERTIES: ("values" | "orient" | "titleAngle" | "titleAnchor" | "titleAlign" | "titleBaseline" | "titleColor" | "titleFont" | "titleFontSize" | "titleFontStyle" | "titleFontWeight" | "titleLimit" | "titlePadding" | "labels" | "labelAlign" | "labelAngle" | "labelColor" | "labelFont" | "labelFontSize" | "labelFontStyle" | "labelLimit" | "labelPadding" | "format" | "formatType" | "offset" | "zindex" | "encoding" | "domain" | "title" | "labelOverlap" | "titleOpacity" | "labelBaseline" | "labelFontWeight" | "labelOpacity" | "labelSeparation" | "ticks" | "grid" | "labelFlush" | "minExtent" | "maxExtent" | "bandPosition" | "titleX" | "titleY" | "domainDash" | "domainDashOffset" | "domainColor" | "domainOpacity" | "domainWidth" | "tickColor" | "tickDash" | "tickDashOffset" | "tickExtra" | "tickOffset" | "tickOpacity" | "tickRound" | "tickSize" | "tickWidth" | "gridColor" | "gridDash" | "gridDashOffset" | "gridOpacity" | "gridWidth" | "labelBound" | "labelFlushOffset" | "position" | "tickCount" | "tickMinStep")[];
    122 | export interface AxisConfigMixins {

 error  in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/legend.d.ts

ERROR in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/legend.d.ts
5:71 Type 'LegendConfig' is not generic.
    3 | import { Guide, GuideEncodingEntry, VlOnlyGuideConfig } from './guide';
    4 | import { LayoutAlign } from './vega.schema';
  > 5 | export declare type LegendConfig = LegendMixins & VlOnlyGuideConfig & VgLegendConfig<number, number, string, Color, FontWeight, FontStyle, Align, TextBaseline, LayoutAlign, LabelOverlap, SymbolShape, number[], Orient, TitleAnchor, LegendOrient> & {
      |                                                                       ^
    6 |     /**
    7 |      * Max legend length for a vertical gradient when `config.legend.gradientLength` is undefined.
    8 |      *

 error  in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/legend.d.ts

ERROR in /home/sean/github/CHAOSS/augur/frontend/node_modules/vega-lite/build/src/legend.d.ts
46:33 Type 'BaseLegend' is not generic.
    44 |  * Properties of a legend or boolean flag for determining whether to show it.
    45 |  */
  > 46 | export interface Legend extends BaseLegend<number, number, string, Color, FontWeight, FontStyle, Align, TextBaseline, LayoutAlign, LabelOverlap, SymbolShape, number[], Orient, TitleAnchor, LegendOrient>, LegendMixins, Guide {
       |                                 ^
    47 |     /**
    48 |      * Mark definitions for custom legend encoding.
    49 |      *

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
96:29 Property 'field' does not exist on type 'PieChart'.
    94 |             {
    95 |               "type": "pie",
  > 96 |               "field": this.field,
       |                             ^
    97 |               "startAngle": {"signal": "startAngle"},
    98 |               "endAngle": {"signal": "endAngle"},
    99 |               "sort": {"signal": "sort"}

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
131:53 Property 'field' does not exist on type 'PieChart'.
    129 |           "name": "r",
    130 |           "type": "sqrt",
  > 131 |           "domain": {"data": "table", "field": this.field},
        |                                                     ^
    132 |           "zero": true,
    133 |           "range": [20, 100]
    134 |         }

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
163:52 Property 'field' does not exist on type 'PieChart'.
    161 |             "x": {"field": {"group": "width"}, "mult": 0.5},
    162 |             "y": {"field": {"group": "height"}, "mult": 0.5},
  > 163 |             "radius": {"scale": "r", "field": this.field, "offset": 8},
        |                                                    ^
    164 |             "theta": {"signal": "(datum.startAngle + datum.endAngle)/2"},
    165 |             "fill": {"value": "#030"},
    166 |             "align": {"value": "center"},

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
168:36 Property 'field' does not exist on type 'PieChart'.
    166 |             "align": {"value": "center"},
    167 |             "baseline": {"value": "middle"},
  > 168 |             "text": {"field": this.field}
        |                                    ^
    169 |           }
    170 |         }
    171 |       ]

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
175:24 Parameter 'data' implicitly has an 'any' type.
    173 | 
    174 |     //define function that does any operation needed on data before sending it to the chart
  > 175 |     let processData = (data) => {
        |                        ^
    176 | 
    177 |       console.log("PIECHART data",data)
    178 | 

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
191:15 Property 'data' does not exist on type 'PieChart'. Did you mean '$data'?
    189 | 
    190 |     //condition handler to retrieve data if needed and call processData with it
  > 191 |     if (!this.data) {
        |               ^
    192 |       // hitting endpoint
    193 |       this.base[this.source]().then((data: any) => {
    194 |         //data handler (what gets returned)

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
201:24 Property 'data' does not exist on type 'PieChart'. Did you mean '$data'?
    199 |       })
    200 |     } else {
  > 201 |       processData(this.data)
        |                        ^
    202 |     }
    203 | 
    204 |     

 error  in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/components/charts/PieChart.vue
214:31 Property 'field' does not exist on type 'PieChart'.
    212 |     //,tooltip: {theme: 'dark'}
    213 |     console.log("piechart", JSON.stringify(config))
  > 214 |     vegaEmbed('#chart' + this.field, config, {actions: false}) 
        |                               ^
    215 |   }
    216 | 
    217 |   mounted () {

 error  in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue
253:11 Parameter 'metric' implicitly has an 'any' type.
    251 |   addRepoGroup!:any;
    252 | 
  > 253 |   getHex (metric) {
        |           ^
    254 |     return color_mapping[highest[idx].ri_metric].hex || '#FFC107'
    255 |   }
    256 |   // 'created' lifecycle hook

 error  in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue
254:12 Cannot find name 'color_mapping'. Did you mean the instance member 'this.color_mapping'?
    252 | 
    253 |   getHex (metric) {
  > 254 |     return color_mapping[highest[idx].ri_metric].hex || '#FFC107'
        |            ^
    255 |   }
    256 |   // 'created' lifecycle hook
    257 |   // Gets ran on component initialization, data collection should be handled here

 error  in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue
254:26 Cannot find name 'highest'. Did you mean the instance member 'this.highest'?
    252 | 
    253 |   getHex (metric) {
  > 254 |     return color_mapping[highest[idx].ri_metric].hex || '#FFC107'
        |                          ^
    255 |   }
    256 |   // 'created' lifecycle hook
    257 |   // Gets ran on component initialization, data collection should be handled here

 error  in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue
254:34 Cannot find name 'idx'.
    252 | 
    253 |   getHex (metric) {
  > 254 |     return color_mapping[highest[idx].ri_metric].hex || '#FFC107'
        |                                  ^
    255 |   }
    256 |   // 'created' lifecycle hook
    257 |   // Gets ran on component initialization, data collection should be handled here

 error  in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue

ERROR in /home/sean/github/CHAOSS/augur/frontend/src/views/Dashboard.vue
355:12 Cannot find name 'color_mapping'. Did you mean the instance member 'this.color_mapping'?
    353 | 
    354 |     for (let i = 0; i < this.highest.length; i++) {
  > 355 |       if (!color_mapping[this.highest[i].ri_metric])
        |            ^
    356 |         this.highest.splice(i, 1)
    357 |     }
    358 |   }

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! augur-f@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the augur-f@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sean/.npm/_logs/2019-10-09T22_13_20_346Z-debug.log

**To Reproduce:**

**Expected behavior:**
Successful Build

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: N/A

**Comment by gabe-heim** [comment]
Production build of the front end no longer has any of these errors, if different behavior occurs on the deployed instances please let me know and reopen @sgoggins
