### ISSUE TITLE
 Augur schema link is not working

### ISSUE THREAD

**Issue by vinodkahuja** [chaoss/augur#412]
Augur Schema link is Dependencies section of installation instruction is not working. 

- PostgreSQL 11 installation with the Augur schema installed

**Comment by GeorgLink** [comment]
It would be advisable to use a relative path to /augur/persistence_schema folder ... 

In that folder, it would be great to add information on how to import the SQL files to Postgres

**Comment by sgoggins** [comment]
@vinodkahuja : What link are you referrign to?

**Comment by vinodkahuja** [comment]
![Capture](https://user-images.githubusercontent.com/25468243/66758486-fcaed500-ee63-11e9-8137-b9f5a0f2df34.JPG)

**Comment by sgoggins** [comment]
This is fixed.
