### ISSUE TITLE
Not all TLDR Links are active

### ISSUE THREAD

**Issue by germonprez** [chaoss/augur#415]
**Describe the bug:**
Not all links to TLDR licenses are working

**To Reproduce:**
Go here: http://science.osshealth.io/repo/Senaite/senaite.core/risk

**Expected behavior:**
All links should work to TLDR

**Screenshots**
http://science.osshealth.io/repo/Senaite/senaite.core/risk

**Desktop (please complete the following information):**
Mac/Firefox

**Additional context**
@Nebrethar could you check this out.

**Comment by sgoggins** [comment]
@Nebrethar : This may be a result of the instance being deployed prior to this functionality being developed. Please advise. I do have the latest augur version as of Friday deployed here, but we may need to rerun the risk analysis with `augur-sbom`.

**Comment by ccarterlandis** [comment]
We discussed on the CHAOSS call today that we may need to change this from TLDR to SPDX. Would it be a problem/confusing if we provided both links, since they have different information available? @Nebrethar @germonprez

**Comment by germonprez** [comment]
That's a good idea

**Comment by Nebrethar** [comment]
Sorry for the late reply. I am looking now into how we can migrate this to SPDX links

**Comment by Nebrethar** [comment]
SPDX provides a "see here" link for every single license.

I have created a pull request to change to these links.

Please note that some nomos tags possess some ambiguity and cannot be linked out.

**Comment by sgoggins** [comment]
We are changing these to SPDX license links.
