### ISSUE TITLE
Top Graph on Insights not Rendering Well 

### ISSUE THREAD

**Issue by germonprez** [chaoss/augur#417]
**Describe the bug:**
Top Graph on Insights not Rendering Well 

**To Reproduce:**
http://science.osshealth.io/inspect_insight/Samvera/https:%2F%2Fgithub.com%2Fsamvera%2Fmaintenance.git/issues-new/

**Expected behavior:**
The graph is just rendering funny

**Screenshots**
<img width="828" alt="Screen Shot 2019-10-14 at 9 13 37 AM" src="https://user-images.githubusercontent.com/656208/66757987-fb30dd00-ee62-11e9-8451-0fe4fe0f9de8.png">

**Desktop (please complete the following information):**
Mac/Firefox 

**Additional context**
@sgoggins and @gabe-heim

**Comment by sgoggins** [comment]
@gabe-heim : I confirmed that this is an issue on both Chrome and Firefox.

**Comment by sgoggins** [comment]
This is in progress and will be released soon.

**Comment by Nebrethar** [comment]
Issue related to #401 Also, @sgoggins has this been fixed lately?

**Comment by ccarterlandis** [comment]
This graph looks like it no longer renders in this wonky format, at least on augur.osshealth.io
