### ISSUE TITLE
make install costs too much time

### ISSUE THREAD

**Issue by JerryKuan** [chaoss/augur#534]
Hi, augur team.
I am installing the project step by step according to the guidence. when I execute "make install" below the picture, it costs too much time , which has taken 2 hours. Is it normal? if not, what I should do? 
![Screen Shot 2020-01-14 at 21 27 36](https://user-images.githubusercontent.com/22657829/72348585-ad539b80-3715-11ea-8a6d-c66cb805ac2a.png)
<img width="1076" alt="Screen Shot 2020-01-14 at 21 27 15" src="https://user-images.githubusercontent.com/22657829/72348598-b5134000-3715-11ea-939c-075c11ea0561.png">

OS: ubuntu16
thanks in advance~

**Comment by JerryKuan** [comment]
the result of the code is stuck ‘Installing backend dependencies...’

**Comment by JerryKuan** [comment]
@sgoggins

**Comment by ccarterlandis** [comment]
Hi @JerryKuan, I'm sorry to hear you've been experiencing some difficulties. Could you provide the output of `logs/backend-install.log` and `logs/backend-install.err` to help us debug what the cause might be?

Additionally, can you also provide the specifications of the system you're doing the install on? I am unable to reproduce this problem, the install consistently only takes ~5 to 10 minutes tops for me on my 2015 MacBook Pro.

**Comment by JerryKuan** [comment]
Thanks for your reply. I have sovled it using many times "control + C". it just hand on, and not show the following infomation. when I want to kill it, enter many "control + C", it works.
 `logs/backend-install.err` shows  in the first picture.
<img width="1026" alt="Screen Shot 2020-01-15 at 09 48 01" src="https://user-images.githubusercontent.com/22657829/72398134-e5da9000-377c-11ea-9b8d-141e33069510.png">
`logs/backend-install.log` shows in the second picture. however, I just select the last because it is too long. 
<img width="1249" alt="Screen Shot 2020-01-15 at 09 50 29" src="https://user-images.githubusercontent.com/22657829/72398211-41a51900-377d-11ea-9b04-e73daa248eb2.png">
  
OS : Ubuntu16.04
CPU:2 core
Memory: 8G 
total memory:20G

thanks again!
