### ISSUE TITLE
Insight Detail page fails to load

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#541]
**Describe the bug:**
I went to check on issue #417 and could not load any Insight Detail pages

**To Reproduce:**
1. Go to Insights Page
2. Click on any button that says "View Insight Details ->"
3. No-load; Check console

**Expected behavior:**
I was expecting to see an insight page

**Screenshots**
![image](https://user-images.githubusercontent.com/34951354/73283347-994d7680-41b8-11ea-9faf-3574aea59f85.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome 79

**Additional context**
#417

**Comment by Nebrethar** [comment]
**Also Additional Context**

This was tested on augur.osshelath.io

**Comment by ccarterlandis** [comment]
My initial closure was in error, this issue is still happening.

**Comment by aksh555** [comment]
@Nebrethar @ccarterlandis  I've been trying to solve this issue,
Investigating the logs, the error is in /frontend/src/components/charts/InsightChart.vue calculateVegaSpec() while trying to get clientWidth, clientHeight.
I've tried modifying it by using `let specWidth = ReactDOM.findDOMNode(this.refs.holder).clientWidth * 0.75;   let specHeight = ReactDOM.findDOMNode(this.refs.holder).clientHeight * 0.75;`  
which is loading the main insights page but some inner graphs are not getting rendered yet..

![insights_issue](https://user-images.githubusercontent.com/25505971/75932773-4ee9a480-5e9e-11ea-8829-e9ebd1ca9781.png)

Any suggestions on proceeding further..

**Comment by aksh555** [comment]
@ccarterlandis @Nebrethar  I am unable to reproduce the error on augur.osshelath.io. In fact no chart loads in the Insight dashboard. 
Is this issue already solved? If not, could you please provide some details. I am interested in working on it

**Comment by sgoggins** [comment]
This is fixed, @Nebrethar
