### ISSUE TITLE
Popup drawing over insight link

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#542]
**Describe the bug:**
When I hover over a project link on the insights page (format xxxxx/yyyyy.git), a popup box will draw over the link and prevent me from clicking it.

**To Reproduce:**
1. Go to Insights Page on augur.osshealth.io
2. Hover over project link

**Expected behavior:**
I expected to be able to click the link

**Screenshots**
https://imgur.com/a/kKWZFUq

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 79

**Comment by ccarterlandis** [comment]
The popup now appears to the side of the label, instead of over it, making the link clickable again 😊
