### ISSUE TITLE
Request: Only show insight cards that show meaningful data

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#543]
**Is your feature request related to a problem? If so, please describe the problem:**
Some cards on the insight page will show data that has only been collected since recently, which becomes a single line on the graph that is hard to read.

**Describe the solution you'd like:**
I suggest we have a minimum age for the data. This would limit the data to be at leat x-old before it is shown.

**Describe alternatives you've considered:**
We could leave the data as-is, but it provides results like this on a regular basis:

![image](https://user-images.githubusercontent.com/34951354/73285034-0b26bf80-41bb-11ea-928e-bfebad18cf49.png)

**Comment by pratikmishra356** [comment]
@ccarterlandis Currently http://augur.osshealth.io not showing any insights 
![Screen Shot 2020-03-23 at 6 57 15 PM](https://user-images.githubusercontent.com/43684300/77321550-5d5a0c00-6d38-11ea-952e-f7cfa2f72089.png)

but when I run augur on local host it shows insights 
![Screen Shot 2020-03-23 at 6 57 27 PM](https://user-images.githubusercontent.com/43684300/77321960-fb4dd680-6d38-11ea-8671-89239070ff4e.png)
Could you explain why insights not showing on augur's website

**Comment by ccarterlandis** [comment]
@pratikmishra356 that version of Augur is likely rather outdated (even if the UI doesn't show it). We'll see what we can do about fixing it. @sgoggins

**Comment by pratikmishra356** [comment]
Thanks @ccarterlandis 
Let me know if I can work on any issue related to insights.

**Comment by sgoggins** [comment]
@pratikmishra356 : I think the biggest issue right now is that we only see the date range for the anomaly period, instead of the training period. @gabe-heim made some fixes to the insight worker so that anomalies are more clearly identified. Do you feel comfortable with front end adjustments?

**Comment by pratikmishra356** [comment]
@sgoggins  I looked into recent commits made by @gabe-heim in the insight worker including deletion of old insights.Currently insight_model uses "training_period" but not the confidence_interval_insights as it uses anomaly_days only.I think we need both anomaly days and training period.I am comfortable with front end  , I know Vue.js and also learned about Vega-lite.
