### ISSUE TITLE
UI Tweaks for clarity

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#549]
Some small tweaks to the UI: 

![Screen Shot 2020-02-12 at 16 22 50](https://user-images.githubusercontent.com/379847/74384988-18959980-4db8-11ea-8e6b-7656ae5d6183.png)
![Screen Shot 2020-02-12 at 16 19 08](https://user-images.githubusercontent.com/379847/74384991-19c6c680-4db8-11ea-9b3b-2380e03bfb22.png)

**Comment by sgoggins** [comment]
ignore the last image .. just the first two.

**Comment by abhiandthetruth** [comment]
@sgoggins shall i work on this one.

**Comment by sgoggins** [comment]
@michaelwoodruffdev : Can you look into this?

**Comment by sgoggins** [comment]
Fixed.
