### ISSUE TITLE
GSoC & Outreachy GitLab Worker Construction Microtask Ideas

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#559]
## Here's some ideas: 

1. Microtask 0: Familiarize yourself with augur by downloading and configuring the dev branch. For a little more context about what we are trying to accomplish with Augur's prototyping, checkout Augur's documentation at : https://oss-augur.readthedocs.io/en/dev/   Fork Augur into your own GitHub Account. Work in the dev branch. 
2. Microtask 1: When you install Augur, choose to load sample data. This will help you see the structure. Augur can count commits for any `git` repository, so our main task for GitLab is connected to their corollaries for issues, pull requests, and comments/events around those "things". The GitHub worker is a good example of a worker for GitHub that manages two "models", and a good, concrete place for familiarizing yourself with our current worker architecture. https://github.com/chaoss/augur/tree/dev/workers/github_worker ... Now you have two choices: 
 - choice 1: Refactor or optimize the current GitHub worker to be more modular, easier to understand, more efficient, more robust, or improved in any way you imagine OR
 - choice 2: Familiarize yourself with the GitLab API and write a python program that successfully authenticates and pulls data from the API into JSON or other data files stored locally. We do NOT expect you to write a worker in this task, just demonstrate you figured out a little bit about the GitLab API: https://docs.gitlab.com/ee/api/README.html ... you can put your code in a new subfolder under "workers" in the `dev` branch with your GitHub ID as the folder name. 
3. Microtask 2: Make a pull request to update the dev branch with the work from Microtask 1. If you have questions about getting started in the steps above, open an issue in the Augur repository.

**Comment by isaeef** [comment]
@sgoggins Thanks  for the microtask :)

**Comment by StrangeNoob** [comment]
Thanks @sgoggins for these Microtasks. Loved to work/contribute on this Project.

**Comment by bawantha** [comment]
Thanks for the micro tasks @sgoggins .

**Comment by Adarsh-NP** [comment]
Hello,
What is the api key that we need to provide in this while setting up augur in our local machine?

**Comment by mrsaicharan1** [comment]
@Adarsh-NP Hi there! Unfortunately, No one would be able to provide you with an API key for obvious security reasons! You can read more about the best practices pertaining to an API key [here](https://medium.com/hyperquant/api-keys-and-why-do-you-need-them-7da1462d871). You can generate a Github specific API key right here [here](https://github.com/settings/tokens)

**Comment by Adarsh-NP** [comment]
Hey, thanks for replying. So this means that I should generate my own personal access token to access github api? 
Because from what I know there are two types of github api's the private ones are the ones not shared for security reasons but that's not the case with the public one's in I'm not wrong.

**Comment by gabe-heim** [comment]
@Adarsh-NP Yes, you need to generate your own personal access token. There is only 1 API key that it will generate (not a public and private one) and it should be kept private. Do not push your key anywhere, as github will disable it if you do so.

**Comment by abhinavbajpai2012** [comment]
Hi All, 
I am Abhinav Bajpai from IIT Dhanbad. I am willing to contribute to this idea for GSoC 2020. During my previous data engineering summer internship, I have developed data collector workers to fetch data from JIRA, Salesforce, Sage Intacct, ElasticSearch and AWS-Redshift and warehouse the data in Google BigQuery. I would love to develop a similar worker for GitLab as well :D

**Comment by abhinavbajpai2012** [comment]
@sgoggins Can you tell me what data would be sufficient for choice 2 of microtask 1? I am currently thinking to store all the projects, their branches and issues along with some details like timestamp, creator etc.

**Comment by ccarterlandis** [comment]
Hello everyone! I have just finished setting up our Slack workspace for applicants, and am happy to invite anyone who is applying for Augur for GSoC 2020. If you would like to be added to the channel, please send me an at c@carterlandis.com with your name and the email address you like me to send the invite to. If you already got an invite from me, you can use it, or if you like I can send it to a different email address. 😊

**Comment by ccarterlandis** [comment]
GSoC submissions are over and applicants have been selected. Thank you to everyone who submitted!
