### ISSUE TITLE
Data Analysis from issue_events.txt File [Gsoc Microtasks]

### ISSUE THREAD

**Issue by pratikmishra356** [chaoss/augur#564]
Extracted Data in meaningful manner from txt file and did some Data preprocessing.
Then visualised actions of chaoss different repositories with time

![Screen Shot 2020-02-29 at 2 51 54 PM](https://user-images.githubusercontent.com/43684300/75604842-15621380-5b03-11ea-94a4-06a6e438634a.png)

**Comment by ccarterlandis** [comment]
Hi @pratikmishra356, if you're submitting your work on a microtask, please open a pull request from your fork as outlined in the microtasks. You can find links to each microtask in the body of the first comment of #545.
