### ISSUE TITLE
`pull_request_closed_no_merge` metric is broken

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#572]
**Describe the bug:**
The `pull_request_closed_no_merge` metric returns a 500 internal server error.

**To Reproduce:**
1. Checkout `dev`
2. Run `augur run --disable-housekeeper`
3. Hit `http://localhost:5000/api/unstable/repo/21000/pull-request-closed-no-merge`
4. Observe error

**Expected behavior:**
I expected the metric to return a valid response object, even if it was empty.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS v 10.14.6

**Additional context**
I noticed that there is a missing `GROUP_BY` clause in the SQL query, based on the usage of `COUNT`. This appears to be the main culprit of the issue.

Broken Travis build: https://travis-ci.org/chaoss/augur/builds/657396384

**Comment by mrsaicharan1** [comment]
@ccarterlandis Has this been occurring only for the empty objects?

**Comment by mrsaicharan1** [comment]
I think It's a 404 error  :sweat_smile:

**Comment by ccarterlandis** [comment]
Check out this line of the metrics test: https://travis-ci.org/chaoss/augur/jobs/657396385#L581. You'll see the SQL error I'm referring to

**Comment by ccarterlandis** [comment]
I didn't even notice this earlier, but the metrics API test is also failing because the route is incorrect. It should be `...unstable/repos/...` instead of `.../unstable/repo/` - this is why it's returning a 404. I'd also suggest using the same repo ID in both your metric and API test.

**Comment by mrsaicharan1** [comment]
> Check out this line of the metrics test: https://travis-ci.org/chaoss/augur/jobs/657396385#L581. You'll see the SQL error I'm referring to

Gotcha, I see where the error is now. I'll send in a fix ASAP

**Comment by mrsaicharan1** [comment]
I'll fix both of them in a PR.

**Comment by mrsaicharan1** [comment]
Closing this in favor of #573
