### ISSUE TITLE
Template for proposal is missing in interest page for Outreachy

### ISSUE THREAD

**Issue by NodiraIbrogimova** [chaoss/augur#640]
Is there a proposal template that we should follow as an Outreachy applicant? I see one provided [here](https://github.com/chaoss/governance/blob/master/GSoC-interest.md) for `GSoC` applicants. 

Should we follow the same template? 
If **yes** or **no** can you please provide details about that?

In outreachy requirements, we have a form to (just) record the contribution and writing description for every single contribution made during the process. I thought we should follow that page and provide information there, but I see some people providing proposals.

Also, if there is no fixed proposal template for outreachy applicants what should our proposal include? 

I might have some page or information providing guidelines about proposal or templates... Please, kindly help with this @ccarterlandis @sgoggins @germonprez

**Comment by sgoggins** [comment]
@NodiraIbrogimova : Follow the same template, or whatever instructions Outreachy provides applicants. We are not going to evaluate the form of proposal, we are interested in the content.

**Comment by NodiraIbrogimova** [comment]
@sgoggins, thank you for a detailed answer. 

Another question is, does the proposal with the template in GSoC has to be completed upon finishing the microtasks. I mean does this fall into the requirements of `augur` project application?

As for outreachy, they asked to record a contribution link, date and description. No template or proposal is mentioned (unless there is some document they will ask after contributions are completed).

**Comment by NodiraIbrogimova** [comment]
On submission of the contribution (after completing contribution on the chosen project(s)), `outreachy` prompts to write essay questions. I'm not sure whether it's allowed to write those questions here.
Closing this issue.
