### ISSUE TITLE
Enforcing DRY principles -- Optimization of test suites

### ISSUE THREAD

**Issue by mrsaicharan1** [chaoss/augur#648]
**Describe the enhancement**
Currently, there are many tests that are repetitive, i.e:
For example:
```
def test_issue_comments_mean_std_by_group(metrics):
    response = requests.get('http://localhost:5000/api/unstable/repo-groups/10/issue-comments-mean-std')
    data = response.json()
    assert response.status_code == 200
    assert len(data) >= 1

def test_issue_comments_mean_std_by_repo(metrics):
    response = requests.get('http://localhost:5000/api/unstable/repo-groups/10/repos/25430/issue-comments-mean-std')
    data = response.json()
    assert response.status_code == 200
    assert len(data) >= 1

def test_issue_comments_mean_std_by_repo(metrics):
    response = requests.get('http://localhost:5000/api/unstable/repo-groups/10/repos/25430/issue-comments-mean-std')
    data = response.json()
    assert response.status_code == 200
    assert len(data) >= 1
```

Instead of this, we could write a common function that
could be called across these tests to incorporate readability, reusability and proper maintenance.

***Additional info***
Working on this.

**Comment by sgoggins** [comment]
@mrsaicharan1 : I believe we merged a pull request where you made these optimizations. Can this be closed?

**Comment by mrsaicharan1** [comment]
There are additional files which require this optimization. I'll be fixing them up in the linked PR!

**Comment by sgoggins** [comment]
@mrsaicharan1 : OK ... you might need to open a new PR, as we merged the first one!

**Comment by ccarterlandis** [comment]
This can be accomplished more robustly with pytest fixtures and marks. See https://github.com/chaoss/augur/blob/dev/tests/test_routes/test_util_routes.py for an example 🛠️

**Comment by mrsaicharan1** [comment]
Yup! This works!

**Comment by sgoggins** [comment]
Great!
