### ISSUE TITLE
List of all the broken links in the documentation

### ISSUE THREAD

**Issue by Adarsh-NP** [chaoss/augur#667]
Here are all the links in the installation guide and readme file that needs to be fixed.

[Installation page](https://oss-augur.readthedocs.io/en/dev/getting-started/installation.html):
The links to Make file commands and data collection documentation, at the bottom of the page, are broken.   

In the installation page, it would be a great help to someone who is starting with the downloads to include the information about the npm incompatibility errors that may arise during the installation of the front-end dependencies because even I took some days to realise that those warnings won't affect the installation and running of augur and was busy figuring out how to solve those errors and warnings.

[Build a visualisation](https://oss-augur.readthedocs.io/en/dev/getting-started/create-a-metric/frontend.html)
Build a visualisation link redirects to the same page. Is it done on purpose or is an error in linking the pages.

[Library commands](https://oss-augur.readthedocs.io/en/dev/getting-started/available-commands/library-commands.html):
In the util section the link to the python library documentation is broken.

[Overview](https://oss-augur.readthedocs.io/en/dev/getting-started/create-a-metric/overview.html):
The link to the worker documentation at the bottom of the page is broken.

[Architecture](https://oss-augur.readthedocs.io/en/dev/architecture/architecture.html):
The link to Requests is broken.

[Readme.md](https://github.com/chaoss/augur/tree/doc-a-thon):
The links in GETTING STARTED sections are broken.

**Comment by Pogayo** [comment]
Hello @Adarsh-NP,

Some of these broken links are already fixed in the documentation that is going on in the doc-a-thon branch. Please check-out the doc-a-thon version of the documentation for the latest version of the documentation. As an example, your recommendations to the errors that arise when installing front-end dependencies are there. Here is [the link](https://oss-augur.readthedocs.io/en/doc-a-thon/getting-started/installation.html)

I have been exploring the documentation on the branch and I will be happy to work with you to improve it.

**Comment by Adarsh-NP** [comment]
Hello sir, thanks for clarifying...but somehow it didn't work for me a day before when I opened it in my laptop. 
I'll look at it again because I am pretty sure I was in doc-a-thon branch only.

I'll verify once again.
Thanks a lot.

**Comment by Pogayo** [comment]
I hope it works.  
I am female, so she/her works for me.

**Comment by Adarsh-NP** [comment]
Oh I am so sorry, actually I replied directly from the mail so didn't know about that.

**Comment by Pogayo** [comment]
I am sorry I closed this accidentally

**Comment by Pogayo** [comment]
> Oh I am so sorry, actually I replied directly from the mail so didn't know about that.

It's okay.

**Comment by ccarterlandis** [comment]
Documentation has been reworked as of v0.12.0, so these links have been fixed.
