### ISSUE TITLE
generating API Docs fails

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#682]
**Describe the bug:**
```
(augur) sean@omaha:~/github/augur-pivotal$ make install-dev
Checking for the correct version of Python 3...
Sufficient version of Python found at /home/sean/github/virtualenvs/augur-pivotal/bin/python. Resuming installation...
Checking for pip...
Sufficient form of pip detected at /home/sean/github/virtualenvs/augur-pivotal/bin/pip. Resuming installation...
Checking for virtual environment...
Virtual environment detected under /home/sean/github/virtualenvs/augur-pivotal. Resuming installation...

*****INSTALLING FOR DEVELOPMENT*****

Installing the backend and its dependencies...
Done!
Installing workers and their dependencies...
Done!
Generating a config file...
** Config file was found. Resuming installation... **
Done!
Generating documentation...
make: *** [Makefile:40: install-dev] Error 2
(augur) sean@omaha:~/github/augur-pivotal$ 
```

**To Reproduce:**
1. `make install-dev` on a clean virtualenv. Possibly a clean machine
2. First I got a failure where I realized that `apidoc` was not in the requirements.txt file, so I didn't have that. 
3. `pip install apidoc`
4. error above

**Expected behavior:**
Getting to the front end installation even if the building of API docs fails, or API Doc building not failing. 

**Desktop (please complete the following information):**
 - Ubunutu 18

**Additional context**
`dev` branch.

**Comment by ccarterlandis** [comment]
`apidoc` is a JavaScript library, not a Python one. If `npm` is not configured correctly it will not be able to install the package before the script to generate the API docs is run. This is the primary reason we will be getting rid of it ASAP, requiring a Javascript library in a Python package makes no sense and the current API docs solution is not very useful or easy to work with.

**Comment by ccarterlandis** [comment]
Can you please provide the log files? There might be other things that are failing out, but I can't fix the problem unless I know exactly what went wrong.

**Comment by sgoggins** [comment]
Full access sent in Slack. Note: Ubuntu 19: 
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
