### ISSUE TITLE
Ideas for front-end improvement

### ISSUE THREAD

**Issue by NodiraIbrogimova** [chaoss/augur#690]
I have been reviewing the front-end of Augur and there are some suggestions that I would like to mention for its improvement.

- I see that typescript has been added to the frontend, but it doesn't seem to be used/supported widely. 
e.g., The components are not still using `ts` as a `lang` option.

- Vue (devs) recommend using **single-file components** and with high probability (in my opinion,) that's applicable when every small part is **divided**/clustered **to single components**. 
In augur's case, there are components that have bigger size both in `template` and `script` sections. 
_Note: I might be wrong, as I'm new in the project and developers might have taken something into account for future cases._
 
How about splitting `template`, `script` and `style` sections into **separate files**? 
_This best practice can be seen in **Angular**._

- Why comments are still kept in (prod.) code?
When the previous feature has to be recovered, I think it's better to **copy** it from the **history of commits**. When the project gets bigger, it can be hard to maintain code that is needed and to delete unnecessary parts.
_It can be hard to remember which part was commented on and had to be deleted._ 

- How about moving index.html file to the root of the frontend source folder? It would make it more clear for the newcomer to distinguish the structure of the project.

- Making a list of naming standards for parts (e.g, images in assets, ) 

**Additional info:**
If mentors and project members support (some of) ideas, I would like to finish the work I have done by now and discuss further development until May.
Listed suggestions have been sent to @michaelwoodruffdev and I would like to have his support as well, on this discussion.

**Comment by ritikavar** [comment]
I am beginner i want to take this  from where i start

**Comment by NodiraIbrogimova** [comment]
> I am beginner i want to take this from where i start

Hi @ritikavar, nice to read that!
I have fixed some of the issues mentioned above in my last pull request. Could you explain your experience in more detail? Which part would you like to start with?
In addition, you can ask team members and mentors of this project for more information. Their names are mentioned in this `issue`

**Comment by sgoggins** [comment]
These are excellent ideas. This is on our roadmap.

**Comment by Adarsh-NP** [comment]
Ok, how about we use React for this? React is way more popular and widely supported than Angular. In my opinion that would be better but I would like to know the views of admins on this.

**Comment by MohitPatni0731** [comment]
Can I work on this issue
