### ISSUE TITLE
Implementation of Issue Worker - Gitlab

### ISSUE THREAD

**Issue by mrsaicharan1** [chaoss/augur#725]
**Worker Implementation Pathway & Description**
Setup the basic components in the `__init__` method and write data collection functions for issues, assignees, comments etc

**Potential solutions:**
Setting up the DB, capturing data from GitLab API Model & relaying it back to our tables in the Postgres schemas in the corresponding format. 
Additional metadata is also included.

**Additional context:**
I just created this issue to have a proper workflow for the issue worker!

**Comment by mrsaicharan1** [comment]
I'll be creating a few sub-issues alluding to this one so that as soon as we wrap up with all of them, we can close this one directly! *It's a long way but just an FYI :)*

**Comment by sgoggins** [comment]
Are we doing well here? I think we are. Scale testing is important next.
