### ISSUE TITLE
Provision for GitLab API key in the generated config

### ISSUE THREAD

**Issue by mrsaicharan1** [chaoss/augur#730]
**Feature Description**
As we're moving towards the implementation of the Gitlab workers, we need to add the GitLab API key in the config file [`augur.config.json`]. The script which generates this config file should be changed accordingly
**Additional context:**
Will solve this asap, as this would aid in the initial setup.

**Comment by sgoggins** [comment]
@mrsaicharan1 : @gabe-heim and @sgoggins also need to address standard methods for the workers and schema so that you can supply additional credentials in the `worker_oauth` table.

**Comment by mrsaicharan1** [comment]
Implemented in #733
