### ISSUE TITLE
Simple worker log output tail function (or error checker)

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#738]
It would be good if we had a single command or method that would identify errors, or at least show the end of logfiles for every worker

**Potential solutions:**
I wrote a quick little shell script, but its brittle to the instance because its got to know what port the workers are using to know the names of the logfiles.  It also does a simple tail. No error checking or reporting. 

A better solution would be a log reading package that sent notifications or collected errors somehow. Not all the log info is stored in the table in augur_operations. 

**Here's my simple shell script that is brittle to the instance**

```
echo ======================================================================
echo BEGIN
echo =contributor=====================================================================
tail contributor_worker/worker_49500.log 
echo =facade=====================================================================
tail facade_worker/worker_50100.log 
echo ======================================================================
echo =github=====================================================================
tail github_worker/worker_50200.log 
echo ======================================================================
echo =insight=====================================================================
tail insight_worker/worker_50300.log 
echo ======================================================================
echo =linux badge=====================================================================
tail linux_badge_worker/worker_50400.log 
echo ======================================================================
echo =pull request=====================================================================
tail pull_request_worker/worker_50600.log 
echo ======================================================================
echo =repo info=====================================================================
tail repo_info_worker/worker_50700.log 
echo ======================================================================
echo =value=====================================================================
tail value_worker/worker_50800.log 
echo ======================================================================
echo ======================================================================
echo ======================================================================
echo DONE
```

**Comment by ccarterlandis** [comment]
Reposting my comment in our Slack channel here, for posterity's sake (slightly edited):

> The simple worker log output functionality already exists in Augur. You can use `./scripts/control/status.sh` to get the last 20 lines of every worker’s logs, as well as the main Augur logs. Passing `interactive` to the script as an argument (like `./scripts/control/status.sh interactive`) pipes every file through `less` allowing you to browse them one by one. While we do not have notification or "log reader" capability, there are other more pressing problems with our logging infrastructure that deserve our attention first. 
> 
> Right now, the backend server logger is not configurable at all (i.e. can't configure formats, verbosity, log level, or message filters) and the logs are not stored at all. None of the workers loggers can be configured either, so I think our effort is better served improving the base logging infrastructure first; without useful logs to read, a log reader library is not very useful. I've been actively working on solving this problem in the workers as part of some of the changes I've had to make for testing, so I have a good handle on how to set it up for the main Augur process.

We can leave this issue open to discuss these necessary core logging changes, or we can use a new one dedicated to that (my preference). I would like to close this issue since the script already exists and we're not ready for the extended functionality, but it's your call @sgoggins

**Comment by ccarterlandis** [comment]
The basics of our new logging infrastructure has been implemented, which includes an output viewer and automatic error collection. I propose we move forward with separate issues for advanced features now that the groundwork is complete.
