### ISSUE TITLE
Implementation of Message Insights Worker

### ISSUE THREAD

**Issue by aksh555** [chaoss/augur#740]
**Worker Description**
Fetch data from relevant tables and analyze sentiment and detect unique/outlier messages related to issues and PRs. Send useful insights to _Auggie_.

**Approach**
Perform sentiment and outlier analysis in Jupyter notebooks using different models. Choose best ones and transfer to worker.

**Additional Context**
This issue is just to keep a track of the progress/discussions.

**Comment by sgoggins** [comment]
PR Merged.
