### ISSUE TITLE
Repo info worker does not collect data successfully

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#747]
**Description:**
The `repo_info_worker` does not successfully collect data. After connecting to the broker and starting its collection process, it runs into several errors, and then stops without inserting any data.

**How to reproduce:**
1. Check out the `dev` branch of Augur, and start the backend with `augur run`
2. Start the `repo_info_worker`
3. Wait until connection is successful and data collection is started

**Expected behavior:**
I expect the data collection process to succeed.

**Screenshots**
n/a, see log files below

**Log files**
Repo info worker error message:
```
INFO:com.augurlabs.core.repo_info_worker.50700:Traceback (most recent call last):
  File "/Users/carter/projects/work/augur/workers/worker_base.py", line 247, in collect
    model_method(message, repo_id)
  File "/Users/carter/projects/work/augur/workers/repo_info_worker/repo_info_worker.py", line 151, in repo_info_model
    forked = self.is_forked(owner, repo)
  File "/Users/carter/projects/work/augur/workers/repo_info_worker/repo_info_worker.py", line 234, in is_forked
    data = self.get_repo_data(self, url, r)
TypeError: get_repo_data() takes 3 positional arguments but 4 were given
```

**Software versions:**
 - Augur: `v0.12.0`
 - OS: macOS 10.14.6

**Notes**
The issues is that the calls to `get_repo_data()` in the `worker.py` file are incorrect in both `is_forked()` and `is_archived()`. They pass `self` as an argument, but also call the method with `self`, which isn't how to call an instance method in Python.

There is also another issue I noticed while investigating: the insert statement that inserts the data into the database also fails with a `sqlalchemy.exc.CompileError: Unconsumed column names: repo_archived, repo_archived_date_collected, forked_from`. This is because those columns have been added to the `repo` table, but the insert statement is trying to insert it into the `repo_info` table. There will need to be a separate update statement that updates the appropriate tuples in that table, or the database will need to be refactored to store those columns in the `repo_info` table.

**Comment by ccarterlandis** [comment]
For some reason I still can't assign this to you @ivanayov but if you could take a look when you get a chance that would be very helpful!

**Comment by sgoggins** [comment]
@ccarterlandis : I think @ivanayov has less time in the coming weeks. She has not accepted the invitation to the CHAOSS org yet, so that's why we cannot assign it to her.

**Comment by ccarterlandis** [comment]
This is actually already fixed, I just forgot to close this issue
