### ISSUE TITLE
Refactoring base worker class to adjust with the Gitlab API.

### ISSUE THREAD

**Issue by abhinavbajpai2012** [chaoss/augur#755]
This thread is to discuss the changes needed to be made in the base worker class before starting with the Gitlab data collection workers.

**Comment by abhinavbajpai2012** [comment]
Currently we have pointed out that changes are required in the methods dealing with-

- Authentication
- Task status registration (Completion and Failure)
- Pagination
- Querying gitlab contributors
- Rate limit updater
- Finding id from login

**Comment by abhinavbajpai2012** [comment]
@ccarterlandis @gabe-heim could there be some additional adjustments we might need to make, to make it compatible with the upcoming Gitlab workers?

**Comment by mrsaicharan1** [comment]
@abhinavbajpai2012 Pagination & rate-limiting functions are done in my WIP PR. Currently working on & find id from login.
 Will test & notify as soon as everything is gtg
