### ISSUE TITLE
Identify outlier, "within repository" comments or comment threads

### ISSUE THREAD

**Issue by sarit-adh** [chaoss/augur#767]
Classifying a comment as an outlier within a particular comment thread and across all comment threads in the repository. A comment  semantically different from other comments will be classified as an outlier

**Comment by sgoggins** [comment]
@sarit-adh : Updates?

**Comment by sarit-adh** [comment]
Experimental work on the following notebook
https://github.com/chaoss/augur/blob/sarit/notebooks/comments_clustering_and_anomaly_detection.ipynb
Didn't get good results, not part of the final worker.
