### ISSUE TITLE
make rebuild-dev asks about installing front end

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#798]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
Previously, if Augur had been installed already, the developer is not prompted if they want to install front end dependencies.  I don't know if this change is intentional or not. But now it does. 

**How to reproduce:**
1. Clone the `dev` or `testing` branch
2. `make rebuild-dev`

**Expected behavior:**
Just rebuilds the front end

**Log files**
```
Successfully installed value-worker
WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Would you like to install Augur's frontend dependencies? [Y/n] Y
Installing...

```

**Comment by ccarterlandis** [comment]
The frontend is classified as “optional” in the initial install process, so there is no gurantee the user wants the frontend to be installed at all or already has the external dependencies required to build it.
