### ISSUE TITLE
Can't get docker compose w/database-compose to work

### ISSUE THREAD

**Issue by cjellick** [chaoss/augur#801]
**Description:**
I installed augur using docker-compose, but it seems comands that write to the db fail. When I try to create a repo group, I get an error. I don't think other commands are working either, but dont know for sure.

**How to reproduce:**
1. Install augur using this command: `docker-compose -f docker-compose.yml -f database-compose.yml up`
2. Go to the UI
3. Attempt to create a repo group

**Expected behavior:**
Repo group creation succeeds.

**Log files**
```
backend_1   | 172.19.0.1 - [23/Jun/2020:22:56:30 +0000] - OPTIONS /api/unstable/create-repo-group HTTP/1.1
backend_1   | 2020-06-23 22:56:30 8157cdbc23ec augur.server[145] ERROR Exception on /api/unstable/create-repo-group [POST]
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
backend_1   |     response = self.full_dispatch_request()
backend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
backend_1   |     rv = self.handle_user_exception(e)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
backend_1   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
backend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
backend_1   |     reraise(exc_type, exc_value, tb)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
backend_1   |     raise value
backend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
backend_1   |     rv = self.dispatch_request()
backend_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
backend_1   |     return self.view_functions[rule.endpoint](**req.view_args)
backend_1   |   File "/usr/local/lib/python3.6/site-packages/augur/routes/manager.py", line 62, in create_repo_group
backend_1   |     if authenticate_request(server._augur, request):
backend_1   |   File "/usr/local/lib/python3.6/site-packages/augur/routes/manager.py", line 325, in authenticate_request
backend_1   |     retrieved_api_key = operations_db.execute(update_api_key_sql).fetchone()[0]
backend_1   | TypeError: 'NoneType' object is not subscriptable
backend_1   | 172.19.0.1 - [23/Jun/2020:22:56:30 +0000] - POST /api/unstable/create-repo-group HTTP/1.1
```

**Software versions:**
 - Augur: (you can use `pip show augur` to find your version)
```
root@8157cdbc23ec:/augur# pip show augur
Name: augur
Version: 0.12.0
Summary: Python 3 package for free/libre and open-source software community metrics & data collection
Home-page: https://github.com/chaoss/augur
Author: Derek Howard
Author-email: derek@howderek.com
License: MIT
Location: /usr/local/lib/python3.6/site-packages
Requires: beaker, psycopg2-binary, flask, gunicorn, coloredlogs, flask-wtf, click, flask-login, psutil, six, flask-cors, sqlalchemy, pandas, requests
Required-by:
```
 - OS: (`sw_vers` for macOS, `lsb_release -a` on Linux)
Im running from the docker container
```
8157cdbc23ec        augurlabs/augur:backend    "/bin/sh -c 'augur d…"   43 minutes ago      Up 42 minutes       0.0.0.0:5000->5000/tcp, 0.0.0.0:50100-50800->50100-50800/tcp   augur_backend_1
e1345f974cda        augurlabs/augur:frontend   "/docker-entrypoint.…"   43 minutes ago      Up 43 minutes       80/tcp, 0.0.0.0:8080->8080/tcp                                 augur_frontend_1
22f19ac4182b        augurlabs/augur:database   "docker-entrypoint.s…"   43 minutes ago      Up 43 minutes       0.0.0.0:5434->5432/tcp                                         augur_database_1
```
 - Browser: (if applicable)

**Comment by csplinter** [comment]
I ran into this too. Digging into the code it looks like this gets called in the [Dockerfile](https://github.com/chaoss/augur/blob/master/util/docker/backend/Dockerfile#L25)
```
augur db update-api-key docker_key
```
Which is [running](https://github.com/chaoss/augur/blob/master/augur/cli/db.py#L260)
```
UPDATE augur_operations.augur_settings SET VALUE = :api_key WHERE setting='augur_api_key'
```
But if you go to your postgres db there is no row with that setting. You can fix it by manually running this in the psql shell.
```
INSERT INTO augur_operations.augur_settings (setting, value) VALUES ('augur_api_key', 'docker_key');
```

**Comment by cjellick** [comment]
thanks! will try it out

**Comment by sgoggins** [comment]
@ccarterlandis : Thoughts?

**Comment by ccarterlandis** [comment]
Thanks for the ping @sgoggins. I will take a look later tonight once I am off work

**Comment by ccarterlandis** [comment]
I think I figured it out, somehow the `augurlabs/augur:database` image had fallen several months out of date and was on version 14 instead of version 16, which has the correct schema and includes the default API key row (the absence of this default row is what was causing the error). I have a sneaky feeling that the GitHub integration we use to automatically build the images on releases is what caused it to get out of sync, so I rebuilt the image and pushed it manually.

@cjellick @csplinter when you get a chance, if you could pull the new `augurlabs/augur:database` image and try this again it would be much appreciated. I'll leave this open until I can confirm it's fixed for both of you 👍

**Comment by cjellick** [comment]
will do. to be honest, even after @csplinter's suggestion, i could get anything to work with the docker-compose deployment. Things just kind of hung. Maybe thisll fix that

**Comment by ccarterlandis** [comment]
Hmmm, that's odd. If it still happens feel free to post the logs and we'll see if we can get that sorted as well

**Comment by hogepodge** [comment]
I can confirm that docker-compose deployments aren't working right now. My auth token panel on GitHub is showing that the token has never been used.

**Comment by sgoggins** [comment]
@ccarterlandis : The database is now on version 25. We may need to double check docker again, though the tests appear to be passing. This may also be why the GSoC branch travis builds are currently failing.
