### ISSUE TITLE
PyPI Augur

### ISSUE THREAD

**Issue by jayvdb** [chaoss/augur#810]
Would it be possible to release this on PyPI?

https://pypi.org/project/Augur is an empty package, by a deleted user it seems.

I believe there is a process by which PyPI maintainers will re-allocate a package name if rationale is sane, such as mis-use, old maintainer no longer able to hand control over to new maintainers, etc.

At the very least it seems sensible to start going through that processes, so as to prevent someone else claiming it via that process.

**Comment by sgoggins** [comment]
We have requested PyPi installation.
