### ISSUE TITLE
Add unit/integration tests for helper methods, functions & modules across augur

### ISSUE THREAD

**Issue by mrsaicharan1** [chaoss/augur#822]
**Description**
Workers across our data collection platform import & utilize a lot of modules/functions. This is a parent issue related to improving the testability of the modules across augur.

**Comment by sgoggins** [comment]
How is this going, @mrsaicharan1 and @abhinavbajpai2012 ?

**Comment by ccarterlandis** [comment]
This is still important, but there is not really any useful information that was captured by this issue, so I'm going to close it. This work also needs to be better defined to be marked as a "good first issue"
