### ISSUE TITLE
Link not working in contributing.md

### ISSUE THREAD

**Issue by rochisha0** [chaoss/augur#879]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**
Developer installation link is incorrect in `CONTRIBUTING.MD`

**How to reproduce:**
1. Go to 'CONTRIBUTING.MD'
2. Scroll down to 'Contributing to the source code'
3. Click on 'development installation instruction'

**Expected behavior:**
This should have opened 'https://oss-augur.readthedocs.io/en/master/getting-started/installation.html'

This currently opens
https://oss-augur.readthedocs.io/en/doc-a-thon/development-guide/toc.html

**Comment by sgoggins** [comment]
Pull request merged into staging branch. To be released this week.
