### ISSUE TITLE
Augur Install fails to hide password when creating new roles

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/augur#911]
**Is your feature request related to a problem? If so, please describe the problem:**
When installing Augur, I tried to set up a local database. When creating database credentials, the password was not hidden while I was typing it in.

**Potential solutions:**
Please implement password hiding in the install, if you can.

**Additional context:**
The places I found this issue were in creating the default user credentials, and the overall database credentials. 
I would share a screenshot but I have two passwords in it.

**Comment by ccarterlandis** [comment]
I've honestly never even tried. I'll do some research, probably shouldn't be hard at all. This would be nice to have, but isn't a huge priority.

**Comment by Nebrethar** [comment]
I agree, it's not a high priority. I just had to include it as a different issue from my others as it's unique 😁

**Comment by ccarterlandis** [comment]
This has been fixed with the release of Augur v0.13.1.
