### ISSUE TITLE
Cannot find 'augur.config.json' file after 'make install'

### ISSUE THREAD

**Issue by gymgym1212** [chaoss/augur#912]
**Description:**
I followed the getting started guide to install Augur. When I stepped to _Collecting data_ part,  there is no  'augur.config.json' file at augur's root directory. Additionally, I also tried 'augur configure generate' and I got "CLI: [configure.generate] [INFO] augur.config.json successfully created" but nothing changed.

**Screenshots**
<img width="485" alt="image" src="https://user-images.githubusercontent.com/37684061/92593313-7d27c100-f2d3-11ea-9b68-1ab9f517eeab.png">

**Software versions:**
 - Augur: latest master
 - OS:
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021

**Comment by sgoggins** [comment]
@gymgym1212 : I have confirmed this issue on the current version of master. Working on a patch.

**Comment by sgoggins** [comment]
@gymgym1212 : a temporary workaround is to use `make install-dev`
I will still patch `make install`

**Comment by gymgym1212** [comment]
@sgoggins Thank you for your reply! It works!!

**Comment by ccarterlandis** [comment]
@sgoggins using `make install-dev` is not really a workaround, it is a different command that has a different purpose that could cause problems if people are actually trying to install for production. Please do not recommend it as a workaround.

An actual workaround would be to just copy the default config in `augur/config.py` into an `augur.config.json` file, and then change the credentials manually.

**Comment by ccarterlandis** [comment]
I have to stop for a few hours to have some meetings, but in my initial testing I have been unable to create this issue. I will update this comment later when done testing

**Comment by ccarterlandis** [comment]
I figured it out. I forgot that when you install the Python package WITHOUT `-e` using `make install`, the executable gets placed in the site-packages directory that lives in your virtualenv folder. When you install the Python package WITH `-e` using `make install-dev`, it installs the executable in the same place as your source code. Stupidly on my part, the config file location is relative to where the executable lives, so the augur.config.json file is actually getting created, but it's not in that `augur/` directory. I'll work on a fix for this ASAP.

**Comment by sgoggins** [comment]
This issue is resolved in the latest `dev` branch, which will be released today or tomorrow.
