### ISSUE TITLE
Automatically add new repos to Augur when a repo is added to a GitHub org that is already in Augur

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/augur#914]
We frequently add new repositories for new open source projects within existing GitHub orgs that are already tracked in Augur. It would be great if these new repositories were automatically discovered and added to the appropriate repo group within Augur. 

The problem is that I don't always know when we create new repos within our existing GitHub orgs, so these repos don't have any metrics unless I happen to notice it and get the repo added manually to Augur. 

For example, the vmware GitHub org (https://github.com/vmware) is already in the pivotal.osshealth.io Augur instance, but you can see that this recently added repository is missing from the org: https://github.com/vmware/go-ipfix

**Comment by geekygirldawn** [comment]
@sgoggins Here's the feature request we talked about. 

@ivanayov FYI in case this is something you are interested in working on :)

**Comment by ivanayov** [comment]
@geekygirldawn yep, I can take it.

**Comment by geekygirldawn** [comment]
@ivanayov Here are a few more repos from the VMware org that are missing from Augur if you'd like a few more for testing:
dod-compliance-and-automation
eslint-config-vmware-react
go-ipfix
jsonnet-lang-for-gazelle
kernel-event-collector-module
legacy-terraform-provider-vra7
live-docs
nsx-container-plugin-operator
vmware-eventlog-stream-console

@dstefka Here is the issue where we're tracking the progress of a new feature to automatically add new repositories to Augur from tracked orgs.

**Comment by ccarterlandis** [comment]
@ivanayov @geekygirldawn I don't know if you've made any progress on this, but I do have some thoughts on it that I am happy to share if you would like.

**Comment by ivanayov** [comment]
Hi @ccarterlandis,
I didn't start working on it yet. Feel free to share. Thanks

**Comment by geekygirldawn** [comment]
@ccarterlandis @ivanayov @sgoggins I wanted to follow up on this one, too. We've created a lot of new projects that I'd love to get into Augur :)

**Comment by jaskiratsingh2000** [comment]
@sgoggins @geekygirldawn Hello! As you might know, I have contributed to CHAOSS a lot and even helped CHAOSS build [Community Handbook](https://handbook.chaoss.community/community-handbook/) from scratch as a part of Google Season of Docs. I planned to explore the coding side now and am super interested to contribute here. As I am quite beginner in coding here and would like to take this issue to work on so @sgoggins @geekygirldawn @GeorgLink Can you please let me know exactly that how have to go ahead with this issue? I see that there is a discussion going around that I need to add the GitHub repo manually. So can you please let me know where exactly?

Looking forward to hearing from you. 

Thanks and Regards

**Comment by geekygirldawn** [comment]
@jaskiratsingh2000 I think @ivanayov has completed this work, but it may not have been merged yet.

I recommend talking to Sean and others on the Augur team to get suggestions for where to start.

**Comment by jaskiratsingh2000** [comment]
oh sure. @sgoggins Can you let me know, please?

**Comment by ivanayov** [comment]
@jaskiratsingh2000 I need to push and update addressing the latest refactoring of `WorkerBase` that go merged. I'm doing this at the moment, so will drop a message once ready. Thanks

**Comment by jaskiratsingh2000** [comment]
@ivanayov sure. Do let me know please

**Comment by ivanayov** [comment]
@jaskiratsingh2000 I just pushed an update in #1039

**Comment by jaskiratsingh2000** [comment]
Oh I see. You pushed the whole

**Comment by sgoggins** [comment]
This is resolved in the Augur release for Friday, September 17, 2021.
