### ISSUE TITLE
Build a worker or page (including endpoints) to show data collection completeness

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#932]
**Is your feature request related to a problem? If so, please describe the problem:**
We have an established set of queries and processes for determining how complete data collection is. They rely on at least one run of the repo_info worker, as we validate what Augur collects against platform (github/gitlab) metadata. 

**Potential solutions:**
These are the queries and shell commands: 

[current-scripts.zip](https://github.com/chaoss/augur/files/5299867/current-scripts.zip)

The steps involved would be first to develop API endpoints, following the patterns found in `$AUGUR_REPO_HOME/augur/metrics/ repo_meta.py`, probably creating a new python file titled something like `$AUGUR_REPO_HOME/augur/metrics/ collection_completeness.py` or whatever @ccarterlandis or @gabe-heim recommend. Those endpoints would essentially become "wrappers" around the attached `sql` scripts. The shell scripts are a little more complicated, so perhaps set those aside at first and focus on the `sql` scripts. 

**Additional context:**
A first step is to build and get Augur running. Please file issues here if you have difficulty.

**Comment by sgoggins** [comment]
@ccarterlandis : These are the scripts I referenced in our conversation yesterday.

**Comment by ccarterlandis** [comment]
Picking this up. I'm going to implement these as endpoints and not as a worker, so they can be queried on-demand by the frontend or some other reporting utility.

**Comment by ccarterlandis** [comment]
PR #941 implements a prototype version of this functionality.
