### ISSUE TITLE
Add SPDX license identifiers to all source code files

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#943]
Most of the existing project code has [SPDX license identifiers](https://spdx.dev/ids/) at the top of each file. However, some of the newer code, like the data collection workers, do not have license identifiers. Not only is this a best practice for clarity and transparency, we also provide SPDX data ourselves; since we often use this repo for testing, having complete coverage is desirable for another reason.

All of Augur is licensed under the MIT License. The license identifier should be the very first line of each file, and should be formatted exactly like so:
```
#SPDX-License-Identifier: MIT
```

See existing code in `augur/cli/` and `augur/metrics/` for examples.

**Comment by ajeurkar** [comment]
@ccarterlandis Could you please assign this to me?

**Comment by sgoggins** [comment]
@ajeurkar : It is done.

**Comment by ccarterlandis** [comment]
PR #947 implements this feature. Thanks again @ajeurkar!

**Comment by ajeurkar** [comment]
@ccarterlandis Thank you! 😄
