### ISSUE TITLE
Refactor all database access to use query parameters

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#944]
Currently, a good portion of Augur builds the SQL queries it uses by doing string concatenation by creating a string with SQL text and passing in the arguments (like the record values) via `.format()`. For example, lines 267-270 of `augur/housekeeper.py`: 
```
repoIdSQL = s.sql.text("""
    SELECT since_id_str FROM worker_job
    WHERE job_model = '{}'
""".format(job['model']))
```

While using `.format()` is fine for regular strings, using them to build SQL queries is very unsecure behavior. This is because `.format()` does not do any sanitization or escaping, meaning that unless the program checks beforehand, it would be very easy to pass to in a malicious string to one of these SQL statements and perform a SQL injection attack. Augur almost never checks these inputs, so we're at a high risk for a SQL injection attack that uses this method.

---------------------------
Augur needs to be updated to use query parameters, and not the `.format()` string, for all SQL requests. For an example using query parameters, see lines 132-136 of `augur/cli/db.py`:
```
updateRepoDirectorySQL = s.sql.text("""
        UPDATE augur_data.settings SET VALUE = :repo_directory WHERE setting='repo_directory';
""")

augur_app.database.execute(updateRepoDirectorySQL, repo_directory=repo_directory)
```

The last line shows how to specify the parameters when executing the statement, and query itself shows how to specify a query param in the body itself (`:<param_name>`), where `param_name` matches a `kwarg` `execute()`. 

**NOTE: there are quite a few ways to pass these parameters. See [the SQLAlchemy docs](https://docs.sqlalchemy.org/en/13/core/tutorial.html#using-textual-sql) for more details.**

**Comment by f-osorio** [comment]
I can work on this. Do you have any sense of which files have the SQL queries, or do I need to look around for them?

**Comment by ccarterlandis** [comment]
@f-osorio I think most of the `workers/` directory needs to be checked. All of the metrics in `augur/metrics/` already use query parameters, and most of the other database access operations happen in the workers, so I'd focus there first. Doing a global search for `read_sql` (like the `pandas` method) or `execute` (like the `sqlachemy` method) would probably also be useful.

**Comment by ccarterlandis** [comment]
@f-osorio would you like me to assign this issue to you?

**Comment by f-osorio** [comment]
Yeah, you can assign it to me.

**Comment by ccarterlandis** [comment]
Sorry, took me a few days to get back to this. Let me know if there is anything I can do to help you @f-osorio! Thanks!
