### ISSUE TITLE
Add database connection retry logic to Augur server

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#945]
Right now, the Augur server only attempts to make a connection to the database once, and if it fails, it immediately stops running and exits. Normally, this is fine, but sometimes when using Docker, the server container might become available before the database container is ready. To prevent this from happening more frequently, it would be good to have some retry logic in place (maybe 3 retries, first waiting 1s, then 3s, or 5s) for making this database connection. The exact number of retries or the timeout is up for debate

**Comment by chinvib66** [comment]
@ccarterlandis I would like to take up this issue

**Comment by ccarterlandis** [comment]
Hey @chinvib66, I'm so sorry I missed your comment when you made it a couple days ago. If you're still interested in working on this, use the `dev` branch as the base, as that's where we do our active development.
