### ISSUE TITLE
Show Gunicorn workers errors in errorfile and stdout

### ISSUE THREAD

**Issue by ccarterlandis** [chaoss/augur#946]
The Augur server is powered by Gunicorn workers handling requests in the background. Currently, when any of these workers encounter an error, it is not shown in the terminal/stdout, and it is not shown in either the `logs/augur.log` or `logs/augur.err` files, where all regular errors will always show up. Instead, it only gets written to `logs/gunicorn.log`, which isn't useful unless one knows to look in that file.

This behavior should be changed, either to surface the Gunicorn error directly in those files, or explicitly state that Gunicorn encountered an error and notify the user to check the Gunicorn log file.

**Comment by saptarsi96** [comment]
Hi, @ccarterlandis I would like to work on this.

**Comment by sajenjeshan1222** [comment]
is this open ?

**Comment by b-thebest** [comment]
Can I work on this issue ?

**Comment by sgoggins** [comment]
@b-thebest : YES!

**Comment by josselineperdomo** [comment]
Hello @sgoggins, is this issue still available? I'd like to work on it :)

**Comment by sgoggins** [comment]
@josselineperdomo : Yes
