### ISSUE TITLE
Front End API Call and Vue.JS Cleanup

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#981]
**Description:**
If you open the javascript console on an augur instance, such as http://augur.osshealth.io you will see a lot of javascript/typescript errors, as well as many calls to deprecated or unecessary APIs. All this slows the frontend down, and causes the user to have to wait, and click links several times. Production compilation of the node modules using `npm run build` also shows several errors where the size of what we are deploying will pose performance issues. 

Any work to "tidy this up", or even part of it, is most appreciated.

**Comment by ccarterlandis** [comment]
@kailynw done. Thanks for volunteering your time and energy, and please feel free to reach out if there's anything we can do to assist!

**Comment by sgoggins** [comment]
@kailynw : Any updates?
