### ISSUE TITLE
repo_info-collection on dev

### ISSUE THREAD

**Issue by sgoggins** [chaoss/augur#993]
Please help us help you by filling out the following sections as thoroughly as you can.

**Description:**

**How to reproduce:**

**Expected behavior:**

**Screenshots**
If applicable, add screenshots to help explain your problem. If your bug is related to the UI, you **must** include screenshots.

**Log files**
Attach the relevant log files here. Server and installation logs can be found in the `logs/` directory in the root `augur/` directory, and the logs for each worker are stored in their respective directories. If the logs are pretty long (> 50ish lines or just use your best judgement) please use a Gist or a [pastebin](https://pastebin.com/). **These logs file are required if you would like help solving your issue.**

**Software versions:**
 - Augur: (you can use `pip show augur` to find your version)
 - OS: (`sw_vers` for macOS, `lsb_release -a` on Linux)
 - Browser: (if applicable)

**Comment by ccarterlandis** [comment]
@sgoggins Is this an actual issue or did you open this by accident?
